"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { courses, offerings, tests, questions, testData } from "@/lib/api/domain";
import { apiFetch } from "@/lib/api/client";
import { useCurrentUser } from "@/lib/currentUser";
import { StudentAnswerSources } from "@/components/StudentAnswerSources";
import { GradingPreparation } from "@/components/GradingPreparation";
import { GradingWorkspace } from "@/components/GradingWorkspace";
import { GradingResults } from "@/components/GradingResults";
import { ReviewEntries } from "@/components/reviews/ReviewEntries";
import { SourcePdfPreview } from "@/components/SourcePdfPreview";
import { grading, type GradingOverview } from "@/lib/api/grading";
import type { Course, Offering, Test, Question, ModelAnswer, GradingPolicy, Rubric, SampleAnswer, Student, Submission, Readiness } from "@/types/domain";
import { Breadcrumbs, PageHeader, StatusBadge, ReadinessChecklist, LoadingState, ErrorState, EmptyState, TechnicalDetails } from "@/components/ui";
import { semesterLabel } from "@/lib/semester";
import { SourceUpload } from "@/components/SourceUpload";
import { MarkdownMathText, MarkdownMathPreview, markdownMathHelp } from "@/components/MarkdownMathText";
type Section = "overview" | "questions" | "answers" | "policy" | "samples" | "rubric" | "students" | "grading" | "results";
type WorkflowKey = Section | "review";
const labels: Record<Section, string> = { overview: "概要", questions: "問題", answers: "模範解答", policy: "採点方針", samples: "サンプル答案", rubric: "採点基準", students: "学生答案", grading: "採点", results: "結果" };
type WorkspaceReadiness = Readiness & { rubric_ready_count?: number; ready_gradable_count?: number; can_start_grading?: boolean };
interface Data { t: Test; o: Offering; c: Course; q: Question[]; a: ModelAnswer[]; p: GradingPolicy[]; r: Rubric[]; s: SampleAnswer[]; st: Student[]; sub: Submission[]; materials: import("@/types/domain").Material[]; ready: WorkspaceReadiness; overview: GradingOverview | null; }
export default function TestWorkspace() {
  const id = String(useParams().testId); const router = useRouter(); const params = useSearchParams(); const section = (params.get("section") as Section) || "overview";
  const currentUser = useCurrentUser();
  const [data, setData] = useState<Data | null>(null); const [error, setError] = useState(""); const [show, setShow] = useState(false);
  const [qForm, setQForm] = useState({ question_number: "", title: "", question_text: "", max_points: 10, sort_order: 0 }); const [policy, setPolicy] = useState(""); const [sample, setSample] = useState({ sample_key: "", transcription: "" }); const [student, setStudent] = useState({ student_identifier: "", display_name: "" });
  const refresh = async () => { const t = await tests.get(id); const [o, q, a, p, r, s, sub, materials, overview] = await Promise.all([offerings.get(t.course_offering_id), questions.list(id), testData.answers(id), testData.policies(id), testData.rubrics(id), testData.samples(id), testData.submissions(id), testData.materials(id), grading.overview(id).catch(() => null)]); const [c, st, ready, gradingReady] = await Promise.all([courses.get(o.course_id), testData.students(o.id), testData.readiness(id), apiFetch<{can_start_grading?: boolean; ready_gradable_count?: number}>(`/tests/${id}/grading-readiness`).catch(() => null)]); const displayReady: WorkspaceReadiness = gradingReady?.can_start_grading ? {...ready, ready: true, checks: {...ready.checks, grading_policy: true, question_grading_readiness: true}, blocking_reasons: [], blocking_codes: [], can_start_grading: true, ready_gradable_count: gradingReady.ready_gradable_count} : {...ready, can_start_grading: gradingReady?.can_start_grading}; setData({ t, o, c, q, a, p, r, s, st, sub, materials, ready: displayReady, overview }); };
  useEffect(() => { refresh().catch(e => setError(e instanceof Error ? e.message : "読み込みに失敗しました")); }, [id]);
  const mutate = async (fn: () => Promise<unknown>) => { try { await fn(); await refresh(); setShow(false); } catch (e) { setError(e instanceof Error ? e.message : "保存に失敗しました"); } };
  if (error) return <ErrorState message={error} />; if (!data) return <LoadingState />;
  const { t, o, c, q, a, p, r, s, st, sub, materials, ready, overview } = data; const gradable = q.filter(x => x.is_gradable !== false); const points = gradable.some(x => x.max_points === null) ? "未設定" : gradable.reduce((sum, x) => sum + (x.max_points ?? 0), 0); const currentAnswer = a.find(x => x.is_current); const currentPolicy = p.find(x => x.is_current); const approved = r.find(x => x.status === "approved"); const go = (x: WorkflowKey) => x === "review" ? router.push(`/tests/${id}/grading/review`) : router.push(`/tests/${id}?section=${x}`);
  const statuses = workflowStatuses({section, q, a, approved, sub, overview, ready}); const next = nextAction({q, a, approved, sub, overview, ready});
  return <><Breadcrumbs items={[{ label: "科目", href: `/courses/${c.id}` }, { label: c.name, href: `/courses/${c.id}` }, { label: `${o.academic_year}年度 ${semesterLabel(o.term,o.term_label)}`, href: `/offerings/${o.id}` }, { label: t.name }]} /><PageHeader title={t.name}><div className="actions"><StatusBadge status={t.status} /><Link className="button secondary" href={`/tests/${id}/grading`}>採点結果を確認</Link></div></PageHeader><p className="muted">{c.name}　{`${o.academic_year}年度 ${semesterLabel(o.term,o.term_label)}`}　{t.test_date || "実施日未定"}　合計 {t.total_points}点</p><NextAction next={next} go={go} compact /><WorkflowIndicator statuses={statuses} go={go} /><div className="workspace-navigation-sticky"><nav className="workspace-nav" aria-label="テスト準備">{(Object.keys(labels) as Section[]).map(x => <button key={x} className={section === x ? "active" : ""} onClick={() => go(x)}>{labels[x]}</button>)}</nav><nav className="secondary-nav" aria-label="詳細設定"><span>追加設定:</span><button onClick={() => go("policy")}>採点方針</button><button onClick={() => go("samples")}>サンプル答案</button></nav></div>
    {section === "overview" && <><section className="panel"><h2>入力資料の登録状況</h2><p>資料の登録と採点準備の完了は別です。設問・模範解答・採点基準・読み取り内容の確認を続けてください。</p><div className="cards"><Summary title="問題用紙" value={`${materials.filter(m=>m.material_type.includes("question_sheet")).length}ファイル`} onClick={()=>go("questions")}/><Summary title="模範解答資料" value={`${materials.filter(m=>m.material_type==="model_answer_source").length}ファイル`} onClick={()=>go("answers")}/><Summary title="学生答案" value={`${sub.length}件`} onClick={()=>go("students")}/><Summary title="採点基準" value={approved?"承認済み":"未承認"} onClick={()=>go("rubric")}/></div></section><ReadinessChecklist readiness={ready} /><div className="cards"><Summary title="問題" value={`${q.length}問`} detail={`${points} / ${t.total_points}点`} onClick={() => go("questions")} /><Summary title="模範解答" value={currentAnswer ? "登録済み" : "未登録"} onClick={() => go("answers")} /><Summary title="採点方針" value={currentPolicy ? "登録済み" : "未登録"} onClick={() => go("policy")} /><Summary title="採点基準" value={approved ? "承認済み" : "未承認"} onClick={() => go("rubric")} /><Summary title="サンプル答案" value={`${s.length}件`} onClick={() => go("samples")} /><Summary title="学生答案" value={`${sub.length}件 / ${st.length}名`} onClick={() => go("students")} /></div></>}
    {section === "questions" && <><SourceUpload testId={id} role="question_sheet" materials={materials} refresh={refresh}/><ReviewEntries testId={id} /><Questions testId={id} q={q} points={points} total={t.total_points} questionMaterial={materials.find(x => x.material_type === "question_sheet" || x.material_type === "corrected_question_sheet")} form={qForm} setForm={setQForm} show={show} setShow={setShow} onSave={() => mutate(() => questions.create(id, qForm))} onUpdated={refresh} /></>}
    {section === "answers" && <><SourceUpload testId={id} role="model_answer_source" materials={materials} refresh={refresh}/><GradingPreparation testId={id} questions={q} answers={a} rubrics={r} mode="answers" reviewer={currentUser?.id} refresh={refresh} /></>}
    {section === "policy" && <Editor title="採点方針" current={currentPolicy ? `登録済み（${currentPolicy.policy_text.length}文字）` : "未登録（任意）"} button="新しい版を作成" show={show} setShow={setShow} description="採点方針は、このテスト全体に共通する採点ルールを記載する場所です。未入力でも採点できます。必要な場合のみ設定してください。" examples={["計算式が正しければ、単純な計算ミスには部分点を与える。", "同値な数式表現は正答として扱う。", "記述問題では、要点が含まれていれば表現の違いは許容する。"]}><form className="form" onSubmit={e => { e.preventDefault(); mutate(() => testData.createPolicy(id, { policy_text: policy })); }}><div className="field"><label>テスト全体の採点方針</label><textarea required value={policy} onChange={e => setPolicy(e.target.value)} /></div><button className="button">保存</button></form></Editor>}
    {section === "samples" && <Editor title="サンプル答案" current={s.length ? `${s.length}件登録済み` : "登録なし（任意）"} button="サンプル答案を追加" show={show} setShow={setShow} description="サンプル答案は、典型的な正答・部分点答案・誤答などと、その採点例を登録するための補助機能です。通常は未登録のままで構いません。" examples={["この程度の説明なら5/10点", "式は正しいが計算ミスがある場合", "図は正しいがラベルが不足している場合"]}><form className="form" onSubmit={e => { e.preventDefault(); mutate(() => testData.createSample(id, sample)); }}><div className="field"><label>サンプル識別子 *</label><input required value={sample.sample_key} onChange={e => setSample({ ...sample, sample_key: e.target.value })} /></div><div className="field"><label>転記</label><textarea value={sample.transcription} onChange={e => setSample({ ...sample, transcription: e.target.value })} /></div><button className="button">保存</button></form></Editor>}
    {section === "rubric" && <GradingPreparation testId={id} questions={q} answers={a} rubrics={r} mode="rubric" reviewer={currentUser?.id} refresh={refresh} />}
    {section === "students" && <><SourceUpload testId={id} role="student_answer_source" materials={materials} students={st} submissions={sub} refresh={refresh}/><Editor title="学生答案" current={`学生 ${st.length}名　答案 ${sub.length}件`} button="学生を追加" show={show} setShow={setShow}><h3>登録済み答案</h3>{sub.length ? <table className="table"><thead><tr><th>答案</th><th>状態</th><th>試行</th></tr></thead><tbody>{sub.map(x => <tr key={x.id}><td>下の学生選択欄で確認</td><td>{x.status === "processed" ? "処理済み" : "登録済み"}</td><td>{x.attempt_number}回目</td></tr>)}</tbody></table> : <p className="muted">答案はまだ登録されていません。</p>}<form className="form" onSubmit={e => { e.preventDefault(); mutate(() => testData.createStudent(o.id, student)); }}><div className="field"><label>学籍番号 *</label><input required value={student.student_identifier} onChange={e => setStudent({ ...student, student_identifier: e.target.value })} /></div><div className="field"><label>氏名</label><input value={student.display_name} onChange={e => setStudent({ ...student, display_name: e.target.value })} /></div><button className="button">保存</button></form></Editor><StudentAnswerSources testId={id} submissions={sub} students={st} questions={q} /></>}
    {section === "grading" && <GradingWorkspace testId={id} questions={q} submissions={sub} />}{section === "results" && <GradingResults testId={id} questions={q} submissions={sub} />}</>;
}
type WorkflowState = "COMPLETE" | "CURRENT" | "REVIEW_REQUIRED" | "NOT_STARTED";
interface WorkflowEntry { key: WorkflowKey; label: string; state: WorkflowState }
function WorkflowIndicator({statuses, go}: {statuses: WorkflowEntry[]; go: (section: WorkflowKey) => void}) { const labels: Record<WorkflowState, string> = { COMPLETE: "完了", CURRENT: "現在", REVIEW_REQUIRED: "要確認", NOT_STARTED: "未実施" }; return <nav className="workflow-indicator" aria-label="作業の進み具合">{statuses.map(step => <div key={step.key} className={`workflow-step ${step.state.toLowerCase()}`}><button type="button" onClick={() => go(step.key)}>{step.label}</button><span className="step-status">{labels[step.state]}</span></div>)}</nav>; }
function NextAction({next, go, compact = false}: {next: {label: string; detail: string; section: WorkflowKey} | null; go: (section: WorkflowKey) => void; compact?: boolean}) { if (!next) return null; return <section className={`next-action${compact ? " compact" : ""}`} aria-label="次に行う作業"><div><h2>次に行う作業</h2><p>{next.detail}</p></div><button className="button" type="button" onClick={() => go(next.section)}>{next.label} ›</button></section>; }
function workflowStatuses({section, q, a, approved, sub, overview, ready}: {section: WorkflowKey; q: Question[]; a: ModelAnswer[]; approved?: Rubric; sub: Submission[]; overview: GradingOverview | null; ready: WorkspaceReadiness}): WorkflowEntry[] {
  const gradable = q.filter(item => item.is_gradable !== false); const modelReady = gradable.length > 0 && gradable.every(item => a.some(answer => answer.question_id === item.id && answer.is_current && Boolean(answer.answer_text?.trim()))); const rubricReady = Boolean(approved) && (ready.rubric_ready_count ?? gradable.length) >= gradable.length;
  const completedJobs = overview?.students.filter(student => ["COMPLETE", "completed", "complete"].includes(student.status)) || []; const review = Boolean(overview?.totals.review_required_count) || Boolean(overview?.students.some(student => student.review_flags.length));
  const current = (key: Section) => section === key;
  return [{key: "questions", label: "1 問題", state: q.length ? "COMPLETE" : current("questions") ? "CURRENT" : "NOT_STARTED"}, {key: "answers", label: "2 模範解答", state: modelReady ? "COMPLETE" : current("answers") ? "CURRENT" : "REVIEW_REQUIRED"}, {key: "rubric", label: "3 採点基準", state: rubricReady ? "COMPLETE" : current("rubric") ? "CURRENT" : "REVIEW_REQUIRED"}, {key: "students", label: "4 学生答案", state: sub.length ? "COMPLETE" : current("students") ? "CURRENT" : "NOT_STARTED"}, {key: "grading", label: "5 採点", state: completedJobs.length ? "COMPLETE" : current("grading") ? "CURRENT" : ready.can_start_grading ? "CURRENT" : "NOT_STARTED"}, {key: "review", label: "6 要確認", state: review ? "REVIEW_REQUIRED" : completedJobs.length ? "COMPLETE" : "NOT_STARTED"}, {key: "results", label: "7 結果", state: completedJobs.length && !review ? "COMPLETE" : current("results") ? "CURRENT" : "NOT_STARTED"}];
}
function nextAction({q, a, approved, sub, overview, ready}: {q: Question[]; a: ModelAnswer[]; approved?: Rubric; sub: Submission[]; overview: GradingOverview | null; ready: WorkspaceReadiness}): {label: string; detail: string; section: WorkflowKey} | null {
  const gradable = q.filter(item => item.is_gradable !== false); if (!q.length) return {label: "問題を確認", detail: "問題構造を登録してください。", section: "questions"};
  if (gradable.some(item => !a.some(answer => answer.question_id === item.id && answer.is_current && Boolean(answer.answer_text?.trim())))) return {label: "模範解答を確認", detail: "未登録または未確認の模範解答があります。", section: "answers"};
  if (!approved || (ready.rubric_ready_count ?? gradable.length) < gradable.length) return {label: "採点基準を確認", detail: "承認済みの採点基準を確認してください。", section: "rubric"};
  if (!sub.length) return {label: "学生答案を確認", detail: "学生答案を登録してください。", section: "students"};
  if (overview?.totals.review_required_count || overview?.students.some(student => student.review_flags.length)) return {label: "要確認を開く", detail: "採点または再構成に教師確認が必要です。", section: "review"};
  if (!overview?.students.some(student => ["COMPLETE", "completed", "complete"].includes(student.status))) return {label: "採点を開始", detail: (ready.can_start_grading ?? ready.ready) ? "全準備が整っています。" : "採点開始前の準備を確認してください。", section: "grading"};
  return {label: "採点結果を確認", detail: "採点が完了しています。結果を確認してください。", section: "results"};
}
function Summary({ title, value, detail, onClick }: { title: string; value: string; detail?: string; onClick: () => void }) { return <button className="card summary" onClick={onClick}><h3>{title}</h3><div className="stat">{value}</div>{detail && <p className="muted">{detail}</p>}<span>開く ›</span></button>; }
function Editor({ title, current, button, show, setShow, description, examples, children }: { title: string; current: string; button: string; show: boolean; setShow: (v: boolean) => void; description?: string; examples?: string[]; children: React.ReactNode }) { return <section className="panel section"><h2>{title} <span className="status-text">任意</span></h2>{description && <div className="optional-help"><p>{description}</p><h3>記入例</h3><ul>{examples?.map(example => <li key={example}>{example}</li>)}</ul></div>}<pre className="answer-text">{current}</pre>{button && <button className="button" onClick={() => setShow(!show)}>{button}</button>}{show && children}</section>; }
function Questions({ testId, q, points, total, questionMaterial, form, setForm, show, setShow, onSave, onUpdated }: { testId: string; q: Question[]; points: number | string; total: number; questionMaterial?: import("@/types/domain").Material; form: { question_number: string; title: string; question_text: string; max_points: number; sort_order: number }; setForm: (v: typeof form) => void; show: boolean; setShow: (v: boolean) => void; onSave: () => void; onUpdated: () => Promise<void> }) { return <section className="section"><div className="question-comparison"><div className="question-table-pane"><div className="page-header"><h2>問題</h2><div className="source-pdf-toolbar"><button className="button" onClick={() => setShow(!show)}>問題を追加</button></div></div><p className="muted">採点対象の設問合計 {points} / {total}点 {points !== total && <span className="warn">（テスト合計と不一致）</span>}</p>{show && <form className="panel form" onSubmit={e => { e.preventDefault(); onSave(); }}><div className="field"><label>問題番号 *</label><input required value={form.question_number} onChange={e => setForm({ ...form, question_number: e.target.value })} /></div><div className="field"><label>タイトル</label><input value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></div><div className="field"><label>問題文</label><textarea value={form.question_text} onChange={e => setForm({ ...form, question_text: e.target.value })} /><small className="math-help">{markdownMathHelp}</small><MarkdownMathPreview source={form.question_text} /></div><div className="field"><label>配点 *</label><input type="number" min="0" required value={form.max_points} onChange={e => setForm({ ...form, max_points: Number(e.target.value) })} /></div><button className="button">保存</button></form>}{q.length === 0 ? <EmptyState message="問題が登録されていません" /> : <table className="table"><thead><tr><th>番号</th><th>タイトル</th><th>配点</th><th>問題文</th></tr></thead><tbody>{questionTree(q).map(({question: x, depth}) => <tr key={x.id}><td style={{paddingLeft: 12 + depth * 24}}>{x.display_label || x.question_number} <small>{x.is_gradable === false ? "構造のみ" : "採点対象"}</small></td><td>{x.title || "—"}</td><td>{x.is_gradable === false ? "—" : x.max_points ?? "配点未設定"}</td><td><MarkdownMathText source={x.question_text || "—"} />{x.provenance?.origin !== "review_import" && <QuestionTextEditor question={x} onUpdated={onUpdated} />}{x.provenance?.origin === "review_import" && <p className="muted">PDFから取り込んだ問題（読み取り専用）</p>}{x.content?.items.filter(i => i.type === "figure").map(i => <TechnicalDetails key={i.asset_id} label="図の技術情報"><code>{i.asset_id}</code></TechnicalDetails>)}</td></tr>)}</tbody></table>}</div><aside className="question-source-pane"><SourcePdfPreview testId={testId} material={questionMaterial} label="問題PDF" inline /></aside></div></section>; }

function questionTree(questions: Question[], parent: string | null = null, depth = 0): {question: Question; depth: number}[] {
 if (depth > questions.length) return [];
 return questions.filter(q => (q.parent_id || null) === parent).sort((a,b) => a.sort_order - b.sort_order || a.id.localeCompare(b.id)).flatMap(question => [{question, depth}, ...questionTree(questions, question.id, depth + 1)]);
}

function QuestionTextEditor({question, onUpdated}: {question: Question; onUpdated: () => Promise<void>}) {
  const [editing, setEditing] = useState(false);
  const [source, setSource] = useState(question.question_text || "");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const open = () => { setSource(question.question_text || ""); setEditing(true); setError(""); };
  const save = async () => {
    setBusy(true); setError("");
    try { await questions.update(question.id, {question_text: source}); await onUpdated(); setEditing(false); }
    catch (e) { setError(e instanceof Error ? e.message : "問題文を保存できませんでした。"); }
    finally { setBusy(false); }
  };
  return editing ? <div className="question-text-edit"><label>問題文の原文<textarea aria-label={`問題文の原文 ${question.question_number}`} value={source} onChange={e => setSource(e.target.value)} maxLength={100000} /></label><small className="math-help">{markdownMathHelp}</small><MarkdownMathPreview source={source} /><button className="button" type="button" disabled={busy} onClick={() => void save()}>変更を保存</button><button className="button secondary" type="button" disabled={busy} onClick={() => setEditing(false)}>キャンセル</button>{error && <p className="error" role="alert">{error}</p>}</div> : <button className="button secondary" type="button" onClick={open}>問題文を編集</button>;
}
