"use client";

import { useState } from "react";
import { grading, type GradingDetail } from "@/lib/api/grading";

export function TeacherActionForm({ item, testId, onDone }: { item: GradingDetail["questions"][number]; testId: string; onDone: () => void }) {
  const definitions = Array.isArray(item.rubric?.entry?.criteria) ? item.rubric.entry.criteria as Array<Record<string, unknown>> : [];
  const current = Object.fromEntries(item.criteria.map((row) => [String(row.criterion_id), Number(row.score ?? 0)]));
  const [scores, setScores] = useState<Record<string, number>>(current);
  const [reason, setReason] = useState(""); const [note, setNote] = useState(""); const [regradeReason, setRegradeReason] = useState("");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const total = definitions.reduce((sum, criterion) => sum + Number(scores[String(criterion.id)] || 0), 0);
  const saveDecision = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { await grading.teacherDecision(testId, item.student_answer.submission_id || "", item.question.id, { criterion_scores: definitions.map((criterion) => ({ criterion_id: String(criterion.id), score: Number(scores[String(criterion.id)] || 0) })), teacher_reason: reason, teacher_note: note || undefined }); setMessage("Teacher adjudicationを保存しました。"); onDone(); } catch (e) { setError(e instanceof Error ? e.message : "保存に失敗しました"); } finally { setBusy(false); } };
  const requestRegrade = async () => { setBusy(true); setError(""); setMessage(""); try { await grading.requestRegrade(testId, item.student_answer.submission_id || "", item.question.id, regradeReason); setMessage("REGRADING_REQUESTEDとして記録しました。"); onDone(); } catch (e) { setError(e instanceof Error ? e.message : "再採点依頼に失敗しました"); } finally { setBusy(false); } };
  return <div className="teacher-action-form"><p className="muted">保存はappend-onlyです。現在の合計: {total} / {item.question.max_points}</p>{item.regrade_requests.length > 0 && <span className="flag">REGRADING_REQUESTED</span>}{definitions.length > 0 && <form onSubmit={saveDecision} className="action-form"><h5>Teacher adjudication</h5>{definitions.map((criterion) => { const levels = Array.isArray(criterion.levels) ? criterion.levels as Array<Record<string, unknown>> : []; return <label className="action-field" key={String(criterion.id)}><span>{String(criterion.id)} ({String(criterion.points)}点)</span><select value={String(scores[String(criterion.id)] ?? levels[0]?.score ?? 0)} onChange={(event) => setScores({ ...scores, [String(criterion.id)]: Number(event.target.value) })}>{levels.map((level) => <option key={String(level.score)} value={String(level.score)}>{String(level.score)}点 — {String(level.description || "")}</option>)}</select></label>; })}<label className="action-field"><span>Teacher reason *</span><textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label><label className="action-field"><span>Optional note</span><textarea value={note} onChange={(event) => setNote(event.target.value)} /></label><button className="button" disabled={busy}>{busy ? "保存中…" : "Teacher adjudicationを保存"}</button></form>}<div className="action-form" id="regrade-actions"><h5>Request Regrade</h5><textarea placeholder="依頼理由" value={regradeReason} onChange={(event) => setRegradeReason(event.target.value)} /><button className="button secondary" disabled={busy || !regradeReason.trim()} onClick={requestRegrade}>Request Regrade</button></div>{message && <p className="ok">{message}</p>}{error && <p className="error">{error}</p>}</div>;
}
