import Link from "next/link";
import type { ReactNode } from "react";
export function Breadcrumbs({ items }: { items: Array<{ label: string; href?: string }> }) { return <nav className="breadcrumbs" aria-label="パンくず">{items.map((x, i) => <span key={`${x.label}-${i}`}>{x.href ? <Link href={x.href}>{x.label}</Link> : x.label}{i < items.length - 1 && <span className="sep">›</span>}</span>)}</nav>; }
export function PageHeader({ title, children }: { title: string; children?: ReactNode }) { return <div className="page-header"><h1>{title}</h1>{children}</div>; }
const statusLabels: Record<string, string> = { draft: "下書き", setup: "準備中", rubric_review: "採点基準確認中", ready: "採点準備完了", grading: "採点中", completed: "採点完了", archived: "アーカイブ" };
export function StatusBadge({ status }: { status: string }) { return <span className={`badge badge-${status}`}>{statusLabels[status] || "要確認"}</span>; }
export function TechnicalDetails({ children, label = "詳細情報" }: { children: ReactNode; label?: string }) { return <details className="technical-details"><summary>{label}</summary><div className="technical-details-content">{children}</div></details>; }
export function friendlyStatus(status: string): string { return ({ READY: "準備完了", READY_FOR_GRADING: "採点準備完了", BLOCKED: "準備が必要", COMPLETE: "完了", completed: "完了", completed_students: "完了", COMPLETED: "採点済み", REVIEW_REQUIRED: "要確認", INCOMPLETE: "未完了", NOT_STARTED: "未実施", INGESTED: "登録済み", PENDING: "処理待ち", published: "公開済み", unpublished: "未公開", regrading_requested: "再採点依頼済み" } as Record<string, string>)[status] || "確認が必要です"; }
export function friendlyWarning(code: string): string { return ({ ASSET_MISSING: "必要な資料が不足しています。", MISSING_SELECTED_RECONSTRUCTION: "答案の読み取り内容を確認してください。", GRADING_REVIEW_REQUIRED: "採点内容の確認が必要です。", GRADING_MODEL_INPUT_CONTRADICTION: "採点入力とモデル判定の整合を確認してください。", GRADING_MODEL_SELF_CONTRADICTION: "採点理由に矛盾があるため確認してください。" } as Record<string, string>)[code] || "確認が必要な項目があります。"; }
export function EmptyState({ message, action }: { message: string; action?: ReactNode }) { return <div className="empty"><p>{message}</p>{action}</div>; }
export function ErrorState({ message = "処理中にエラーが発生しました" }: { message?: string }) { return <div className="error" role="alert">{message}</div>; }
export function LoadingState() { return <div className="loading" aria-live="polite">読み込み中…</div>; }
export function ReadinessChecklist({ readiness }: { readiness: { ready: boolean; checks: Record<string, boolean>; blocking_reasons: string[]; blocking_codes?: string[] } }) { const labels: Record<string, string> = { questions: "問題", model_answers: "模範解答", grading_policy: "採点方針", approved_rubric: "採点基準の承認", student_submissions: "学生答案", score_ready: "配点設定", question_grading_readiness: "採点準備" }; return <section className="readiness"><h2>採点準備</h2><strong className={readiness.ready ? "ok" : "warn"}>{readiness.ready ? "採点を開始できます" : "準備が必要です"}</strong><ul>{Object.entries(readiness.checks).map(([k, v]) => <li key={k}><span aria-label={v ? "完了" : "未完了"}>{v ? "✓" : "△"}</span> {labels[k] || "確認項目"}</li>)}</ul>{!readiness.ready && readiness.blocking_reasons.length > 0 && <><p className="muted">準備が必要な項目があります。</p><TechnicalDetails label="詳細を表示">{readiness.blocking_reasons.map((reason, i) => <p key={i}>{reason}</p>)}{readiness.blocking_codes?.map(code => <code key={code}>{code} </code>)}</TechnicalDetails></>}</section>; }
