import {readFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {test,expect,type Page} from "@playwright/test";
import {confirmAnalysis,saveAuthoring} from "./authoringNotifications";

test.setTimeout(120000);
test.skip(!process.env.RUNTIME_MANAGER_E2E,"requires disposable real API / RuntimeManager harness");

async function calls(page:Page){return Promise.all(["ocr","math_ocr","ornith_rubric_draft","grader"].map(async profile=>{const data=await(await page.request.get(`${process.env.LLM_GRADER_RUNTIME_MANAGER_URL}/runtimes/${profile}/logs?tail=1000`)).json();return data.lines.filter((line:string)=>line.includes("POST /v1/chat/completions")).length;}));}

test("real Sample Q5 split children discover, correct, accept and reuse the Answer diagram",async({page},testInfo)=>{
 await page.setViewportSize({width:1600,height:1000});
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
 const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Real Sample Q5 diagram regression",total_points:100}});expect(created.status()).toBe(201);const tid=(await created.json()).id,base=`/api/v1/tests/${tid}`,authoring=base+"/authoring";
 await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();
 const materialSelect=page.getByLabel("利用資料",{exact:true}),controls=page.getByRole("group",{name:"利用資料の操作",exact:true}),selector=page.getByLabel("対象設問",{exact:true});
 async function add(role:string,file:string){await materialSelect.selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption(role);await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:file.split("/").at(-1)!,mimeType:"application/pdf",buffer:await readFile(file)});await page.getByRole("button",{name:"いいえ",exact:true}).click();await saveAuthoring(page);}
 async function analyze(){const result=page.waitForResponse(r=>r.request().method()==="POST"&&(/\/authoring\/(source-import|analyze-answer)$/.test(r.url())));await confirmAnalysis(page,controls,"解析");const response=await result;expect(response.status(),await response.text()).toBe(200);await expect(page.locator(".authoring-analysis-progress")).toHaveCount(0);}
 await add("question_sheet","../testData/SampleQ/sampleQ5.pdf");await analyze();
 let row=(await(await page.request.get(authoring)).json()).revision;const parent=row.snapshot.nodes.find((n:any)=>/問題\s*[3３]/.test(n.label.raw));expect(parent,JSON.stringify(row.snapshot.nodes.map((n:any)=>n.label))).toBeTruthy();
 await selector.selectOption(parent.stable_key);const question=page.locator("#authoring-question");await question.getByRole("button",{name:"本文編集",exact:true}).click();await question.getByRole("button",{name:"小問の分割案を作成",exact:true}).click();const proposal=page.getByRole("dialog",{name:/の分割案/});await expect(proposal).toBeVisible();const parts=proposal.locator(".authoring-split-block");let children=0;for(let i=0;i<await parts.count();i++){if(await parts.nth(i).getByRole("combobox").inputValue()==="child"){await parts.nth(i).getByLabel("小問名",{exact:true}).fill(`(${++children})`);}}expect(children).toBe(3);await proposal.getByRole("button",{name:"分割を適用",exact:true}).click();await saveAuthoring(page);
 await add("model_answer_source","../testData/SampleQ/modelAnswer/sampleQ5_modelAnswer.pdf");await analyze();
 row=(await(await page.request.get(authoring)).json()).revision;const nodes=row.snapshot.nodes,child=nodes.find((n:any)=>n.parent_key===parent.stable_key&&n.label.raw==="(1)");expect(child).toBeTruthy();
 const source=row.snapshot.domains.answer,diagnostics={questionNodes:nodes.filter((n:any)=>n.stable_key===parent.stable_key||n.parent_key===parent.stable_key),answerSource:{draft_id:source.draft_id,material_id:source.material_id,source_sha256:source.source_sha256,artifact_ref:source.artifact_ref,question_regions:source.question_regions}};
 await testInfo.attach("sample-q5-source-chain",{body:JSON.stringify(diagnostics,null,2),contentType:"application/json"});
 await selector.selectOption(child.stable_key);const answer=page.locator("#authoring-answer");if(!await answer.locator('[id^="authoring-candidate-"]').count()){await answer.getByRole("button",{name:"模範解答を追加",exact:true}).click();await saveAuthoring(page);}
 const candidate=answer.locator('[id^="authoring-candidate-"]').first();await candidate.getByRole("button",{name:"本文編集",exact:true}).click();const diagram=candidate.getByRole("region",{name:"模範解答の図",exact:true});
 const entryId=(await candidate.getAttribute("id"))!.replace("authoring-candidate-",""),endpoint=`${authoring}/entries/${entryId}/diagrams`,parentDiscovery=page.waitForResponse(r=>r.request().method()==="POST"&&r.url().includes(endpoint)&&r.url().includes("scope=parent"));
 await diagram.getByRole("button",{name:"図候補を確認",exact:true}).click();const response=await parentDiscovery;const body=await response.text();expect(response.status(),body).toBe(200);const result=JSON.parse(body);await testInfo.attach("sample-q5-diagram-discovery",{body,contentType:"application/json"});
 await expect(diagram.getByAltText("図1の切り出し範囲",{exact:true})).toBeVisible();
 await testInfo.attach("sample-q5-candidate-visible",{body:await page.screenshot(),contentType:"image/png"});
 expect(result.diagrams).toHaveLength(1);const record=result.diagrams[0];expect(record.scope).toBe("parent");expect(record.source_question_id).toBe(parent.stable_key);expect(record.assigned_question_id).toBe(child.stable_key);expect(record.material_id).toBe(source.material_id);expect(record.source_sha256).toBe(createHash("sha256").update(await readFile("../testData/SampleQ/modelAnswer/sampleQ5_modelAnswer.pdf")).digest("hex"));expect(record.automatic_bbox[1]).toBeGreaterThan(613);expect(record.crop_bbox[1]).toBeGreaterThanOrEqual(source.question_regions.find((r:any)=>r.question_id===parent.stable_key).top);
 await expect.poll(()=>diagram.getByAltText("図1の切り出し範囲",{exact:true}).evaluate(el=>(el as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
 // A crop in Problem 2 must remain invalid even though the PDF is shared.
 const outside=await page.request.post(`${endpoint}/${record.id}/crop-preview?question_id=${child.stable_key}&scope=parent`,{data:{expected_revision:row.edit_version,final_bbox:[330,400,530,500]}});expect(outside.status()).toBe(422);expect((await outside.json()).error.code).toBe("diagram_source_boundary");
 const beforeCorrection=await calls(page);await diagram.getByRole("button",{name:"範囲を修正",exact:true}).click();const box=record.automatic_bbox.map((value:number,i:number)=>value+(i<2?2:-2));for(const [i,label]of["左","上","右","下"].entries())await diagram.getByLabel(`図の範囲 ${label}`,{exact:true}).fill(String(box[i]));await diagram.getByRole("button",{name:"プレビューを更新",exact:true}).click();await expect(diagram.getByAltText("修正後の図の範囲",{exact:true})).toBeVisible();await diagram.getByRole("button",{name:"範囲を適用",exact:true}).click();await diagram.getByRole("button",{name:/^この図を(確認して)?使用$/}).click();await saveAuthoring(page);expect(await calls(page)).toEqual(beforeCorrection);
 row=(await(await page.request.get(authoring)).json()).revision;const accepted=row.snapshot.domains.answer.entries.find((e:any)=>e.id===entryId).diagram_records[0];expect(accepted.state).toBe("accepted");expect(accepted.teacher_adjusted).toBe(true);
 const second=nodes.find((n:any)=>n.parent_key===parent.stable_key&&n.label.raw==="(2)");await selector.selectOption(second.stable_key);if(!await answer.locator('[id^="authoring-candidate-"]').count()){await answer.getByRole("button",{name:"模範解答を追加",exact:true}).click();await saveAuthoring(page);}const sibling=answer.locator('[id^="authoring-candidate-"]').first();if(await sibling.getByRole("button",{name:"本文編集",exact:true}).count())await sibling.getByRole("button",{name:"本文編集",exact:true}).click();const siblingDiagram=sibling.getByRole("region",{name:"模範解答の図",exact:true});await expect(siblingDiagram.getByAltText("再利用できる図",{exact:true})).toBeVisible();await siblingDiagram.getByRole("button",{name:"この図を再利用",exact:true}).click();await saveAuthoring(page);expect(await calls(page)).toEqual(beforeCorrection);
 // Register the same physical PDF for Rubric; Answer provenance stays exact.
 await materialSelect.selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption("rubric_source");await page.getByRole("button",{name:"既存ファイルを再利用",exact:true}).click();await page.getByLabel("既存ファイル",{exact:true}).selectOption(source.material_id);await page.getByRole("button",{name:"採点基準として追加",exact:true}).click();await page.getByRole("button",{name:"いいえ",exact:true}).click();await saveAuthoring(page);const answerBeforeRubric=(await(await page.request.get(authoring)).json()).revision.snapshot.domains.answer;await analyze();expect((await(await page.request.get(authoring)).json()).revision.snapshot.domains.answer).toEqual(answerBeforeRubric);
 const afterRubric=await calls(page);await selector.selectOption(child.stable_key);if(await candidate.getByRole("button",{name:"本文編集",exact:true}).count())await candidate.getByRole("button",{name:"本文編集",exact:true}).click();await diagram.getByRole("button",{name:"図候補を確認",exact:true}).click();await expect(diagram.getByRole("button",{name:"使用中",exact:true})).toBeDisabled();expect(await calls(page)).toEqual(afterRubric);
 await selector.selectOption(second.stable_key);if(await sibling.getByRole("button",{name:"本文編集",exact:true}).count())await sibling.getByRole("button",{name:"本文編集",exact:true}).click();await expect(siblingDiagram.getByAltText("再利用できる図",{exact:true})).toBeVisible();await expect(siblingDiagram.getByRole("button",{name:"使用中",exact:true})).toBeDisabled();
 const persisted=(await(await page.request.get(authoring)).json()).revision;await page.reload();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();expect((await(await page.request.get(authoring)).json()).revision).toEqual(persisted);await page.getByRole("link",{name:"戻る",exact:true}).click();await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();expect((await(await page.request.get(authoring)).json()).revision).toEqual(persisted);await selector.selectOption(second.stable_key);if(await sibling.getByRole("button",{name:"本文編集",exact:true}).count())await sibling.getByRole("button",{name:"本文編集",exact:true}).click();await expect(siblingDiagram.getByAltText("再利用できる図",{exact:true})).toBeVisible();expect(await calls(page)).toEqual(afterRubric);
 const entries=persisted.snapshot.domains.answer.entries,firstSaved=entries.find((e:any)=>e.id===entryId).diagram_records[0],secondSaved=entries.find((e:any)=>e.authoring_question_key===second.stable_key&&e.diagram_records?.length).diagram_records[0];expect(firstSaved.crop_sha256).toBe(secondSaved.crop_sha256);expect(firstSaved.assigned_question_id).toBe(child.stable_key);expect(secondSaved.assigned_question_id).toBe(second.stable_key);for(const domain of["questions","model-answers","rubrics"])expect(await(await page.request.get(`${base}/${domain}`)).json()).toEqual([]);expect(errors).toEqual([]);
});
