import {confirmAnalysis,expectUnsavedAnalysisHint,saveAuthoring} from "./authoringNotifications";
import {test,expect,type Page} from "@playwright/test";
import {openAuthoringEditors} from "./authoringEditMode";
import {readFile} from "node:fs/promises";
test.setTimeout(150000);
test.skip(!process.env.RUNTIME_MANAGER_E2E,"isolated real API/production build required");
async function calls(page:Page){return Promise.all(["ocr","math_ocr","ornith_rubric_draft","grader"].map(async p=>{
 const data=await(await page.request.get(`${process.env.LLM_GRADER_RUNTIME_MANAGER_URL}/runtimes/${p}/logs?tail=1000`)).json();return data.lines.filter((s:string)=>s.includes("POST /v1/chat/completions")).length;
}));}
test("compact material controls, role-aware explicit analysis and every Test editing entry",async({page})=>{
 await page.setViewportSize({width:1920,height:1080});await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
 // Each runner repeat uses the same disposable database. Keep this fixture unique
 // so a prior repeat cannot make the course table locator ambiguous.
 const run=`${Date.now()}`;const exams=[];for(const name of ["Analysis access A","Analysis access B","Analysis access C"]){const result=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:`${name} ${run}`,total_points:10}});expect(result.status()).toBe(201);exams.push(await result.json());}
 const base=`/api/v1/tests/${exams[1].id}`,before=await calls(page);
 await page.goto(`/offerings/${seed.course_offering_id}`);for(const exam of exams){const row=page.getByRole("row").filter({hasText:exam.name});await expect(row.getByRole("link",{name:"編集",exact:true})).toHaveAttribute("href",`/tests/${exam.id}/authoring`);}
 await page.getByRole("row").filter({hasText:exams[1].name}).getByRole("link",{name:"編集",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${exams[1].id}/authoring$`));
 await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();await page.getByRole("button",{name:"設問を追加",exact:true}).click();await page.getByLabel("問題文",{exact:true}).waitFor({state:"attached"});await openAuthoringEditors(page);await page.getByLabel("問題文",{exact:true}).fill("Teacher saved Question");
 const controls=page.getByRole("group",{name:"利用資料の操作",exact:true}),select=page.getByLabel("利用資料",{exact:true});await select.selectOption("action:add");
 const bytes=await(await page.request.get(`/api/v1/tests/${seed.id}/materials/${process.env.MODEL_ANSWER_CLASSIFICATION_MATERIAL_ID}/file`)).body();
 const files:{id:string;material_type:string}[]=[];
 for(const [role,buffer] of [["model_answer_source",bytes],["rubric_source",bytes],["question_sheet",await readFile(process.env.QUESTION_MATH_PDF_PATH!)],["supplementary_source",bytes]] as const){
  await select.selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption(role);await expect(page.getByRole("button",{name:"PDFに戻る",exact:true})).toHaveCount(0);
  if(role==="rubric_source"){
    const registered=await(await page.request.get(base+"/materials")).json(),source=registered.find((m:{material_type:string})=>m.material_type==="model_answer_source");
    let uploads=0;const track=(request:{url:()=>string})=>{if(request.url().includes("/materials/upload"))uploads++;};page.on("request",track);
    await page.getByRole("button",{name:"既存ファイルを再利用",exact:true}).click();await page.getByLabel("既存ファイル",{exact:true}).selectOption(source.id);await page.getByRole("button",{name:"採点基準として追加",exact:true}).click();
    await expect(select).toContainText("採点基準 — model_answer_source.pdf");page.off("request",track);expect(uploads).toBe(0);expect(await calls(page)).toEqual(before);
    const bindings=await(await page.request.get(base+"/materials")).json(),rubric=bindings.find((m:{material_type:string})=>m.material_type==="rubric_source");expect(rubric.id).not.toBe(source.id);expect(rubric.sha256).toBe(source.sha256);expect(rubric.storage_ref).toBe(source.storage_ref);
  }else {await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:role+".pdf",mimeType:"application/pdf",buffer});await expect(select).toContainText(role+".pdf");}
 }
 files.push(...await(await page.request.get(base+"/materials")).json());
 await select.selectOption(files.find(m=>m.material_type==="supplementary_source")!.id);await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeDisabled();await expect(page.getByText("選択資料の解析: この資料は解析対象ではありません。",{exact:true})).toBeVisible();
 await select.selectOption(files.find(m=>m.material_type==="model_answer_source")!.id);await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeDisabled();await expectUnsavedAnalysisHint(page,controls);
 await page.getByRole("button",{name:/通知履歴、未読/}).click();await page.getByRole("region",{name:"通知履歴"}).getByRole("button",{name:"すべて既読"}).click();await page.getByRole("button",{name:"通知履歴を閉じる"}).click();
 await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeEnabled();expect(await calls(page)).toEqual(before);
 await expect(page.getByRole("button",{name:/通知履歴、未読1件/})).toBeVisible();await page.getByRole("button",{name:/通知履歴、未読/}).click();await expect(page.getByRole("region",{name:"通知履歴"})).toContainText("保存しました");await expect(page.getByRole("button",{name:/通知履歴、未読0件/})).toBeVisible();await page.getByRole("button",{name:"通知履歴を閉じる"}).click();
 const b=(await controls.boundingBox())!,dropdown=(await select.boundingBox())!,toolbar=(await page.locator(".review-workspace-source .pdf-pane-toolbar").boundingBox())!,pdf=(await page.locator(".pdf-pane-viewport").boundingBox())!;
 expect(b.height).toBeLessThan(48);expect(dropdown.width).toBeGreaterThan(170);expect(toolbar.y).toBeGreaterThanOrEqual(b.y+b.height);expect(pdf.height).toBeGreaterThan(550);expect(pdf.width).toBeGreaterThanOrEqual((await page.locator(".review-workspace-source").boundingBox())!.width*.8);
 for(const label of ["解析","差換え"]){const button=(await controls.getByRole("button",{name:label,exact:true}).boundingBox())!;expect(Math.abs(button.y-dropdown.y)).toBeLessThan(8);}
 const key=await page.getByLabel("対象設問",{exact:true}).inputValue(),previous=(await(await page.request.get(base+"/authoring")).json()).revision;
 const observed:string[]=[];page.on("request",r=>{if(r.method()==="POST"&&(r.url().includes("analyze-answer")||r.url().includes("question-materials")))observed.push(r.url());});
 await controls.getByRole("button",{name:"解析",exact:true}).click();const questionDialog=page.getByRole("dialog");await expect(questionDialog).toBeVisible();await expect(questionDialog).toContainText("模範解答の解析結果だけを更新します");await expect(questionDialog).toContainText("問題文・小問構成は変更しません");await expect(questionDialog).toContainText("採点基準の編集内容も保持されます");await questionDialog.getByRole("button",{name:"キャンセル",exact:true}).click();expect(await calls(page)).toEqual(before);
 await confirmAnalysis(page,controls,"解析");await expect(page.getByRole("status").filter({hasText:"模範解答を解析しています…"})).toBeVisible();await expect(controls.getByRole("button",{name:"解析中…",exact:true})).toBeDisabled();
 await expect(page.locator(".authoring-toast").filter({hasText:"模範解答を解析しました"})).toBeVisible();await expect(page.locator(".authoring-toast").filter({hasText:/対応済み/})).toBeVisible();await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();await page.getByLabel("対象設問",{exact:true}).selectOption(key);await expect(page.getByLabel("問題文",{exact:true})).toHaveValue("Teacher saved Question");
 const analyzed=(await(await page.request.get(base+"/authoring")).json()).revision;expect(analyzed.id).not.toBe(previous.id);expect(analyzed.revision).toBe(previous.revision+1);expect(observed).toHaveLength(1);
 const after=await calls(page);expect(after[2]).toBeGreaterThan(before[2]);
 // Reanalysis requires explicit confirmation; cancelling changes neither revision nor runtime calls.
 await controls.getByRole("button",{name:"再解析",exact:true}).click();const answerDialog=page.getByRole("dialog");await expect(answerDialog).toContainText("模範解答の解析結果だけを更新します");await expect(answerDialog).toContainText("問題文・小問構成は変更しません");await expect(answerDialog).toContainText("採点基準の編集内容も保持されます");await answerDialog.getByRole("button",{name:"キャンセル",exact:true}).click();expect((await(await page.request.get(base+"/authoring")).json()).revision.id).toBe(analyzed.id);expect(await calls(page)).toEqual(after);
 const answerBeforeRubric=structuredClone(analyzed.snapshot.answers),treeBeforeRubric=structuredClone(analyzed.snapshot.nodes);
 await select.selectOption(files.find(m=>m.material_type==="rubric_source")!.id);await controls.getByRole("button",{name:"解析",exact:true}).click();const rubricDialog=page.getByRole("dialog");await expect(rubricDialog).toContainText("採点基準の解析結果だけを更新します");await expect(rubricDialog).toContainText("問題文・小問構成・模範解答は変更しません");await rubricDialog.getByRole("button",{name:"キャンセル",exact:true}).click();await confirmAnalysis(page,controls,"解析");await expect(page.locator(".authoring-toast").filter({hasText:"採点基準を解析しました"})).toBeVisible();await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();expect((await(await page.request.get(base+"/authoring")).json()).revision.snapshot.domains.answer.material_id).toBe(files.find(m=>m.material_type==="rubric_source")!.id);
 const rubricAnalyzed=(await(await page.request.get(base+"/authoring")).json()).revision;expect(rubricAnalyzed.snapshot.answers).toEqual(answerBeforeRubric);expect(rubricAnalyzed.snapshot.nodes).toEqual(treeBeforeRubric);
 await select.selectOption(files.find(m=>m.material_type==="model_answer_source")!.id);await confirmAnalysis(page,controls,"再解析");await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();const answerReanalyzed=(await(await page.request.get(base+"/authoring")).json()).revision;expect(answerReanalyzed.snapshot.rubrics).toEqual(rubricAnalyzed.snapshot.rubrics);
 await select.selectOption(files.find(m=>m.material_type==="rubric_source")!.id);await confirmAnalysis(page,controls,"再解析");await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();expect((await(await page.request.get(base+"/authoring")).json()).revision.snapshot.answers).toEqual(answerReanalyzed.snapshot.answers);
 await select.selectOption(files.find(m=>m.material_type==="model_answer_source")!.id);await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();await page.reload();await select.selectOption(files.find(m=>m.material_type==="model_answer_source")!.id);await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();
 const beforeQuestionAnalysis=(await(await page.request.get(base+"/authoring")).json()).revision;
 await select.selectOption(files.find(m=>m.material_type==="question_sheet")!.id);await controls.getByRole("button",{name:"解析",exact:true}).click();const questionSheetDialog=page.getByRole("dialog");await expect(questionSheetDialog).toContainText("問題文・小問構成など問題用紙から作成した内容が");await expect(questionSheetDialog).toContainText("模範解答・採点基準の編集内容は保持されます");await questionSheetDialog.getByRole("button",{name:"キャンセル",exact:true}).click();await confirmAnalysis(page,controls,"解析");await expect(page.locator(".authoring-toast").filter({hasText:"問題用紙の解析が完了しました"})).toBeVisible();await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();expect(observed.some(url=>url.includes("question-materials"))).toBe(true);
 const questionAnalyzed=(await(await page.request.get(base+"/authoring")).json()).revision;
 expect(questionAnalyzed.snapshot.domains.question.document.source_pdf_sha256).toBeTruthy();
 const entryContent=(entries:Record<string,unknown>[])=>entries.map(entry=>{const copy=structuredClone(entry);delete copy.authoring_question_key;delete copy.disposition;delete copy.mapping_state;return copy;});
 expect(entryContent(questionAnalyzed.snapshot.domains.answer.entries)).toEqual(entryContent(beforeQuestionAnalysis.snapshot.domains.answer.entries));
 expect(questionAnalyzed.snapshot.domains.answer.material_id).toBe(beforeQuestionAnalysis.snapshot.domains.answer.material_id);
 expect(questionAnalyzed.snapshot.domains.answer.sources).toEqual(beforeQuestionAnalysis.snapshot.domains.answer.sources);
 expect(questionAnalyzed.snapshot.source_provenance.authoring_origins.tokens.answer).toEqual(beforeQuestionAnalysis.snapshot.source_provenance.authoring_origins.tokens.answer);
 for(const key of Object.keys(questionAnalyzed.snapshot.answers))if(key in beforeQuestionAnalysis.snapshot.answers)expect(questionAnalyzed.snapshot.answers[key]).toEqual(beforeQuestionAnalysis.snapshot.answers[key]);
 for(const key of Object.keys(questionAnalyzed.snapshot.rubrics))if(key in beforeQuestionAnalysis.snapshot.rubrics)expect(questionAnalyzed.snapshot.rubrics[key]).toEqual(beforeQuestionAnalysis.snapshot.rubrics[key]);
 await page.getByRole("button",{name:"最終確認へ",exact:true}).click();const review=(await(await page.request.get(base+"/authoring/review")).json()).issues as {question_key:string|null;section:string;message:string;field?:string}[];
 const issueControl=page.getByRole("button",{name:`要修正事項、未解決${review.length}件`,exact:true});await expect(issueControl).toBeVisible();await issueControl.click();const issuePanel=page.getByRole("region",{name:"要修正事項"});await expect(issuePanel).toBeVisible();await expect(issuePanel).toContainText(`要修正事項 ${review.length}件`);await expect(issuePanel.locator("li")).toHaveCount(review.length);
 const navigableIndex=review.findIndex(issue=>issue.question_key||issue.section==="answer");if(navigableIndex>=0){await issuePanel.locator("li button").nth(navigableIndex).click();await expect(page.getByLabel("対象設問",{exact:true})).toHaveValue(review[navigableIndex].question_key||"unassigned");await expect(issuePanel).toHaveCount(0);}
 // Replacing one binding must not move the other role off the shared source.
 const beforeReplacement=(await(await page.request.get(base+"/authoring")).json()).revision,oldAnswer=files.find(m=>m.material_type==="model_answer_source")!,oldRubric=files.find(m=>m.material_type==="rubric_source")!,replacementCalls=await calls(page);
 await select.selectOption(oldAnswer.id);await controls.getByRole("button",{name:"差換え",exact:true}).click();page.once("dialog",dialog=>dialog.accept());await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:"answer-v2.pdf",mimeType:"application/pdf",buffer:Buffer.concat([bytes,Buffer.from("\n% replacement\n")])});await expect(select).toContainText("模範解答 — answer-v2.pdf");await expect(select).toContainText("採点基準 — model_answer_source.pdf");expect(await calls(page)).toEqual(replacementCalls);
 await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);const replaced=(await(await page.request.get(base+"/authoring")).json()).revision;expect(replaced.snapshot.rubrics).toEqual(beforeReplacement.snapshot.rubrics);expect(replaced.snapshot.materials.find((m:{id:string})=>m.id===oldRubric.id)).toEqual(beforeReplacement.snapshot.materials.find((m:{id:string})=>m.id===oldRubric.id));expect(replaced.snapshot.materials.some((m:{replaces_material_id?:string})=>m.replaces_material_id===oldAnswer.id)).toBe(true);expect((await page.request.get(base+`/materials/${oldRubric.id}/file`)).status()).toBe(200);
 // Persist a classifier-uncertain extracted segment to exercise the real
 // teacher recovery UI/API contract without inventing production criteria.
 const recoveryBefore=(await(await page.request.get(base+"/authoring")).json()).revision;
 const recoveryKey=recoveryBefore.snapshot.nodes.find((n:{stable_key:string;included:boolean})=>n.included&&!recoveryBefore.snapshot.nodes.some((c:{parent_key:string;included:boolean})=>c.included&&c.parent_key===n.stable_key))?.stable_key;
 expect(recoveryKey).toBeTruthy();const uuid=`00000000-0000-4000-8000-${Date.now().toString(16).padStart(12,"0")}`,recoveryId=`teacher-entry-${uuid}`,segmentId=`segment-${Date.now()}`;
 const answerSource=Object.entries({[recoveryBefore.snapshot.domains.answer.draft_id]:recoveryBefore.snapshot.domains.answer,...(recoveryBefore.snapshot.domains.answer.sources||{})} as Record<string,{material_id:string}>).find(([,source])=>source.material_id===oldRubric.id);expect(answerSource).toBeTruthy();
 const recoveryEntry={id:recoveryId,source_draft_id:answerSource![0],question_id:null,authoring_question_key:null,disposition:"unassigned",mapping_state:"needs_review",answer_kind:"alternative",answer_text:"",source:{kind:"teacher_manual",material_id:null,source_sha256:null,segments:[]},semantic_classification:{status:"needs_teacher_review",candidate_text:"配点と根拠を説明する",segments:[{id:segmentId,text:"配点と根拠を説明する",category:"uncertain",confidence:0.4}],rubric_groups:[]}};
 const recoverySnapshot=structuredClone(recoveryBefore.snapshot);recoverySnapshot.domains.answer.entries.push(recoveryEntry);
 const seeded=await page.request.put(base+"/authoring",{data:{expected_edit_version:recoveryBefore.edit_version,snapshot:recoverySnapshot}});expect(seeded.status(),await seeded.text()).toBe(200);
 const callsBeforeRecovery=await calls(page);await page.reload();await page.getByLabel("対象設問",{exact:true}).selectOption("unassigned");
 const recoveryCard=page.locator(`#authoring-candidate-${recoveryId}`),answerSection=recoveryCard.getByRole("region",{name:"模範解答候補",exact:true}),rubricSection=recoveryCard.getByRole("region",{name:"採点基準候補",exact:true});
 await answerSection.getByRole("button",{name:"本文編集",exact:true}).click();await answerSection.getByLabel("対応する設問",{exact:true}).selectOption(recoveryKey!);await page.getByLabel("対象設問",{exact:true}).selectOption(recoveryKey!);
 await rubricSection.getByRole("button",{name:"編集する",exact:true}).click();const recoverButton=rubricSection.getByRole("button",{name:"採点基準として追加",exact:true});await expect(rubricSection.getByRole("region",{name:"未登録の採点基準候補",exact:true})).toContainText("配点と根拠を説明する");await recoverButton.click();
 await rubricSection.getByLabel("基準1の配点",{exact:true}).fill("5");await rubricSection.getByRole("button",{name:"この採点基準を確認",exact:true}).click();await saveAuthoring(page);
 const recovered=(await(await page.request.get(base+"/authoring")).json()).revision.snapshot.domains.answer.entries.find((e:{id:string})=>e.id===recoveryId);expect(recovered.authoring_question_key).toBe(recoveryKey);expect(recovered.rubric_edits[0]).toMatchObject({description:"配点と根拠を説明する",points:5,segment_ids:[segmentId],grouping_confirmed:true});expect(recovered.rubric_edits[0].provenance.source_candidate_segment_id).toBe(segmentId);expect(await calls(page)).toEqual(callsBeforeRecovery);
 for(const domain of ["questions","model-answers","rubrics"])expect(await(await page.request.get(base+`/${domain}`)).json()).toEqual([]);
 await page.setViewportSize({width:760,height:900});const narrow=(await controls.boundingBox())!;expect(narrow.height).toBeLessThan(90);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole("link",{name:"戻る",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${exams[1].id}$`));await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${exams[1].id}/authoring$`));
 const offering=await(await page.request.get(`/api/v1/offerings/${seed.course_offering_id}`)).json();await page.goto("/");const card=page.locator(".recent-course-card").filter({has:page.locator(`a[href='/courses/${offering.course_id}']`)});await expect(card.getByLabel("最近のテスト").getByRole("link")).toHaveCount(1);expect(errors).toEqual([]);
});

test("fresh Sample Q5 source bindings stay isolated in Question→Answer→Rubric and Question→Rubric→Answer orders",async({page})=>{
 await page.setViewportSize({width:1600,height:1000});await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json(),questionPdf=await readFile("../testData/SampleQ/sampleQ5.pdf"),sharedPdf=await readFile("../testData/SampleQ/modelAnswer/sampleQ5_modelAnswer.pdf"),run=`${Date.now()}`;
 for(const [fixtureIndex,roleOrder] of [[0,["model_answer_source","rubric_source"]],[1,["rubric_source","model_answer_source"]]] as const){
  const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:`Fresh Sample Q5 ${fixtureIndex} ${run}`,total_points:100}});expect(created.status()).toBe(201);const testId=(await created.json()).id,base=`/api/v1/tests/${testId}`;
  const q=await page.request.post(`${base}/materials/upload`,{data:questionPdf,headers:{"Content-Type":"application/pdf","X-Source-Role":"question_sheet","X-Filename":"sampleQ5.pdf"}});expect(q.status()).toBe(201);const questionMaterial=await q.json();
  const a=await page.request.post(`${base}/materials/upload`,{data:sharedPdf,headers:{"Content-Type":"application/pdf","X-Source-Role":"model_answer_source","X-Filename":"sampleQ5_modelAnswer.pdf"}});expect(a.status()).toBe(201);const answerMaterial=await a.json();
  const r=await page.request.post(`${base}/materials/${answerMaterial.id}/reuse`,{data:{material_type:"rubric_source"}});expect(r.status()).toBe(201);const rubricMaterial=await r.json();expect(rubricMaterial.id).not.toBe(answerMaterial.id);expect(rubricMaterial.sha256).toBe(answerMaterial.sha256);expect(rubricMaterial.storage_ref).toBe(answerMaterial.storage_ref);
  await page.goto(`/tests/${testId}/authoring`);const controls=page.getByRole("group",{name:"利用資料の操作",exact:true}),select=page.getByLabel("利用資料",{exact:true});await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();
  async function analyze(material:{id:string;material_type:string},label:string){await select.selectOption(material.id);await controls.getByRole("button",{name:"解析",exact:true}).click();const dialog=page.getByRole("dialog");await expect(dialog).toBeVisible();await expect(dialog).toContainText(label);const endpoint=material.material_type==="question_sheet"?"/authoring/source-import":"/authoring/analyze-answer",resultRequest=page.waitForResponse(response=>response.request().method()==="POST"&&response.url().endsWith(endpoint));await dialog.getByRole("button",{name:"解析",exact:true}).click();await expect(page.getByRole("status").filter({hasText:`${label}を解析しています…`})).toBeVisible();await expect(page.locator(".authoring-toast").filter({hasText:label})).toBeVisible();const resultResponse=await resultRequest;expect(resultResponse.status()).toBe(200);const resultBody=await resultResponse.json();if(material.material_type!=="question_sheet")expect(resultBody.snapshot.domains?.answer,`Analysis response omitted answer domain for ${label}: ${JSON.stringify({revision:resultBody.revision,domains:Object.keys(resultBody.snapshot.domains||{})})}`).toBeTruthy();return (await(await page.request.get(`${base}/authoring`)).json()).revision;}
  let revision=await analyze(questionMaterial,"問題");expect(revision.snapshot.nodes.length).toBeGreaterThanOrEqual(3);let tree=structuredClone(revision.snapshot.nodes);
  const first=revision.snapshot.nodes.find((n:{included:boolean})=>n.included);expect(first).toBeTruthy();await page.getByLabel("対象設問",{exact:true}).selectOption(first.stable_key);await page.locator("#authoring-question").getByRole("button",{name:"本文編集",exact:true}).click();const body=page.getByLabel("問題文",{exact:true}),teacherText=`${first.body_text}\n夜間監査の教師編集 ${fixtureIndex}`;await body.fill(teacherText);await saveAuthoring(page);revision=(await(await page.request.get(`${base}/authoring`)).json()).revision;expect(revision.snapshot.nodes.find((n:{stable_key:string})=>n.stable_key===first.stable_key).body_text).toBe(teacherText);tree=structuredClone(revision.snapshot.nodes);
  let answerRevision:any,rubricRevision:any;
  for(const role of roleOrder){if(role==="model_answer_source"){answerRevision=await analyze(answerMaterial,"模範解答");expect(answerRevision.snapshot.domains?.answer,`Answer analysis omitted its domain in fixture ${fixtureIndex}: ${JSON.stringify(answerRevision.snapshot.domains)}`).toBeTruthy();expect(answerRevision.snapshot.domains.answer.material_id).toBe(answerMaterial.id);expect(answerRevision.snapshot.domains.answer.material_role).toBe("model_answer_source");expect(answerRevision.snapshot.nodes).toEqual(tree);expect(answerRevision.snapshot.nodes.find((n:{stable_key:string})=>n.stable_key===first.stable_key).body_text).toBe(teacherText);}
   else{const beforeAnswer=roleOrder[0]==="model_answer_source"?answerRevision:null;rubricRevision=await analyze(rubricMaterial,"採点基準");expect(rubricRevision.snapshot.domains?.answer,`Rubric analysis omitted its domain in fixture ${fixtureIndex}: ${JSON.stringify(rubricRevision.snapshot.domains)}`).toBeTruthy();expect(rubricRevision.snapshot.domains.answer.material_id).toBe(rubricMaterial.id);expect(rubricRevision.snapshot.domains.answer.material_role).toBe("rubric_source");expect(rubricRevision.snapshot.nodes).toEqual(tree);const rubricOutcome=rubricRevision.snapshot.domains.answer.analysis_result;expect(rubricOutcome.candidate_count,`Q5 shared PDF fixture should be a true zero-candidate Rubric result: ${JSON.stringify(rubricOutcome)}`).toBe(0);await expect(page.getByRole("alert").filter({hasText:"自動抽出できる採点基準候補がありませんでした。設問を選択し、採点基準を手動で追加してください。"})).toBeVisible();if(beforeAnswer){expect(rubricRevision.snapshot.answers,`Rubric analysis changed answer projection; role order ${roleOrder.join("→")}`).toEqual(beforeAnswer.snapshot.answers);const answerSourceId=beforeAnswer.snapshot.domains.answer.draft_id;expect(rubricRevision.snapshot.domains.answer.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===answerSourceId)).toEqual(beforeAnswer.snapshot.domains.answer.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===answerSourceId));}}
  }
  revision=(await(await page.request.get(`${base}/authoring`)).json()).revision;
  const answerDomain=revision.snapshot.domains.answer,sourceInfo=(id:string)=>id===answerDomain.draft_id?answerDomain:answerDomain.sources[id];
  const answerSourceId=answerRevision.snapshot.domains.answer.draft_id,rubricSourceId=rubricRevision.snapshot.domains.answer.draft_id;
  expect(sourceInfo(answerSourceId)).toMatchObject({material_id:answerMaterial.id,source_sha256:answerMaterial.sha256});expect(sourceInfo(rubricSourceId)).toMatchObject({material_id:rubricMaterial.id,source_sha256:rubricMaterial.sha256});
  if(roleOrder[0]==="rubric_source"){expect(revision.snapshot.rubrics).toEqual(rubricRevision.snapshot.rubrics);expect(answerDomain.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===rubricSourceId)).toEqual(rubricRevision.snapshot.domains.answer.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===rubricSourceId));}
  else{expect(revision.snapshot.answers).toEqual(answerRevision.snapshot.answers);expect(answerDomain.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===answerSourceId)).toEqual(answerRevision.snapshot.domains.answer.entries.filter((e:{source_draft_id:string})=>e.source_draft_id===answerSourceId));}
  const boundMaterials=revision.snapshot.materials.filter((m:{id:string})=>[answerMaterial.id,rubricMaterial.id].includes(m.id));expect(boundMaterials).toHaveLength(2);expect(boundMaterials[0].sha256).toBe(boundMaterials[1].sha256);await page.reload();expect((await(await page.request.get(`${base}/authoring`)).json()).revision.snapshot).toEqual(revision.snapshot);
  for(const domain of ["questions","model-answers","rubrics"])expect(await(await page.request.get(`${base}/${domain}`)).json()).toEqual([]);
  await page.getByRole("link",{name:"戻る",exact:true}).click();await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${testId}/authoring$`));expect((await(await page.request.get(`${base}/authoring`)).json()).revision.snapshot).toEqual(revision.snapshot);
 }
 expect(errors).toEqual([]);
});
