import {confirmAnalysis} from "./authoringNotifications";
import {test,expect,type Page,type Locator} from "@playwright/test";
test.setTimeout(90000);
test.skip(!process.env.RUNTIME_MANAGER_E2E,"isolated production build/real API required");
async function calls(page:Page){return Promise.all(["ocr","math_ocr","ornith_rubric_draft","grader"].map(async p=>{
  const result=await(await page.request.get(`${process.env.LLM_GRADER_RUNTIME_MANAGER_URL}/runtimes/${p}/logs?tail=1000`)).json();
  return result.lines.filter((s:string)=>s.includes("POST /v1/chat/completions")).length;
}));}
async function exerciseEditor(page:Page,area:Locator,wrapper:Locator){
  await wrapper.getByRole("button",{name:"本文編集",exact:true}).click();
  await area.fill("第1行\n第2行\n第3行");
  await area.evaluate(el=>{const a=el as HTMLTextAreaElement;(window as unknown as {activeAuthoringArea:HTMLTextAreaElement}).activeAuthoringArea=a;a.focus();a.setSelectionRange(3,3);});
  await page.keyboard.press("Delete");await expect(area).toHaveValue("第1行第2行\n第3行");
  expect(await area.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(3);
  await page.keyboard.press("Enter");await expect(area).toHaveValue("第1行\n第2行\n第3行");
  expect(await area.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(4);
  await page.keyboard.type("ABC");await page.keyboard.press("Control+z");await expect(area).toHaveValue("第1行\nAB第2行\n第3行");
  await page.keyboard.press("Control+Shift+z");await expect(area).toHaveValue("第1行\nABC第2行\n第3行");
  const client=await page.context().newCDPSession(page);
  await client.send("Input.imeSetComposition",{text:"にほん",selectionStart:3,selectionEnd:3});
  await client.send("Input.insertText",{text:"日本語"});await client.detach();
  await expect(area).toHaveValue("第1行\nABC日本語第2行\n第3行");
  const beforePaste=await area.inputValue();
  await area.evaluate(el=>{const a=el as HTMLTextAreaElement;a.setSelectionRange(4,7);});
  await page.keyboard.insertText("貼付\n複数行");
  const current=await area.inputValue(),caret=await area.evaluate(el=>(el as HTMLTextAreaElement).selectionStart);
  await wrapper.getByRole("button",{name:"プレビューを見る",exact:true}).click();
  await expect(area).not.toBeVisible();await expect(wrapper.locator(".authoring-current-preview")).toContainText("貼付");
  await wrapper.getByRole("button",{name:"本文編集",exact:true}).click();await expect(area).toHaveValue(current);
  expect(await area.evaluate(el=>el===(window as unknown as {activeAuthoringArea:HTMLTextAreaElement}).activeAuthoringArea)).toBe(true);
  expect(await area.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(caret);
  await page.keyboard.press("Control+z");await expect(area).toHaveValue(beforePaste);await page.keyboard.press("Control+Shift+z");await expect(area).toHaveValue(current);
  expect((await area.boundingBox())!.height).toBeGreaterThanOrEqual(120);expect((await area.boundingBox())!.height).toBeLessThan(200);
  return current;
}
test("current preview and retained editor history; explicit add/replace materials; Back goes to Test",async({page})=>{
  await page.setViewportSize({width:1920,height:1080});await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
  const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
  const exam=await(await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Preview material controls",total_points:10}})).json(),base=`/api/v1/tests/${exam.id}`;
  await page.goto(`/tests/${exam.id}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();await page.getByRole("button",{name:"設問を追加",exact:true}).click();
  const question=page.getByLabel("問題の表示切替",{exact:true}),answer=page.getByLabel("解答の表示切替",{exact:true}),rubric=page.getByLabel("採点基準の表示切替",{exact:true});
  await expect(question.getByRole("button",{name:"本文編集",exact:true})).toBeVisible();await expect(answer.getByRole("button",{name:"本文編集",exact:true})).toBeVisible();await expect(rubric.getByRole("button",{name:"編集する",exact:true})).toBeVisible();
  await expect(page.getByLabel("問題文",{exact:true})).not.toBeVisible();await expect(page.getByLabel("模範解答本文",{exact:true})).not.toBeVisible();
  await expect(page.getByRole("button",{name:"設問を追加",exact:true})).toHaveCount(1);
  await expect(page.locator(".authoring-target-controls").getByRole("button",{name:"設問を追加",exact:true})).toBeVisible();
  await expect(page.getByLabel("テスト全体確認",{exact:true})).toHaveCount(0);
  await expect(page.locator(".authoring-question-metadata")).toContainText("大問：問題1 ／ 配点：－点（未設定）");
  await expect(page.locator(".authoring-question-preview-frame")).toBeVisible();
  await question.getByRole("button",{name:"設問設定の変更",exact:true}).click();
  await question.locator('input[type="number"]').fill("30");
  await question.getByRole("button",{name:"プレビューに戻る",exact:true}).click();
  await expect(page.locator(".authoring-question-metadata")).toContainText("30点（直接配点）");
  await question.getByRole("button",{name:"設問設定の変更",exact:true}).click();
  await question.locator('input[type="number"]').fill("");
  await question.getByRole("button",{name:"プレビューに戻る",exact:true}).click();
  const before=await(await page.request.get(base+"/authoring")).json(),counts=await calls(page);
  const qtext=await exerciseEditor(page,page.getByLabel("問題文",{exact:true}),question);
  await expect(page.getByLabel("設問の階層",{exact:true})).not.toBeVisible();await expect(page.getByRole("button",{name:"小問の分割案を作成",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"最終確認へ",exact:true}).click();await page.getByRole("button",{name:/問題1.*配点を確認/}).click();await expect.poll(()=>page.evaluate(()=>document.activeElement?.getAttribute("type"))).toBe("number");await expect(page.getByLabel("問題文",{exact:true})).not.toBeVisible();await expect(page.getByLabel("設問の階層",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"小問の分割案を作成",exact:true})).not.toBeVisible();
  await question.getByRole("button",{name:"本文編集",exact:true}).click();await expect(page.getByLabel("問題文",{exact:true})).toHaveValue(qtext);
  const atext=await exerciseEditor(page,page.getByLabel("模範解答本文",{exact:true}),answer);
  await question.getByRole("button",{name:"プレビューを見る",exact:true}).click();await expect(answer.getByRole("button",{name:"プレビューを見る",exact:true})).toBeVisible();
  await rubric.getByRole("button",{name:"編集する",exact:true}).click();await page.getByRole("button",{name:"基準を追加",exact:true}).click();
  await page.getByLabel(/^基準\d+の本文$/).fill("$x^2$ を確認");await page.getByLabel(/^基準\d+の配点$/).fill("5");await page.getByRole("button",{name:"複製",exact:true}).click();
  await page.getByRole("button",{name:"上と結合",exact:true}).nth(1).click();await expect(page.getByLabel(/^基準\d+の本文$/)).toHaveCount(1);
  await rubric.getByRole("button",{name:"プレビューを見る",exact:true}).click();await expect(rubric.locator(".katex").first()).toBeVisible();await expect(rubric.locator(".authoring-current-preview")).toContainText("5点");
  await rubric.getByRole("button",{name:"編集する",exact:true}).click();await page.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(page.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);
  await page.getByRole("checkbox",{name:"解答",exact:true}).uncheck();await page.getByRole("checkbox",{name:"解答",exact:true}).check();await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue(atext);
  expect((await(await page.request.get(base+"/authoring")).json()).revision).toEqual(before.revision);expect(await calls(page)).toEqual(counts);
  const bytes=await(await page.request.get(`/api/v1/tests/${seed.id}/materials/${process.env.MODEL_ANSWER_CLASSIFICATION_MATERIAL_ID}/file`)).body();
  await page.getByLabel("利用資料",{exact:true}).selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption("model_answer_source");
  await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:"answer.pdf",mimeType:"application/pdf",buffer:bytes});await expect(page.getByLabel("利用資料",{exact:true})).toContainText("模範解答 — answer.pdf");
  const source=page.locator(".review-workspace-source"),right=page.locator(".review-workspace-editor"),selector=page.getByLabel("利用資料",{exact:true});
  const target=await page.getByLabel("対象設問",{exact:true}).inputValue();await selector.selectOption("action:manage");await expect(source.getByLabel("資料管理",{exact:true})).toBeVisible();await expect(right.getByLabel("資料管理",{exact:true})).toHaveCount(0);await expect(source.locator(".pdf-pane-viewport")).toHaveCount(0);await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue(atext);await expect(page.getByLabel("対象設問",{exact:true})).toHaveValue(target);
  const uploaded=(await(await page.request.get(base+"/materials")).json())[0];await selector.selectOption(uploaded.id);await expect(source.locator(".pdf-pane-viewport")).toBeVisible();
  const old=await page.getByLabel("利用資料",{exact:true}).inputValue();await page.getByRole("group",{name:"利用資料の操作"}).getByRole("button",{name:"差換え",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"差し替え対象"})).toContainText("再確認が必要");
  const changed={name:"replacement.pdf",mimeType:"application/pdf",buffer:Buffer.concat([bytes,Buffer.from("\n% replacement source\n")])};
  page.once("dialog",d=>d.dismiss());await page.getByLabel("資料を追加",{exact:true}).setInputFiles(changed);await expect(page.getByLabel("資料を追加",{exact:true})).toHaveValue("");await expect(page.getByLabel("利用資料",{exact:true})).toHaveValue("action:add");
  page.once("dialog",d=>d.accept());await page.getByLabel("資料を追加",{exact:true}).setInputFiles(changed);
  await expect(page.getByRole("status").filter({hasText:"資料を差し替えました"})).toBeVisible();await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue(atext);
  await expect(page.getByText("未保存の変更があります",{exact:true})).toBeVisible();expect(await calls(page)).toEqual(counts);
  await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();
  const saved=(await(await page.request.get(base+"/authoring")).json()).revision,replacementRef=saved.snapshot.materials.find((m:{id:string;replaces_material_id?:string})=>m.replaces_material_id===old);expect(replacementRef).toBeTruthy();
  await page.reload();await expect(page.getByLabel("問題プレビュー",{exact:true})).toContainText("貼付");await expect(page.getByLabel("解答プレビュー",{exact:true})).toContainText("日本語");await expect(page.getByLabel("模範解答本文",{exact:true})).not.toBeVisible();
  await question.getByRole("button",{name:"本文編集",exact:true}).click();await expect(page.getByLabel("問題文",{exact:true})).toHaveValue(qtext);await answer.getByRole("button",{name:"本文編集",exact:true}).click();await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue(atext);
  await selector.selectOption(replacementRef!.id);const materialActions=page.getByRole("group",{name:"利用資料の操作"});await expect(materialActions.getByRole("button",{name:"解析",exact:true})).toBeEnabled();
  await confirmAnalysis(page,materialActions,"解析");await expect(materialActions.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();
  const analyzed=(await(await page.request.get(base+"/authoring")).json()).revision;expect(analyzed.snapshot.nodes).toEqual(saved.snapshot.nodes);expect(analyzed.snapshot.domains.answer.material_id).toBe(replacementRef!.id);
  const analyzedCalls=await calls(page);expect(analyzedCalls[2]).toBeGreaterThan(counts[2]);await page.getByRole("link",{name:"戻る",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${exam.id}$`));expect(await calls(page)).toEqual(analyzedCalls);expect(errors).toEqual([]);
});

test("Question and whole-Test views stay separate; canonical score metadata and top Add",async({page})=>{
  await page.setViewportSize({width:1920,height:1080});await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
  const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
  const exam=await(await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Question preview metadata",total_points:70}})).json(),base=`/api/v1/tests/${exam.id}`;
  await page.goto(`/tests/${exam.id}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).first().click();
  await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
  const saved=await(await page.request.get(base+"/authoring")).json(),template=saved.revision.snapshot.nodes[0];
  const make=(key:string,label:string,parent:string|null,points:number|null,semantics:string,order:number)=>({...template,stable_key:key,review_node_id:key,parent_key:parent,depth:parent?1:0,node_type:parent?"subquestion":"major_question",label:{raw:label,normalized:label},sort_order:order,score_points:points,score_semantics:semantics,body_text:"$x^2$ の問題",ordered_content:[{type:"text",order:0,text:"$x^2$ の問題"}]});
  const snapshot={...saved.revision.snapshot,nodes:[make("direct","問題1",null,30,"direct",0),make("parent","問題2",null,null,"sum_children",1),make("child1","(1)","parent",20,"direct",0),make("child2","(2)","parent",20,"direct",1),make("unset","問題3",null,null,"unset",2)]};
  const result=await page.request.put(base+"/authoring",{data:{snapshot:{...snapshot,question_text_buffers:Object.fromEntries(snapshot.nodes.map((n:{stable_key:string;body_text:string})=>[n.stable_key,n.body_text]))},expected_edit_version:saved.revision.edit_version}});expect(result.ok()).toBe(true);
  await page.reload();const selector=page.getByLabel("対象設問",{exact:true}),metadata=page.locator(".authoring-question-metadata"),controls=page.locator(".authoring-target-controls");
  const countBefore=await calls(page);
  await selector.selectOption("direct");await expect(metadata).toContainText("大問：問題1 ／ 配点：30点（直接配点）");await expect(page.locator(".authoring-question-preview-frame .katex")).toBeVisible();
  await selector.selectOption("parent");await expect(metadata).toContainText("40点（小問合計）");
  await selector.selectOption("child1");await expect(metadata).toContainText("小問：問題2 > (1)");
  await selector.selectOption("unset");await expect(metadata).toContainText("－点（未設定）");
  await expect(page.getByLabel("テスト全体確認",{exact:true})).toHaveCount(0);
  await selector.selectOption("all");await expect(page.getByLabel("テスト全体確認",{exact:true})).toBeVisible();await expect(metadata).toHaveCount(0);await expect(page.getByLabel("問題の表示切替",{exact:true})).toHaveCount(0);
  await expect(page.getByRole("button",{name:"設問を追加",exact:true})).toHaveCount(1);
  await controls.getByRole("button",{name:"設問を追加",exact:true}).click();await expect(selector).not.toHaveValue("all");await expect(page.getByText("未保存の変更があります",{exact:true})).toBeVisible();
  await selector.selectOption("direct");await controls.getByRole("button",{name:"設問を追加",exact:true}).click();await expect(metadata).toBeVisible();
  await page.setViewportSize({width:760,height:900});await expect(controls.getByRole("button",{name:"設問を追加",exact:true})).toBeVisible();
  expect(await calls(page)).toEqual(countBefore);expect(await(await page.request.get(base+"/questions")).json()).toEqual([]);
});
