import {openAuthoringEditors} from "./authoringEditMode";
import {test,expect} from "@playwright/test";
import {readFile} from "node:fs/promises";
test.setTimeout(90000);
test.skip(!process.env.AUTHORING_SOURCE_TEST_ID,"isolated source-backed authoring fixture required");
test("saved source reviews integrate Question, answer diagrams and advanced Rubric without publishing",async({page})=>{
  await page.setViewportSize({width:1920,height:1080});
  await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();
  await expect(page).not.toHaveURL(/login/);
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
  const tid=process.env.AUTHORING_SOURCE_TEST_ID!,base=`/api/v1/tests/${tid}`;
  const formal=await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>(await page.request.get(base+`/${suffix}`)).json()));
  const upload=await page.request.post(base+"/question-materials",{headers:{"content-type":"application/pdf","x-filename":"authoring-question.pdf"},data:await readFile(process.env.DIAGRAM_PDF_PATH!)});
  expect(upload.status()).toBe(201);
  const draft=await (await page.request.post(`/api/v1/question-imports/${(await upload.json()).id}/draft`)).json();
  const review=await (await page.request.post(`/api/v1/question-import-drafts/${draft.id}/reviews`)).json();
  const answerResult=await page.request.post(base+"/model-answer-imports",{data:{material_id:process.env.AUTHORING_SOURCE_MATERIAL_ID}});
  expect(answerResult.status()).toBe(201);const answer=await answerResult.json();
  await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();
  await page.getByLabel("問題文",{exact:true}).waitFor({state:"attached"});await openAuthoringEditors(page);const editor=page.getByLabel("問題文",{exact:true});await expect(editor).toContainText("図の範囲");
  const authoring=await(await page.request.get(base+"/authoring")).json();
  const warnings=authoring.revision.snapshot.domains.question.document.warnings;
  const selectedKey=await page.getByLabel("対象設問",{exact:true}).inputValue();
  const selectedNode=authoring.revision.snapshot.nodes.find((n:{stable_key:string})=>n.stable_key===selectedKey);
  const expectedWarnings=warnings.filter((w:{owner:string|null;source_id:string})=>{const region=authoring.revision.snapshot.domains.question.document.regions.find((r:{region_id:string})=>r.region_id===w.source_id);const owner=w.owner||region?.assigned_question_key||w.source_id;return owner===selectedKey||owner===selectedNode.source_draft_stable_key;});
  const panel=page.getByLabel("問題",{exact:true}).getByLabel("確認事項一覧",{exact:true});
  if(expectedWarnings.length)await expect(panel.locator("fieldset")).toHaveCount(expectedWarnings.length);else await expect(panel).toHaveCount(0);
  const initial=await editor.inputValue();
  await editor.fill("第1行\n第2行\n第3行");
  await editor.evaluate(el=>{const t=el as HTMLTextAreaElement;(window as unknown as {activeAuthoringEditor:Element}).activeAuthoringEditor=t;t.focus();t.setSelectionRange(3,3);});
  await editor.press("Delete");await expect(editor).toHaveValue("第1行第2行\n第3行");
  expect(await editor.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(3);
  await editor.press("Enter");expect(await editor.evaluate(el=>(el as HTMLTextAreaElement).selectionStart)).toBe(4);
  expect(await editor.evaluate(el=>el===(window as unknown as {activeAuthoringEditor:Element}).activeAuthoringEditor)).toBe(true);
  await editor.dispatchEvent("compositionstart",{data:""});await editor.dispatchEvent("compositionupdate",{data:"日本語"});await editor.dispatchEvent("compositionend",{data:"日本語"});
  expect(await editor.evaluate(el=>el===(window as unknown as {activeAuthoringEditor:Element}).activeAuthoringEditor)).toBe(true);
  await editor.fill(initial+"\n教師が編集した問題文");
  const selector=page.getByLabel("対象設問",{exact:true});await selector.selectOption("q2");await selector.selectOption("q1");await expect(editor).toHaveValue(initial+"\n教師が編集した問題文");
  const problemDiagram=page.getByRole("region",{name:"図の確認",exact:true});await problemDiagram.getByRole("button",{name:"図候補を確認",exact:true}).click();
  await expect(problemDiagram.getByAltText("図1の切り出し範囲")).toBeVisible();await expect(page.locator(".diagram-overlay")).toBeVisible();
  await problemDiagram.getByRole("button",{name:"この図を使用",exact:true}).click();await expect(problemDiagram.getByText("使用中",{exact:true})).toBeVisible();
  await page.getByLabel("利用資料",{exact:true}).selectOption(process.env.AUTHORING_SOURCE_MATERIAL_ID!);await expect(editor).toHaveValue(initial+"\n教師が編集した問題文");
  await page.getByLabel("候補の扱い").first().selectOption("ignored");await page.getByRole("button",{name:"模範解答を追加",exact:true}).click();await page.locator('[id^="authoring-candidate-teacher-entry-"]').first().waitFor();await openAuthoringEditors(page);
  const manual=page.locator('[id^="authoring-candidate-teacher-entry-"]');await expect(manual.getByLabel("模範解答本文",{exact:true})).toHaveValue("");
  const diagrams=manual.getByRole("region",{name:"模範解答の図",exact:true});await diagrams.getByRole("button",{name:"図候補を確認",exact:true}).click();
  await expect(diagrams.getByAltText("図1の切り出し範囲")).toBeVisible();await diagrams.getByRole("button",{name:"この図を使用",exact:true}).click();await expect(diagrams.getByText("使用中",{exact:true})).toBeVisible();
  await manual.getByRole("button",{name:"基準を追加",exact:true}).click();const criterion=manual.getByLabel(/^基準\d+の本文$/);await criterion.fill("first condition\nsecond condition");
  await criterion.evaluate(el=>{const textarea=el as HTMLTextAreaElement;textarea.focus();textarea.setSelectionRange(16,16);});
  await criterion.press("ArrowRight");await criterion.press("ArrowLeft");
  await manual.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await page.getByRole("button",{name:"この分割を適用",exact:true}).click();
  await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);await manual.getByLabel(/^基準\d+の配点$/).nth(0).fill("5");await manual.getByLabel(/^基準\d+の配点$/).nth(1).fill("5");
  await manual.getByRole("button",{name:"複製",exact:true}).nth(1).click();await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);
  await manual.getByRole("button",{name:"上と結合",exact:true}).nth(2).click();await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);
  await manual.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);
  await manual.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);
  await manual.getByRole("button",{name:"採点基準の統合案を作成",exact:true}).click();
  await expect(page.getByRole("region",{name:"採点基準の統合案",exact:true})).toBeVisible();
  await page.getByRole("button",{name:"この統合を適用",exact:true}).click();await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);
  await manual.getByRole("button",{name:"別解を追加",exact:true}).click();await manual.getByLabel("別解1",{exact:true}).fill("教師が入力した別解");
  await page.getByRole("checkbox",{name:"解答",exact:true}).uncheck();await page.getByRole("checkbox",{name:"解答",exact:true}).check();await expect(diagrams.getByText("使用中",{exact:true})).toBeVisible();
  const beforeReview=await (await page.request.get(base+"/authoring")).json();
  await page.getByRole("button",{name:"最終確認へ",exact:true}).click();
  await page.getByRole("button",{name:/問題4.*採点基準の配点合計/}).click();await expect(selector).toHaveValue("q2");
  await expect.poll(()=>page.evaluate(()=>!!document.activeElement?.closest('[aria-label="採点基準候補"]'))).toBe(true);
  expect((await (await page.request.get(base+"/authoring")).json()).revision.edit_version).toBe(beforeReview.revision.edit_version);
  await selector.selectOption("q1");await expect(editor).toHaveValue(initial+"\n教師が編集した問題文");
  await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();
  const saved=await (await page.request.get(base+"/authoring")).json();expect(saved.revision.state).toBe("draft");
  await page.reload();await openAuthoringEditors(page);await expect(editor).toHaveValue(initial+"\n教師が編集した問題文");await expect(manual.getByLabel("模範解答本文",{exact:true})).toHaveValue("");await expect(manual.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);await expect(manual.getByLabel("別解1",{exact:true})).toHaveValue("教師が入力した別解");
  await expect(diagrams.getByText("使用中",{exact:true})).toBeVisible();
  expect(await (await page.request.get(`/api/v1/question-import-reviews/${review.id}`)).json()).toEqual(review);
  expect(await (await page.request.get(`/api/v1/model-answer-import-drafts/${answer.id}`)).json()).toEqual(answer);
  expect(await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>(await page.request.get(base+`/${suffix}`)).json()))).toEqual(formal);
  const externalEntries=answer.entries.map((e:Record<string,unknown>,index:number)=>({id:e.id,question_id:e.question_id,disposition:e.disposition||"include",answer_kind:e.answer_kind||"primary",answer_text:index===0?String(e.answer_text)+" 外部レビューの更新":e.answer_text}));
  const external=await page.request.put(`/api/v1/model-answer-import-drafts/${answer.id}`,{data:{expected_revision:answer.revision,entries:externalEntries}});expect(external.status()).toBe(200);
  await page.reload();await openAuthoringEditors(page);await expect(page.getByText("外部の保存済みレビューが更新されています。統合下書きは上書きされていません。",{exact:true})).toBeVisible();
  await expect(editor).toHaveValue(initial+"\n教師が編集した問題文");await expect(diagrams.getByText("使用中",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"現在の下書きを継続",exact:true}).click();
  await editor.fill(initial+"\n教師が編集した問題文\n外部変更後も統合下書きを維持");
  await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();
  const kept=await (await page.request.get(base+"/authoring")).json();
  expect(kept.external_source_change).toBe(false);
  await page.getByRole("link",{name:"戻る",exact:true}).click();
  await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();
  await openAuthoringEditors(page);
  await expect(editor).toHaveValue(initial+"\n教師が編集した問題文\n外部変更後も統合下書きを維持");
  const resumed=await (await page.request.get(base+"/authoring")).json();
  expect(resumed.revision).toEqual(kept.revision);
  expect(resumed.external_source_change).toBe(false);
  const treeBeforeImport=resumed.revision.snapshot.nodes,sourceBeforeImport=await(await page.request.get(`/api/v1/model-answer-import-drafts/${answer.id}`)).json();
  const importEntries=sourceBeforeImport.entries.map((entry:Record<string,unknown>,index:number)=>({id:entry.id,question_id:entry.question_id,disposition:entry.disposition||"include",answer_kind:entry.answer_kind||"primary",answer_text:index===0?String(entry.answer_text)+" 明示取込":String(entry.answer_text)}));
  const externalImport=await page.request.put(`/api/v1/model-answer-import-drafts/${answer.id}`,{data:{expected_revision:sourceBeforeImport.revision,entries:importEntries}});expect(externalImport.status(),await externalImport.text()).toBe(200);
  page.once("dialog",dialog=>dialog.accept());await page.getByRole("button",{name:"保存済みレビューを取り込む",exact:true}).click();
  await expect(page.locator(".authoring-toast").filter({hasText:"保存済みレビューを取り込みました"}).filter({hasText:"設問本文・分割・階層は保持されています"})).toBeVisible();
  const explicitlyImported=await(await page.request.get(base+"/authoring")).json();expect(explicitlyImported.revision.snapshot.nodes).toEqual(treeBeforeImport);
  expect(explicitlyImported.revision.snapshot.question_text_buffers["q1"]).toContain("外部変更後も統合下書きを維持");
  expect(explicitlyImported.revision.snapshot.domains.answer.entries.some((entry:{answer_text:string})=>entry.answer_text.includes("明示取込"))).toBe(true);
  expect(await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>(await page.request.get(base+`/${suffix}`)).json()))).toEqual(formal);
  const answerToggle=page.getByRole("checkbox",{name:"解答",exact:true}),rubricToggle=page.getByRole("checkbox",{name:"採点基準",exact:true});await answerToggle.check();await rubricToggle.check();
  const addAnswer=page.getByRole("button",{name:"模範解答を追加",exact:true});await expect(addAnswer).toBeVisible();expect(await addAnswer.evaluate(el=>el.closest("section")?.getAttribute("aria-label"))).toBe("模範解答候補");await expect(page.getByRole("region",{name:"採点基準候補",exact:true}).getByRole("button",{name:"模範解答を追加",exact:true})).toHaveCount(0);
  await answerToggle.uncheck();await expect(addAnswer).toHaveCount(0);await expect(page.getByRole("region",{name:"採点基準候補",exact:true}).first()).toBeVisible();await answerToggle.check();await rubricToggle.uncheck();await expect(addAnswer).toBeVisible();await expect(page.getByRole("region",{name:"採点基準候補",exact:true})).toHaveCount(0);await answerToggle.uncheck();await expect(addAnswer).toHaveCount(0);await rubricToggle.check();await answerToggle.check();
  expect(errors).toEqual([]);
});
