import {openAuthoringEditors} from "./authoringEditMode";
import {test,expect} from "@playwright/test";
import {readFile} from "node:fs/promises";
test.setTimeout(90000);
test.skip(!process.env.QUESTION_MATH_TEST_ID,"managed authoring math fixture required");
test("unified Question math OCR applies locally, remains editable and saves without publishing",async({page})=>{
  await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
  const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
  const tid=process.env.QUESTION_MATH_TEST_ID!,base=`/api/v1/tests/${tid}/authoring`;
  const extraction=await (await page.request.post(`/api/v1/tests/${tid}/question-materials`,{headers:{"content-type":"application/pdf","x-filename":"authoring-math.pdf"},data:await readFile(process.env.QUESTION_MATH_PDF_PATH!)})).json();const draft=await (await page.request.post(`/api/v1/question-imports/${extraction.id}/draft`)).json();const review=await (await page.request.post(`/api/v1/question-import-drafts/${draft.id}/reviews`)).json();
  await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"編集用の下書きを作成"}).click();await page.getByLabel("問題文",{exact:true}).waitFor({state:"attached"});await openAuthoringEditors(page);const editor=page.getByLabel("問題文",{exact:true}),control=page.locator('[data-content-type="question-content"]').getByRole("region",{name:"LaTeX変換",exact:true});const original=await editor.inputValue();
  await control.getByRole("button",{name:"数式をLaTeX化",exact:true}).click();await expect(control.getByRole("button",{name:"この変換を適用",exact:true})).toBeEnabled();await expect(control.locator(".katex").first()).toBeVisible();await control.getByRole("button",{name:"この変換を適用",exact:true}).click();await expect(editor).toHaveValue(/\\frac\{TP\}\{TP\+FP\}/);const edited=(await editor.inputValue()).replace("Precision=","\\mathrm{Precision}=");await editor.fill(edited);const view=page.getByLabel("問題の表示切替",{exact:true});await view.getByRole("button",{name:"プレビューを見る",exact:true}).click();await expect(view.locator(".authoring-current-preview .katex").first()).toBeVisible();await view.getByRole("button",{name:"編集する",exact:true}).click();await expect(editor).toHaveValue(edited);
  expect((await (await page.request.get(base)).json()).revision.snapshot.nodes[0].math_ocr_edits||[]).toHaveLength(0);expect(await (await page.request.get(`/api/v1/question-import-reviews/${review.id}`)).json()).toEqual(review);
  await page.getByRole("button",{name:"保存",exact:true}).click();await expect(page.getByText("下書きを保存しました。",{exact:true})).toBeVisible();await page.reload();await openAuthoringEditors(page);await expect(editor).toHaveValue(edited);expect(edited).not.toBe(original);const saved=(await (await page.request.get(base)).json()).revision;expect(saved.snapshot.nodes[0].math_ocr_edits).toHaveLength(1);expect(saved.state).toBe("draft");expect(await (await page.request.get(`/api/v1/tests/${tid}/questions`)).json()).toEqual([]);expect(errors).toEqual([]);
});

test("unified answer math OCR retains compact provenance and never changes saved source or formal answers",async({page})=>{
  await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
  const source=await (await page.request.get(`/api/v1/model-answer-import-drafts/${process.env.SOURCE_MATH_DRAFT_ID}`)).json(),tid=source.test_id,base=`/api/v1/tests/${tid}/authoring`;
  const formal=await (await page.request.get(`/api/v1/tests/${tid}/model-answers`)).json();await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"編集用の下書きを作成"}).click();await page.locator(".authoring-preview-editor").first().waitFor();await openAuthoringEditors(page);const candidate=page.locator('[id^="authoring-candidate-"]').first(),editor=candidate.getByLabel("模範解答本文",{exact:true}),control=candidate.getByRole("region",{name:"LaTeX変換",exact:true}).first();
  await control.getByRole("button",{name:"数式をLaTeX化",exact:true}).click();await expect(control.getByRole("button",{name:"この変換を適用",exact:true})).toBeEnabled();await control.getByRole("button",{name:"この変換を適用",exact:true}).click();await expect(editor).toHaveValue(/\\frac\{TP\}\{TP\+FP\}/);const text=await editor.inputValue();const view=candidate.getByLabel("解答の表示切替",{exact:true});await view.getByRole("button",{name:"プレビューを見る",exact:true}).click();await expect(view.locator(".authoring-current-preview .katex").first()).toBeVisible();await view.getByRole("button",{name:"編集する",exact:true}).click();await expect(editor).toHaveValue(text);await page.getByRole("button",{name:"保存",exact:true}).click();await expect(page.getByText("下書きを保存しました。",{exact:true})).toBeVisible();await page.reload();await openAuthoringEditors(page);await expect(editor).toHaveValue(text);
  const saved=(await (await page.request.get(base)).json()).revision.snapshot.domains.answer.entries[0];expect(saved.teacher_correction.latex_normalization.source.entry_id).toBe(source.entries[0].id);expect(JSON.stringify(saved.teacher_correction)).not.toContain("crop_image");expect(await (await page.request.get(`/api/v1/model-answer-import-drafts/${source.id}`)).json()).toEqual(source);expect(await (await page.request.get(`/api/v1/tests/${tid}/model-answers`)).json()).toEqual(formal);
});
