import {canonicalQuestionRoot} from "../lib/canonicalQuestionPath";
import {readFile} from "node:fs/promises";
import {createHash} from "node:crypto";
import {test,expect,type Page} from "@playwright/test";
import {confirmAnalysis,saveAuthoring} from "./authoringNotifications";

test.setTimeout(120000);
test.skip(!process.env.RUNTIME_MANAGER_E2E,"requires disposable real API / RuntimeManager harness");

async function calls(page:Page){return Promise.all(["ocr","math_ocr","ornith_rubric_draft","grader"].map(async profile=>{const data=await(await page.request.get(`${process.env.LLM_GRADER_RUNTIME_MANAGER_URL}/runtimes/${profile}/logs?tail=1000`)).json();return data.lines.filter((line:string)=>line.includes("POST /v1/chat/completions")).length;}));}

for(const productionExclusion of [false,true])test(`real Sample Q5 three-child saved diagram inclusion diagnostics (${productionExclusion?"controlled production exclusion":"native classification"})`,async({page},testInfo)=>{
 await page.setViewportSize({width:1600,height:1000});
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const expectedReviewConflicts:Promise<void>[]=[];page.on("response",response=>{if(response.status()===409&&/\/authoring\/review$/.test(response.url()))expectedReviewConflicts.push(response.json().then(body=>{expect(body.error.message).toBe("AUTHORING_SAVE_CONFLICT");}));});
 const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));page.on("console",message=>{if(message.type()==="error")errors.push(message.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
 const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Sample Q5 three-child inclusion",total_points:100}});expect(created.status()).toBe(201);const tid=(await created.json()).id,base=`/api/v1/tests/${tid}`,authoring=base+"/authoring";
 await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();
 const materialSelect=page.getByLabel("利用資料",{exact:true}),controls=page.getByRole("group",{name:"利用資料の操作",exact:true}),selector=page.getByLabel("対象設問",{exact:true});
 async function add(role:string,file:string){await materialSelect.selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption(role);await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:file.split("/").at(-1)!,mimeType:"application/pdf",buffer:await readFile(file)});await page.getByRole("button",{name:"いいえ",exact:true}).click();await saveAuthoring(page);}
 async function analyze(){const result=page.waitForResponse(r=>r.request().method()==="POST"&&(/\/authoring\/(source-import|analyze-answer)$/.test(r.url())));await confirmAnalysis(page,controls,"解析");const response=await result;expect(response.status(),await response.text()).toBe(200);await expect(page.locator(".authoring-analysis-progress")).toHaveCount(0);}
 await add("question_sheet","../testData/SampleQ/sampleQ5.pdf");await analyze();
 let row=(await(await page.request.get(authoring)).json()).revision;const parent=row.snapshot.nodes.find((n:any)=>/問題\s*[3３]/.test(n.label.raw));expect(parent,JSON.stringify(row.snapshot.nodes.map((n:any)=>n.label))).toBeTruthy();
 await selector.selectOption(parent.stable_key);const question=page.locator("#authoring-question");await question.getByRole("button",{name:"本文編集",exact:true}).click();await question.getByRole("button",{name:"小問の分割案を作成",exact:true}).click();const proposal=page.getByRole("dialog",{name:/の分割案/});await expect(proposal).toBeVisible();const parts=proposal.locator(".authoring-split-block");let children=0;for(let i=0;i<await parts.count();i++){if(await parts.nth(i).getByRole("combobox").inputValue()==="child"){await parts.nth(i).getByLabel("小問名",{exact:true}).fill(`(${++children})`);}}expect(children).toBe(3);await proposal.getByRole("button",{name:"分割を適用",exact:true}).click();await saveAuthoring(page);
 await add("model_answer_source","../testData/SampleQ/modelAnswer/sampleQ5_modelAnswer.pdf");await analyze();
 row=(await(await page.request.get(authoring)).json()).revision;const nodes=row.snapshot.nodes,child=nodes.find((n:any)=>n.parent_key===parent.stable_key&&n.label.raw==="(1)");expect(child).toBeTruthy();

 const childrenNodes=nodes.filter((n:any)=>n.parent_key===parent.stable_key).sort((a:any,b:any)=>a.sort_order-b.sort_order);
 expect(childrenNodes).toHaveLength(3);
 // Native extraction is left unchanged in the first case. The second is an
 // explicit saved-state fixture matching the supplied production evidence.
 if(productionExclusion){const fixture=structuredClone(row.snapshot);for(const entry of fixture.domains.answer.entries){if(childrenNodes.slice(0,2).some((n:any)=>n.stable_key===entry.authoring_question_key)){entry.disposition="excluded";entry.mapping_state="automatic";entry.ignore_reason="classified_as_non_answer";entry.semantic_classification={...entry.semantic_classification,status:"classified"};delete entry.teacher_correction;}}const saved=await page.request.put(authoring,{data:{expected_edit_version:row.edit_version,snapshot:fixture}});expect(saved.status(),await saved.text()).toBe(200);row=await saved.json();await testInfo.attach("controlled-production-pre-accept-state",{body:JSON.stringify(row.snapshot.domains.answer.entries,null,2),contentType:"application/json"});await page.reload();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();}
 const answer=page.locator("#authoring-answer");
 async function editor(index:number){await selector.selectOption(childrenNodes[index].stable_key);const entry=answer.locator('[id^="authoring-candidate-"]').first();await expect(entry).toBeVisible();if(await entry.getByRole("button",{name:"本文編集",exact:true}).count())await entry.getByRole("button",{name:"本文編集",exact:true}).click();return {entry,diagram:entry.getByRole("region",{name:"模範解答の図",exact:true}),id:(await entry.getAttribute("id"))!.replace("authoring-candidate-","")};}
 const first=await editor(0);await first.diagram.getByRole("button",{name:"図候補を確認",exact:true}).click();await expect(first.diagram.getByAltText("図1の切り出し範囲",{exact:true})).toBeVisible();await first.diagram.getByRole("button",{name:/^この図を(確認して)?使用$/}).click();
 async function evidence(stage:string){const saved=(await(await page.request.get(authoring)).json()).revision;const target=await editor(2);const endpoint=`${authoring}/entries/${target.id}/diagrams?question_id=${childrenNodes[2].stable_key}&scope=reuse&reuse_diagnostics=true`;const response=await page.request.get(endpoint);expect(response.status()).toBe(200);const result=await response.json();const hierarchy=saved.snapshot.nodes.map((n:any)=>({key:n.stable_key,parentKey:n.parent_key}));const states=childrenNodes.map((n:any)=>({key:n.stable_key,parent:n.parent_key,root:canonicalQuestionRoot(n.stable_key,hierarchy),entries:saved.snapshot.domains.answer.entries.filter((e:any)=>e.authoring_question_key===n.stable_key)}));expect(new Set(states.map((s:any)=>s.root)).size).toBe(1);await testInfo.attach(stage,{body:JSON.stringify({saved_revision:saved.id,edit_version:saved.edit_version,snapshot_path:"domains.answer.entries",states,endpoint,response:result},null,2),contentType:"application/json"});return {result,target};}
 const before=await evidence("auto-before-save");expect(before.result.reusable_diagrams).toHaveLength(0);await expect(before.target.diagram.getByText("他の小問で図を再利用するには、図を選択した後に保存してください。",{exact:true})).toBeVisible();await saveAuthoring(page);expect((await evidence("auto-after-save")).result.reusable_diagrams).toHaveLength(1);
 const second=await editor(1),manual=second.diagram.getByRole("region",{name:"PDFから手動切り取り",exact:true});await manual.getByRole("button",{name:"PDFから切り取る",exact:true}).click();const viewer=page.getByRole("region",{name:"利用資料PDF",exact:true}),overlay=viewer.getByLabel("図の範囲を矩形選択",{exact:true});await expect(overlay).toBeVisible();await viewer.getByRole("button",{name:"ページに合わせる",exact:true}).click();await overlay.scrollIntoViewIfNeeded();await viewer.locator(".pdf-pane-viewport").evaluate(el=>{el.scrollTop=el.scrollHeight-el.clientHeight;});const bounds=(await overlay.boundingBox())!,dimensions=(await overlay.getAttribute("viewBox"))!.split(" ").map(Number);const point=(x:number,y:number)=>({x:bounds.x+x/dimensions[2]*bounds.width,y:bounds.y+y/dimensions[3]*bounds.height});const a=point(345,625),b=point(505,765);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:8});await page.mouse.up();await manual.getByRole("button",{name:"選択範囲をプレビュー",exact:true}).click();await expect(manual.getByAltText("手動切り取りのプレビュー",{exact:true})).toBeVisible();await manual.getByRole("button",{name:"使用する",exact:true}).click();expect((await evidence("manual-before-save")).result.reusable_diagrams).toHaveLength(1);await saveAuthoring(page);
 const after=await evidence("two-origins-after-save");expect(after.result.reusable_diagrams).toHaveLength(2);expect(after.result.reuse_diagnostics.candidate_count).toBe(2);if(productionExclusion){for(const id of[first.id,second.id]){const entry=after.result.reuse_diagnostics.entry_states.find((e:any)=>e.entry_id===id);expect(entry.effective_disposition).toBe("include");expect(entry.ignore_reason).toBe("classified_as_non_answer");}}await expect(after.target.diagram.getByAltText("再利用できる図",{exact:true})).toHaveCount(2);await expect(after.target.diagram.getByText("他の小問で図を再利用するには、図を選択した後に保存してください。",{exact:true})).toHaveCount(0);
 const noInference=await calls(page);for(let i=0;i<2;i++){const target=await editor(2);const action=target.diagram.getByRole("button",{name:"この図を再利用",exact:true}).and(target.diagram.locator("button:enabled"));await action.first().click();await saveAuthoring(page);}expect(await calls(page)).toEqual(noInference);
 await page.reload();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();await page.getByRole("link",{name:"戻る",exact:true}).click();await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();expect((await evidence("two-origins-after-resume")).result.reusable_diagrams).toHaveLength(2);
 const ignored=await editor(0);await ignored.entry.getByLabel("候補の扱い").selectOption("ignored");await saveAuthoring(page);const negative=await evidence("explicitly-ignored-origin");expect(negative.result.reusable_diagrams).toHaveLength(1);expect(negative.result.reuse_diagnostics.decisions.some((d:any)=>d.entry_id===first.id&&d.reason==="entry_not_included")).toBe(true);expect(negative.result.reuse_diagnostics.entry_states.find((e:any)=>e.entry_id===first.id).accepted_diagram_count).toBe(1);expect(await calls(page)).toEqual(noInference);
 for(const domain of["questions","model-answers","rubrics"])expect(await(await page.request.get(`${base}/${domain}`)).json()).toEqual([]);
});
