import {confirmAnalysis,expectUnsavedAnalysisHint} from "./authoringNotifications";
import {test,expect,type Page} from "@playwright/test";
import {readFile} from "node:fs/promises";
test.setTimeout(90000);
test.skip(!process.env.AUTHORING_SAVE_WARNING_PDF_PATH,"isolated real API/production build required");
async function login(page:Page){await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);}
async function calls(page:Page){return Promise.all(["ocr","math_ocr","ornith_rubric_draft","grader"].map(async p=>{const data=await(await page.request.get(`${process.env.LLM_GRADER_RUNTIME_MANAGER_URL}/runtimes/${p}/logs?tail=1000`)).json();return data.lines.filter((s:string)=>s.includes("POST /v1/chat/completions")).length;}));}
async function start(page:Page,name:string){
 await login(page);await page.setViewportSize({width:1920,height:1080});const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
 const exam=await(await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name,total_points:10}})).json();await page.goto(`/tests/${exam.id}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();return {exam,base:`/api/v1/tests/${exam.id}`};
}
async function upload(page:Page,path:string){await page.getByLabel("利用資料",{exact:true}).selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption("question_sheet");await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:"question.pdf",mimeType:"application/pdf",buffer:await readFile(path)});await expect(page.getByLabel("利用資料",{exact:true})).toContainText("question.pdf");await page.getByRole("button",{name:"いいえ",exact:true}).click();}
async function resume(page:Page,id:string){await page.getByRole("link",{name:"戻る",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/tests/${id}$`));await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();}

test("quiet Save tooltip immediately enables analysis and reanalysis; saved Back/resume and stale Save are safe",async({page})=>{
 const {exam,base}=await start(page,"Save analysis readiness");const controls=page.getByRole("group",{name:"利用資料の操作"}),guidance=controls.getByRole("tooltip");
 const before=await calls(page);await upload(page,process.env.AUTHORING_SPLIT_QUESTION_PDF_PATH!);await expectUnsavedAnalysisHint(page,controls);await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeDisabled();
 await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();await expect(guidance).toHaveCount(0);await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeEnabled();expect(await calls(page)).toEqual(before);
 await confirmAnalysis(page,controls,"解析");await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();
 const view=page.getByLabel("問題の表示切替",{exact:true});await view.getByRole("button",{name:"本文編集",exact:true}).click();const editor=page.getByLabel("問題文",{exact:true});await editor.fill((await editor.inputValue())+"\nCurrent unsaved teacher text");await expectUnsavedAnalysisHint(page,controls);await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeDisabled();
 page.once("dialog",d=>d.dismiss());await page.getByRole("link",{name:"戻る",exact:true}).click();await expect(page).toHaveURL(/\/authoring$/);await expect(editor).toContainText("Current unsaved teacher text");
 const previous=(await(await page.request.get(base+"/authoring")).json()).revision,counts=await calls(page);await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();await expect(guidance).toHaveCount(0);await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 const saved=(await(await page.request.get(base+"/authoring")).json()).revision;expect(saved.id).toBe(previous.id);expect(saved.edit_version).toBe(previous.edit_version+1);expect(await calls(page)).toEqual(counts);
 const stale=await page.request.put(base+"/authoring",{data:{snapshot:previous.snapshot,expected_edit_version:previous.edit_version}});expect(stale.status()).toBe(409);expect(await(await page.request.get(base+"/authoring")).json().then(r=>r.revision)).toEqual(saved);
 await resume(page,exam.id);expect((await(await page.request.get(base+"/authoring")).json()).revision).toEqual(saved);await expect(page.getByLabel("問題プレビュー",{exact:true})).toContainText("Current unsaved teacher text");await page.reload();await expect(page.getByLabel("問題プレビュー",{exact:true})).toContainText("Current unsaved teacher text");expect(await calls(page)).toEqual(counts);
});

test("unreconciled source text persists with a separate saved warning, safe anchors and actionable source navigation",async({page})=>{
 const {exam,base}=await start(page,"Source warning is not Save failure");await upload(page,process.env.AUTHORING_SAVE_WARNING_PDF_PATH!);await page.getByRole("button",{name:"保存",exact:true}).first().click();
 const controls=page.getByRole("group",{name:"利用資料の操作"});await expect(controls.getByRole("button",{name:"解析",exact:true})).toBeEnabled();await confirmAnalysis(page,controls,"解析");await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();
 const initial=(await(await page.request.get(base+"/authoring")).json()).revision;expect(initial.snapshot.nodes[0].ordered_content.some((i:{type:string})=>i.type==="figure_region")).toBe(true);
 await page.getByLabel("問題の表示切替",{exact:true}).getByRole("button",{name:"本文編集",exact:true}).click();const editor=page.getByLabel("問題文",{exact:true}),text="Teacher rewrite across figure anchors\n$unfinished exact local buffer";await editor.fill(text);
 const counts=await calls(page);await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();const warning=page.getByLabel("保存済み内容の出典確認",{exact:true});await expect(warning).toContainText("編集内容は保存されています");await expect(page.getByText(/未保存の編集は保持されています/)).toHaveCount(0);await expect(controls.getByRole("button",{name:"再解析",exact:true})).toBeEnabled();
 const saved=(await(await page.request.get(base+"/authoring")).json()).revision;expect(saved.snapshot.nodes[0].ordered_content).toEqual(initial.snapshot.nodes[0].ordered_content);expect(saved.snapshot.question_text_buffers[saved.snapshot.nodes[0].stable_key]).toBe(text);
 await warning.getByRole("button",{name:"確認する",exact:true}).click();await expect(editor).toHaveValue(text);await resume(page,exam.id);await expect(page.getByLabel("問題プレビュー",{exact:true})).toContainText("Teacher rewrite");await expect(warning).toContainText("保存されています");await page.reload();await expect(page.getByLabel("問題プレビュー",{exact:true})).toContainText("Teacher rewrite");expect((await(await page.request.get(base+"/authoring")).json()).revision).toEqual(saved);expect(await calls(page)).toEqual(counts);
 for(const domain of ["questions","model-answers","rubrics"])expect(await(await page.request.get(base+`/${domain}`)).json()).toEqual([]);
});
