import {test,expect} from "@playwright/test";
import {rubricCriterionLabel,rubricSplitOffset} from "../lib/rubricEditing";

test("criterion labels and Unicode/math cursor boundaries are stable",()=>{
 expect(rubricCriterionLabel(0)).toBe("基準1");expect(rubricCriterionLabel(2)).toBe("基準3");
 expect(rubricSplitOffset("😀 first. second.",10)).toBe(9);
 for(const [text,offset] of [["first second",0],["first second",12],["first   ",5],["A $x^2$ B",4],["A $$x^2$$ B",5],["😀 text",1]] as const)expect(()=>rubricSplitOffset(text,offset)).toThrow();
 expect(rubricSplitOffset("A $x^2$ B",7)).toBe(7);
});

test.setTimeout(120000);
test("authoring criterion cursor/assisted split, Undo, points and section ownership survive resume",async({page})=>{
 test.skip(!process.env.RUNTIME_MANAGER_E2E,"isolated API/RuntimeManager required");
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error"&&!e.text().includes("503 (Service Unavailable)"))errors.push(e.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Rubric reliability "+Date.now(),total_points:10}});expect(created.status()).toBe(201);const tid=(await created.json()).id,base=`/api/v1/tests/${tid}/authoring`;
 await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 await page.getByRole("checkbox",{name:"採点基準",exact:true}).check();const rubric=page.getByRole("region",{name:"採点基準候補",exact:true}),texts=()=>rubric.getByLabel(/^基準\d+の本文$/),points=()=>rubric.getByLabel(/^基準\d+の配点$/);
 await rubric.getByRole("button",{name:"編集する",exact:true}).click();await rubric.getByRole("button",{name:"基準を追加",exact:true}).click();await texts().first().fill("First condition. Second condition.");await points().first().fill("10");
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(0,0);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"先頭・末尾"})).toBeVisible();await expect(texts()).toHaveCount(1);
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(t.value.length,t.value.length);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"先頭・末尾"})).toBeVisible();await expect(texts()).toHaveCount(1);
 // No synthetic select event or arrow key is required to update the cursor.
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(17,24);});let modelRequests=0;page.on("request",r=>{if(r.url().includes("/rubric-split")&&!r.postDataJSON()?.offset)modelRequests++;});
 await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();const proposal=page.getByRole("region",{name:"採点基準の分割案",exact:true});await expect(proposal).toBeVisible();await expect(proposal).toContainText("元の配点: 10点");await expect(texts()).toHaveCount(1);expect(modelRequests).toBe(0);
 await proposal.getByRole("button",{name:"この分割を適用",exact:true}).click();await expect(texts()).toHaveCount(2);await expect(texts().nth(0)).toHaveValue("First condition.");await expect(texts().nth(1)).toHaveValue("Second condition.");await expect(points().nth(0)).toHaveValue("0");await expect(points().nth(1)).toHaveValue("0");
 await texts().nth(1).evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(6,6);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).first().click();await expect(page.getByRole("alert").filter({hasText:"分割する基準の本文欄"})).toBeVisible();await expect(texts()).toHaveCount(2);
 await points().nth(0).fill("4");await points().nth(1).fill("6");await rubric.getByRole("button",{name:"上と結合",exact:true}).nth(1).click();await expect(texts()).toHaveCount(1);await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(2);await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(1);await expect(points().first()).toHaveValue("10");
 await texts().first().fill("[split_failure]");await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"分割案を作成できませんでした"})).toBeVisible();await expect(rubric.getByRole("button",{name:"分割案を作成",exact:true})).toBeEnabled();await expect(texts().first()).toHaveValue("[split_failure]");
 await texts().first().fill("5 points: explain overfitting. 5 points: cite evidence.");
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route("**/rubric-split",async route=>{const response=await route.fetch();await gate;await route.fulfill({response});});
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();const running=rubric.getByRole("button",{name:"分割案を作成中…",exact:true});await expect(running).toBeDisabled();await expect(running.locator(".spinner")).toBeVisible();release();await expect(proposal).toBeVisible();await page.unroute("**/rubric-split");await proposal.getByRole("button",{name:"キャンセル",exact:true}).click();await expect(proposal).toHaveCount(0);await expect(texts()).toHaveCount(1);expect(modelRequests).toBe(2);
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(proposal).toBeVisible();await proposal.getByRole("button",{name:"この分割を適用",exact:true}).click();await expect(texts()).toHaveCount(2);await expect(points().nth(0)).toHaveValue("5");await expect(points().nth(1)).toHaveValue("5");await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(1);
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(proposal).toBeVisible();await proposal.getByRole("button",{name:"この分割を適用",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 const saved=(await(await page.request.get(base)).json()).revision;await page.reload();await rubric.getByRole("button",{name:"編集する",exact:true}).click();await expect(texts()).toHaveCount(2);expect((await(await page.request.get(base)).json()).revision.snapshot.rubrics).toEqual(saved.snapshot.rubrics);
 await page.getByRole("link",{name:"戻る",exact:true}).click();await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await expect(rubric.getByRole("heading",{name:"基準1",exact:true})).toBeVisible();await expect(rubric.getByRole("heading",{name:"基準2",exact:true})).toBeVisible();expect((await(await page.request.get(base)).json()).revision).toEqual(saved);await expect(page.getByText(/観点1|基準1基準/)).toHaveCount(0);
 for(const suffix of ["questions","model-answers","rubrics"])expect(await(await page.request.get(`/api/v1/tests/${tid}/${suffix}`)).json()).toEqual([]);expect(errors).toEqual([]);
});

test("source-backed criterion split keeps native segment provenance and explicit range points",async({page})=>{
 test.skip(!process.env.RUBRIC_SPLIT_TEST_ID,"source-backed split fixture required");
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const tid=process.env.RUBRIC_SPLIT_TEST_ID!,qid=process.env.RUBRIC_SPLIT_QUESTION_ID!,base=`/api/v1/tests/${tid}`,materials=await(await page.request.get(base+"/materials")).json();const imported=await page.request.post(base+"/model-answer-imports",{data:{material_id:materials[0].id}});expect(imported.status()).toBe(201);
 const formal=await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>await(await page.request.get(base+"/"+suffix)).json()));
 await page.goto(`/tests/${tid}/authoring`);await page.getByLabel("対象設問",{exact:true}).selectOption(qid);await page.getByRole("checkbox",{name:"解答",exact:true}).uncheck();await page.getByRole("checkbox",{name:"採点基準",exact:true}).check();const rubric=page.getByRole("region",{name:"採点基準候補",exact:true}).first();await rubric.getByRole("button",{name:"編集する",exact:true}).click();const text=rubric.getByLabel("基準1の本文",{exact:true}),original=await text.inputValue();expect(original.trim()).not.toBe("");const reviewed=`5 points: ${original}\n5 points: additional teacher condition.`;await text.fill(reviewed);await rubric.getByLabel("基準1の配点",{exact:true}).fill("10");const offset=reviewed.indexOf("5 points:",1);expect(offset).toBeGreaterThan(0);
 const before=(await(await page.request.get(base+"/authoring")).json()).revision,entry=before.snapshot.domains.answer.entries.find((e:{authoring_question_key:string})=>e.authoring_question_key===qid);
 await text.evaluate((el,pos)=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(pos,pos);},offset);await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await page.getByRole("region",{name:"採点基準の分割案",exact:true}).getByRole("button",{name:"この分割を適用",exact:true}).click();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 const saved=(await(await page.request.get(base+"/authoring")).json()).revision,rows=saved.snapshot.domains.answer.entries.find((e:{id:string})=>e.id===entry.id).rubric_edits;expect(rows.reduce((total:number,c:{points:number})=>total+c.points,0)).toBe(10);expect(rows[0].segment_ids).toEqual(rows[1].segment_ids);expect(rows[0].segment_ids.length).toBeGreaterThan(0);expect(rows[0].provenance.end).toBe(rows[1].provenance.start);expect(saved.snapshot.nodes).toEqual(before.snapshot.nodes);expect(saved.snapshot.domains.answer.material_id).toBe(before.snapshot.domains.answer.material_id);
 await page.reload();await rubric.getByRole("button",{name:"編集する",exact:true}).click();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);expect((await(await page.request.get(base+"/authoring")).json()).revision.snapshot.domains.answer.entries.find((e:{id:string})=>e.id===entry.id).rubric_edits).toEqual(rows);expect(await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>await(await page.request.get(base+"/"+suffix)).json()))).toEqual(formal);
});
