import {saveAuthoring} from "./authoringNotifications";
import {test,expect} from "@playwright/test";
import {rubricCriterionLabel,rubricSplitOffset} from "../lib/rubricEditing";

test("criterion labels and Unicode/math cursor boundaries are stable",()=>{
 expect(rubricCriterionLabel(0)).toBe("基準1");expect(rubricCriterionLabel(2)).toBe("基準3");
 expect(rubricSplitOffset("😀 first. second.",10)).toBe(9);
 for(const [text,offset] of [["first second",0],["first second",12],["first   ",5],["A $x^2$ B",4],["A $$x^2$$ B",5],["😀 text",1]] as const)expect(()=>rubricSplitOffset(text,offset)).toThrow();
 expect(rubricSplitOffset("A $x^2$ B",7)).toBe(7);
});

test.setTimeout(120000);
test("authoring criterion cursor/assisted split, Undo, points and section ownership survive resume",async({page})=>{
 test.skip(!process.env.RUNTIME_MANAGER_E2E,"isolated API/RuntimeManager required");
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));page.on("console",e=>{if(e.type()==="error"&&!e.text().includes("503 (Service Unavailable)"))errors.push(e.text());});
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Rubric reliability "+Date.now(),total_points:10}});expect(created.status()).toBe(201);const tid=(await created.json()).id,base=`/api/v1/tests/${tid}/authoring`;
 await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 await page.getByRole("checkbox",{name:"採点基準",exact:true}).check();const rubric=page.getByRole("region",{name:"採点基準候補",exact:true}),texts=()=>rubric.getByLabel(/^基準\d+の本文$/),points=()=>rubric.getByLabel(/^基準\d+の配点$/);
 await rubric.getByRole("button",{name:"編集する",exact:true}).click();await rubric.getByRole("button",{name:"基準を追加",exact:true}).click();await texts().first().fill("First condition. Second condition.");await points().first().fill("10");
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(0,0);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"先頭・末尾"})).toBeVisible();await expect(texts()).toHaveCount(1);
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(t.value.length,t.value.length);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"先頭・末尾"})).toBeVisible();await expect(texts()).toHaveCount(1);
 // No synthetic select event or arrow key is required to update the cursor.
 await texts().first().evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(17,24);});let modelRequests=0;page.on("request",r=>{if(r.url().includes("/rubric-split")&&!r.postDataJSON()?.offset)modelRequests++;});
 await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();const proposal=page.getByRole("dialog",{name:/基準\d+の分割案/});await expect(proposal).toBeVisible();await expect(proposal).toContainText("元の配点: 10点");await expect(texts()).toHaveCount(1);expect(modelRequests).toBe(0);
 await proposal.getByRole("button",{name:"分割案を適用",exact:true}).click();await expect(texts()).toHaveCount(2);await expect(texts().nth(0)).toHaveValue("First condition.");await expect(texts().nth(1)).toHaveValue("Second condition.");await expect(points().nth(0)).toHaveValue("0");await expect(points().nth(1)).toHaveValue("0");
 await texts().nth(1).evaluate(el=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(6,6);});await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).first().click();await expect(page.getByRole("alert").filter({hasText:"分割する基準の本文欄"})).toBeVisible();await expect(texts()).toHaveCount(2);
 await points().nth(0).fill("4");await points().nth(1).fill("6");await rubric.getByRole("button",{name:"上と結合",exact:true}).nth(1).click();await expect(texts()).toHaveCount(1);await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(2);await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(1);await expect(points().first()).toHaveValue("10");
 await texts().first().fill("[split_failure]");await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(page.getByRole("alert").filter({hasText:"分割案を作成できませんでした"})).toBeVisible();await expect(rubric.getByRole("button",{name:"分割案を作成",exact:true})).toBeEnabled();await expect(texts().first()).toHaveValue("[split_failure]");
 await texts().first().fill("5 points: explain overfitting. 5 points: cite evidence.");
 let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve);await page.route("**/rubric-split",async route=>{const response=await route.fetch();await gate;await route.fulfill({response});});
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();const running=rubric.getByRole("button",{name:"分割案を作成中…",exact:true});await expect(running).toBeDisabled();await expect(running.locator(".spinner")).toBeVisible();release();await expect(proposal).toBeVisible();await page.unroute("**/rubric-split");await proposal.getByRole("button",{name:"取消",exact:true}).click();await expect(proposal).toHaveCount(0);await expect(texts()).toHaveCount(1);expect(modelRequests).toBe(2);
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(proposal).toBeVisible();await proposal.getByRole("button",{name:"分割案を適用",exact:true}).click();await expect(texts()).toHaveCount(2);await expect(points().nth(0)).toHaveValue("5");await expect(points().nth(1)).toHaveValue("5");await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(texts()).toHaveCount(1);
 await rubric.getByRole("button",{name:"分割案を作成",exact:true}).click();await expect(proposal).toBeVisible();await proposal.getByRole("button",{name:"分割案を適用",exact:true}).click();await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 const saved=(await(await page.request.get(base)).json()).revision;await page.reload();await rubric.getByRole("button",{name:"編集する",exact:true}).click();await expect(texts()).toHaveCount(2);expect((await(await page.request.get(base)).json()).revision.snapshot.rubrics).toEqual(saved.snapshot.rubrics);
 await page.getByRole("link",{name:"戻る",exact:true}).click();await page.getByRole("region",{name:"次に行う作業"}).getByRole("button",{name:"編集を続ける ›",exact:true}).click();await expect(rubric.getByRole("heading",{name:"基準1",exact:true})).toBeVisible();await expect(rubric.getByRole("heading",{name:"基準2",exact:true})).toBeVisible();expect((await(await page.request.get(base)).json()).revision).toEqual(saved);await expect(page.getByText(/観点1|基準1基準/)).toHaveCount(0);
 for(const suffix of ["questions","model-answers","rubrics"])expect(await(await page.request.get(`/api/v1/tests/${tid}/${suffix}`)).json()).toEqual([]);expect(errors).toEqual([]);
});

test("source-backed criterion split keeps native segment provenance and explicit range points",async({page})=>{
 test.skip(!process.env.RUBRIC_SPLIT_TEST_ID,"source-backed split fixture required");
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const tid=process.env.RUBRIC_SPLIT_TEST_ID!,qid=process.env.RUBRIC_SPLIT_QUESTION_ID!,base=`/api/v1/tests/${tid}`,materials=await(await page.request.get(base+"/materials")).json();const imported=await page.request.post(base+"/model-answer-imports",{data:{material_id:materials[0].id}});expect(imported.status()).toBe(201);
 const formal=await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>await(await page.request.get(base+"/"+suffix)).json()));
 await page.goto(`/tests/${tid}/authoring`);await page.getByLabel("対象設問",{exact:true}).selectOption(qid);await page.getByRole("checkbox",{name:"解答",exact:true}).uncheck();await page.getByRole("checkbox",{name:"採点基準",exact:true}).check();const rubric=page.getByRole("region",{name:"採点基準候補",exact:true}).first();await rubric.getByRole("button",{name:"編集する",exact:true}).click();const text=rubric.getByLabel("基準1の本文",{exact:true}),original=await text.inputValue();expect(original.trim()).not.toBe("");const originalOffset=Math.max(1,original.indexOf(" ")+1);await text.evaluate((el,pos)=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(pos,pos);},originalOffset);await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();const originalDialog=page.getByRole("dialog",{name:"基準1の分割案",exact:true});await expect(originalDialog).toContainText(original);await originalDialog.getByRole("button",{name:"取消",exact:true}).click();await expect(text).toHaveValue(original);const reviewed=`5 points: ${original}\n5 points: additional teacher condition.`;await text.fill(reviewed);await rubric.getByLabel("基準1の配点",{exact:true}).fill("10");const offset=reviewed.indexOf("5 points:",1);expect(offset).toBeGreaterThan(0);
 const before=(await(await page.request.get(base+"/authoring")).json()).revision,entry=before.snapshot.domains.answer.entries.find((e:{authoring_question_key:string})=>e.authoring_question_key===qid);
 await text.evaluate((el,pos)=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(pos,pos);},offset);await rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).click();await page.getByRole("dialog",{name:/基準\d+の分割案/}).getByRole("button",{name:"分割案を適用",exact:true}).click();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);await page.getByRole("button",{name:"保存",exact:true}).first().click();await expect(page.getByText("未保存の変更があります",{exact:true})).toHaveCount(0);
 const saved=(await(await page.request.get(base+"/authoring")).json()).revision,rows=saved.snapshot.domains.answer.entries.find((e:{id:string})=>e.id===entry.id).rubric_edits;expect(rows.reduce((total:number,c:{points:number})=>total+c.points,0)).toBe(10);expect(rows[0].segment_ids).toEqual(rows[1].segment_ids);expect(rows[0].segment_ids.length).toBeGreaterThan(0);expect(rows[0].provenance.end).toBe(rows[1].provenance.start);expect(saved.snapshot.nodes).toEqual(before.snapshot.nodes);expect(saved.snapshot.domains.answer.material_id).toBe(before.snapshot.domains.answer.material_id);
 await page.reload();await rubric.getByRole("button",{name:"編集する",exact:true}).click();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(2);expect((await(await page.request.get(base+"/authoring")).json()).revision.snapshot.domains.answer.entries.find((e:{id:string})=>e.id===entry.id).rubric_edits).toEqual(rows);expect(await Promise.all(["questions","model-answers","rubrics"].map(async suffix=>await(await page.request.get(base+"/"+suffix)).json()))).toEqual(formal);
});

test("middle Japanese criterion proposal is immediately visible, keyboard-safe and atomic",async({page})=>{
 test.skip(!process.env.RUNTIME_MANAGER_E2E,"isolated services required");
 await page.goto("/login");await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);await page.getByRole("button",{name:"ログイン"}).click();await expect(page).not.toHaveURL(/login/);
 const seed=await(await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();const created=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Middle criterion dialog",total_points:10}});const tid=(await created.json()).id,base=`/api/v1/tests/${tid}/authoring`;
 await page.goto(`/tests/${tid}/authoring`);await page.getByRole("button",{name:"設問を追加",exact:true}).click();
 await saveAuthoring(page);
 await page.getByRole("checkbox",{name:"採点基準",exact:true}).check();const rubric=page.getByRole("region",{name:"採点基準候補",exact:true});await rubric.getByRole("button",{name:"編集する",exact:true}).click();
 const first="過学習の説明：学習データに過度に適合する状態であることが説明されている。",second="未知データ・テストデータでは性能が低下することが説明されている。";
 for(const text of ["任意の別基準",first+second,"末尾の別基準"]){await rubric.getByRole("button",{name:"基準を追加",exact:true}).click();await rubric.getByLabel(/^基準\d+の本文$/).last().fill(text);}
 await saveAuthoring(page);await page.setViewportSize({width:1000,height:560});
 const middle=rubric.getByLabel("基準2の本文",{exact:true}),trigger=rubric.getByRole("button",{name:"カーソル位置で分割",exact:true}).nth(1),dialog=page.getByRole("dialog",{name:"基準2の分割案",exact:true});
 async function open(){await middle.evaluate((el,pos)=>{const t=el as HTMLTextAreaElement;t.focus();t.setSelectionRange(pos,pos);},(await middle.inputValue()).indexOf("。")+1);await trigger.click();await expect(dialog).toBeVisible();await expect(dialog.getByRole("heading",{name:"元の基準",exact:true})).toBeVisible();await expect(dialog.getByRole("button",{name:"分割案を適用"})).toBeVisible();const box=(await dialog.boundingBox())!;expect(box.y).toBeGreaterThanOrEqual(0);expect(box.y+box.height).toBeLessThanOrEqual(561);}
 await open();await expect(dialog).toContainText(first);await expect(dialog).toContainText(second);expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);
 for(let i=0;i<5;i++){await page.keyboard.press("Tab");expect(await dialog.evaluate(el=>el.contains(document.activeElement))).toBe(true);}
 await page.keyboard.press("Escape");await expect(dialog).toHaveCount(0);await expect(trigger).toBeFocused();await expect(middle).toHaveValue(first+second);await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);
 const edited=first.replace("過学習の説明：","");await middle.fill(edited+second);await open();await expect(dialog).not.toContainText("過学習の説明：");await dialog.getByRole("button",{name:"分割案を適用"}).click();await expect(dialog).toHaveCount(0);await expect(rubric.getByLabel("基準2の本文",{exact:true})).toHaveValue(edited);await expect(rubric.getByLabel("基準3の本文",{exact:true})).toHaveValue(second);await expect(rubric.getByLabel("基準4の本文",{exact:true})).toHaveValue("末尾の別基準");
 await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();await expect(middle).toHaveValue(edited+second);
 await middle.fill("5 points: explain overfitting. 5 points: cite evidence.");const assisted=rubric.getByRole("button",{name:"分割案を作成",exact:true}).nth(1);await assisted.click();await expect(dialog).toBeVisible();await dialog.getByRole("button",{name:"取消",exact:true}).click();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);await assisted.click();await expect(dialog).toBeVisible();await dialog.getByRole("button",{name:"分割案を適用"}).click();await expect(rubric.getByLabel("基準2の配点",{exact:true})).toHaveValue("5");await expect(rubric.getByLabel("基準3の配点",{exact:true})).toHaveValue("5");await expect(rubric.getByLabel("基準4の本文",{exact:true})).toHaveValue("末尾の別基準");await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();
 await middle.fill(edited.repeat(40)+second);await open();const body=dialog.locator(".authoring-dialog-body");expect(await body.evaluate(el=>el.scrollHeight>el.clientHeight)).toBe(true);await expect(dialog.getByRole("button",{name:"取消",exact:true})).toBeVisible();await dialog.getByRole("button",{name:"取消",exact:true}).click();await middle.fill(edited+second);
 // A transient preflight failure retains the exact proposal and supports retry.
 await open();await page.route(`**/tests/${tid}/authoring`,route=>route.fulfill({status:503,contentType:"application/json",body:JSON.stringify({detail:"一時的に確認できませんでした"})}));await dialog.getByRole("button",{name:"分割案を適用"}).click();await expect(dialog.getByRole("alert")).toBeVisible();await expect(dialog).toBeVisible();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);await page.unroute(`**/tests/${tid}/authoring`);await dialog.getByRole("button",{name:"分割案を適用"}).click();await expect(dialog).toHaveCount(0);await rubric.getByRole("button",{name:"編集を元に戻す",exact:true}).click();
 // A separate saved update must block application, retain the proposal and never overwrite it.
 await open();const state=(await(await page.request.get(base)).json()).revision;expect((await page.request.put(base,{data:{snapshot:state.snapshot,expected_edit_version:state.edit_version}})).ok()).toBe(true);await dialog.getByRole("button",{name:"分割案を適用"}).click();await expect(dialog.getByRole("alert")).toContainText("別の画面");await expect(dialog.getByRole("button",{name:"分割案を適用"})).toBeDisabled();await expect(rubric.getByLabel(/^基準\d+の本文$/)).toHaveCount(3);await dialog.getByRole("button",{name:"取消",exact:true}).click();
});
