import { test, expect } from "@playwright/test";
test.skip(!process.env.RUBRIC_SPLIT_TEST_ID, "isolated managed runtime fixture required");
test("on-demand LaTeX proposals preserve answer and rubric text across reload", async ({page}) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", {name: "ログイン"}).click();
  await expect(page).not.toHaveURL(/\/login/);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error" && !message.text().includes("503")) errors.push(message.text()); });
  const tid = process.env.RUBRIC_SPLIT_TEST_ID;
  const mats = await (await page.request.get(`/api/v1/tests/${tid}/materials`)).json();
  const draft = await (await page.request.post(`/api/v1/tests/${tid}/model-answer-imports`, {data: {material_id: mats[0].id}})).json();
  let calls = 0;
  page.on("request", request => {if (request.url().endsWith("/latex-normalize")) calls++;});
  await page.goto(`/model-answer-import-reviews/${draft.id}`);
  await page.getByLabel("編集対象").selectOption(`question:${process.env.RUBRIC_SPLIT_QUESTION_ID}`);
  const answer = page.getByLabel(/^模範解答本文 /).first();
  const control = page.getByRole("region", {name: "LaTeX変換", exact: true}).first();
  expect(calls).toBe(0);
  await answer.fill("Precision = TP / (TP + FP)\n答え：0.800（80%）");
  await page.route("**/latex-normalize", async route => {await new Promise(resolve => setTimeout(resolve, 250)); await route.continue();});
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("status")).toContainText("数式を解析中");
  await expect(control.locator(".katex")).toBeVisible();
  await control.getByRole("button", {name: "キャンセル"}).click();
  await expect(answer).toHaveValue("Precision = TP / (TP + FP)\n答え：0.800（80%）");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await control.getByRole("button", {name: "この変換を適用"}).click();
  const normalized = "Precision = $\\frac{TP}{TP+FP}$\n答え：0.800（80%）";
  await expect(answer).toHaveValue(normalized);
  const rubric = page.locator(".rubric-candidate-edit").first();
  await rubric.getByRole("textbox").fill("TP / (TP + FP)");
  const oldPoints = await rubric.getByRole("spinbutton").inputValue();
  await rubric.getByRole("button", {name: "数式をLaTeX化"}).click();
  await rubric.getByRole("button", {name: "この変換を適用"}).click();
  await expect(rubric.getByRole("textbox")).toHaveValue("$\\frac{TP}{TP+FP}$");
  await expect(rubric.getByRole("spinbutton")).toHaveValue(oldPoints);
  const savedResponse = page.waitForResponse(r => r.request().method() === "PUT" && r.url().endsWith(draft.id));
  await page.getByRole("button", {name: "下書き保存"}).click();
  const saved = await (await savedResponse).json();
  const entry = saved.entries.find((e: {answer_text: string}) => e.answer_text === normalized);
  expect(entry.teacher_correction.teacher_confirmed).toBe(true);
  expect(entry.teacher_correction.latex_normalization.profile).toBe("ornith_rubric_draft");
  expect(entry.rubric_edits[0].provenance.latex_normalization.original_text).toBe("TP / (TP + FP)");
  const beforeReload = calls;
  await page.reload(); await page.getByLabel("編集対象").selectOption(`question:${process.env.RUBRIC_SPLIT_QUESTION_ID}`);
  await expect(answer).toHaveValue(normalized); await expect(rubric.getByRole("textbox")).toHaveValue("$\\frac{TP}{TP+FP}$");
  expect(calls).toBe(beforeReload);
  await answer.fill("Accuracy = TP+TN / TP+FP+FN+TN");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeDisabled();
  await expect(control.getByRole("checkbox")).toBeVisible();
  await control.getByRole("checkbox").check();
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeEnabled();
  await control.getByRole("button", {name: "キャンセル"}).click();
  await answer.fill("[latex_failure]");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("LLMから変換結果");
  await expect(control.getByRole("alert")).toContainText("元の本文は保持");
  await expect(answer).toHaveValue("[latex_failure]");
  await answer.fill("[latex_malformed]");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("有効な変換結果");
  await expect(answer).toHaveValue("[latex_malformed]");
  await answer.fill("TP / (TP + FP)");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeEnabled();
  await answer.fill("Teacher changed text");
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeDisabled();
  await control.getByRole("button", {name: "キャンセル"}).click();
  await answer.fill("[latex_numeric_change] 0.800");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("保持を確認できない");
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeDisabled();
  await expect(answer).toHaveValue("[latex_numeric_change] 0.800");
  await control.getByRole("button", {name: "キャンセル"}).click();
  await answer.fill("[latex_bad_math] TP / FP");
  await control.getByRole("button", {name: "数式をLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("構文を確認");
  await expect(control.getByRole("button", {name: "この変換を適用"})).toBeDisabled();
  await control.getByRole("button", {name: "キャンセル"}).click();
  await page.goto(`/tests/${tid}?section=answers&question=${process.env.RUBRIC_SPLIT_QUESTION_ID}`);
  const normalAnswer = page.getByLabel("模範解答本文", {exact: true});
  await expect(normalAnswer).toBeVisible();
  await normalAnswer.fill("TP / (TP + FP)");
  const normalAnswerControl = page.locator(".model-answer-editor").getByRole("region", {name: "LaTeX変換", exact: true});
  await normalAnswerControl.getByRole("button", {name: "数式をLaTeX化"}).click();
  await normalAnswerControl.getByRole("button", {name: "この変換を適用"}).click();
  await expect(normalAnswer).toHaveValue("$\\frac{TP}{TP+FP}$");
  await page.getByRole("button", {name: "＋採点基準を追加", exact: true}).click();
  const normalRubric = page.locator(".rubric-criterion-card").first();
  await normalRubric.getByRole("textbox").fill("TP / (TP + FP)");
  await normalRubric.getByRole("button", {name: "数式をLaTeX化"}).click();
  await normalRubric.getByRole("button", {name: "この変換を適用"}).click();
  await expect(normalRubric.getByRole("textbox")).toHaveValue("$\\frac{TP}{TP+FP}$");
  expect(errors).toEqual([]);
});
