import { test, expect } from "@playwright/test";
test.skip(!process.env.LATEX_STATE_TEST_ID, "isolated runtime and state fixture required");
test("formal, saved and local content remain independent; cold LaTeX starts runtime and warm reuses PID", async ({page, playwright}) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", {name: "ログイン"}).click();
  await expect(page).not.toHaveURL(/\/login/);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => {if (message.type() === "error") errors.push(message.text());});
  const anonymous = await playwright.request.newContext({baseURL: process.env.E2E_FRONTEND_URL});
  const unauth = await anonymous.post("/api/v1/text-tools/latex-normalize", {data: {text: "TP / FP"}});
  expect(unauth.status()).toBe(401); await anonymous.dispose();
  const managerUrl = process.env.LLM_GRADER_RUNTIME_MANAGER_URL!;
  await page.request.post(`${managerUrl}/runtimes/ornith_rubric_draft/stop`);
  const student = await playwright.request.newContext({baseURL: process.env.E2E_FRONTEND_URL});
  expect((await student.post("/api/v1/auth/login", {data: {email: process.env.TEXT_TOOL_STUDENT_EMAIL,
    password: process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD}})).status()).toBe(200);
  const forbidden = await student.post("/api/v1/text-tools/latex-normalize", {data: {text: "TP / (TP + FP)"}});
  expect(forbidden.status()).toBe(403); expect((await forbidden.json()).error.code).toBe("TEACHER_ROLE_REQUIRED");
  await student.dispose();
  const afterDenied = await (await page.request.get(`${managerUrl}/runtimes/ornith_rubric_draft/status`)).json();
  expect(afterDenied.state).toBe("stopped"); expect(afterDenied.pid).toBeNull();
  const invalid = await page.request.post("/api/v1/text-tools/latex-normalize", {data: {text: "TP / FP", context_type: "invalid"}});
  expect(invalid.status()).toBe(422); expect((await invalid.json()).error.code).toBe("validation_error");
  const tid = process.env.LATEX_STATE_TEST_ID!, qid = process.env.LATEX_STATE_QUESTION_ID!;
  const created = await page.request.post(`/api/v1/tests/${tid}/model-answer-imports`, {data: {material_id: process.env.LATEX_STATE_MATERIAL_ID}});
  const draft = await created.json();
  const entry = draft.entries.find((e: {question_id: string}) => e.question_id === qid);
  const saved = await page.request.put(`/api/v1/model-answer-import-drafts/${draft.id}`, {data: {expected_revision: draft.revision,
    entries: draft.entries.map((e: {id: string; question_id: string; answer_text: string}) => ({id: e.id, question_id: e.question_id,
      answer_text: e.id === entry.id ? "Draft answer B." : e.answer_text, disposition: e.id === entry.id ? "include" : "excluded"}))}});
  expect(saved.status()).toBe(200);
  let calls = 0;
  page.on("request", r => {if (r.url().endsWith("/text-tools/latex-normalize")) calls++;});
  await page.goto(`/model-answer-import-reviews/${draft.id}`);
  await page.getByLabel("編集対象").selectOption(`question:${qid}`);
  const formal = page.getByRole("group", {name: "登録済み模範解答", exact: true});
  const savedView = page.getByRole("group", {name: "保存済み下書き模範解答", exact: true}).first();
  const editor = page.getByLabel(/^模範解答本文 /).first();
  await expect(formal).toContainText("Formal answer A.");
  await expect(savedView).toContainText("Draft answer B.");
  await expect(editor).toHaveValue("Draft answer B.");
  expect(calls).toBe(0);
  await editor.fill("TP / (TP + FP)");
  await expect(page.getByText("未保存の変更があります").first()).toBeVisible();
  await expect(formal).toContainText("Formal answer A."); await expect(savedView).toContainText("Draft answer B.");
  const manager = process.env.LLM_GRADER_RUNTIME_MANAGER_URL!;
  expect((await page.request.post(`${manager}/runtimes/ornith_rubric_draft/stop`)).ok()).toBeTruthy();
  const stopped = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(stopped.state).toBe("stopped");
  const control = page.getByRole("region", {name: "LaTeX変換", exact: true}).first();
  const start = Date.now();
  const result = page.waitForResponse(r => r.url().endsWith("/text-tools/latex-normalize") && r.request().method() === "POST");
  await control.getByRole("button", {name: "LLMでLaTeX化"}).click();
  await expect(control.getByRole("status")).toContainText("初回は時間");
  const response = await result; expect(response.status()).toBe(200);
  expect(Date.now() - start).toBeGreaterThan(700);
  const running = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(running.state).toBe("ready"); expect(running.pid).toBeTruthy();
  await control.getByRole("button", {name: "キャンセル"}).click();
  await control.getByRole("button", {name: "LLMでLaTeX化"}).click();
  await control.getByRole("button", {name: "この変換を適用"}).click();
  const warm = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(warm.pid).toBe(running.pid); expect(warm.started_at).toBe(running.started_at);
  const normalized = "$\\frac{TP}{TP+FP}$";
  await expect(editor).toHaveValue(normalized); await expect(savedView).toContainText("Draft answer B.");
  const put = page.waitForResponse(r => r.url().endsWith(draft.id) && r.request().method() === "PUT");
  await page.getByRole("button", {name: "下書き保存"}).click(); const putBody = await (await put).json();
  expect(putBody.revision).toBeGreaterThan(draft.revision);
  await expect(savedView).toContainText("TP"); await expect(savedView).not.toContainText("Draft answer B.");
  await expect(formal).toContainText("Formal answer A.");
  await page.reload(); await page.getByLabel("編集対象").selectOption(`question:${qid}`);
  await expect(editor).toHaveValue(normalized); await expect(formal).toContainText("Formal answer A.");
  expect(calls).toBe(2);
  await page.getByRole("button", {name: "模範解答として登録", exact: true}).click();
  await expect(page).toHaveURL(/section=answers/);
  await expect(page.getByLabel("模範解答本文", {exact: true})).toHaveValue(normalized);
  await page.reload(); await expect(page.getByLabel("模範解答本文", {exact: true})).toHaveValue(normalized);
  const persisted = await (await page.request.get(`/api/v1/model-answer-import-drafts/${draft.id}`)).json();
  expect(persisted.saved_answers.find((a: {question_id: string}) => a.question_id === qid).answer_text).toBe(normalized);
  expect(persisted.entries.find((e: {id: string}) => e.id === entry.id).answer_text).toBe(normalized);
  expect(persisted.confirmed_entry_ids).toContain(entry.id);
  const finalRuntime = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(finalRuntime.pid).toBe(running.pid); expect(errors).toEqual([]);
});

test("structured resource 404 is not diagnosed as a missing text API", async ({page}) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", {name: "ログイン"}).click();
  await expect(page).not.toHaveURL(/\/login/);
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => {if (message.type() === "error" && !message.text().includes("404")) errors.push(message.text());});
  const tid = process.env.LATEX_STATE_TEST_ID!;
  const response = await page.request.post(`/api/v1/tests/${tid}/model-answer-imports`, {data: {material_id: process.env.LATEX_STATE_MATERIAL_ID}});
  expect(response.status()).toBe(201); const draft = await response.json();
  await page.goto(`/model-answer-import-reviews/${draft.id}`);
  await page.getByLabel("編集対象").selectOption(`question:${process.env.LATEX_STATE_QUESTION_ID}`);
  const editor = page.getByLabel(/^模範解答本文 /).first();
  await editor.fill("TP / (TP + FP)");
  const control = page.getByRole("region", {name: "LaTeX変換", exact: true}).first();
  let body: unknown = {error: {code: "RESOURCE_NOT_FOUND", message: "RESOURCE_NOT_FOUND"}};
  await page.route("**/api/v1/text-tools/latex-normalize", route => route.fulfill({status: 404, contentType: "application/json", body: JSON.stringify(body)}));
  await control.getByRole("button", {name: "LLMでLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("対象リソースが見つかりません");
  await expect(control.getByRole("alert")).not.toContainText("APIが見つかりません");
  await expect(editor).toHaveValue("TP / (TP + FP)");
  body = {detail: "Not Found"};
  await control.getByRole("button", {name: "LLMでLaTeX化"}).click();
  await expect(control.getByRole("alert")).toContainText("LaTeX変換APIが見つかりません");
  await expect(editor).toHaveValue("TP / (TP + FP)");
  expect(errors).toEqual([]);
});
