import { test, expect } from "@playwright/test";

const testId = process.env.REVIEW_UX_TEST_ID;
const questionIds: string[] = JSON.parse(process.env.REVIEW_UX_QUESTION_IDS || "[]");
test.skip(!testId, "requires isolated real API, production frontend and managed classifier stub");

test("review disposition, manual answer, navigation and in-pane PDF zoom persist", async ({ page }) => {
  const pageErrors: string[] = [];
  const createRequests: string[] = [];
  const classifyRequests: string[] = [];
  page.on("request", (request) => {
    if (request.method() === "POST" && request.url().endsWith("/model-answer-imports")) createRequests.push(request.url());
    if (request.method() === "POST" && request.url().endsWith("/classify")) classifyRequests.push(request.url());
  });
  page.on("pageerror", (error) => pageErrors.push(error.message));
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", { name: "ログイン" }).click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto(`/tests/${testId}?section=answers`);
  const questionNav = page.getByLabel("対象設問");
  for (const label of ["問題1", "問題2", "問題3"]) {
    await questionNav.selectOption({ label });
    await expect(page.getByTestId("selected-question-detail")).toContainText(label);
  }
  expect(pageErrors).toEqual([]);
  await page.getByRole("button", { name: "ナビゲーションを折りたたむ" }).click();
  await expect(page.locator(".sidebar")).toHaveClass(/sidebar-collapsed/);
  const created = page.waitForResponse((response) => response.url().endsWith("/model-answer-imports") && response.request().method() === "POST");
  await page.getByRole("button", { name: "review-ux-model-answer.pdfを解析して模範解答を確認" }).click();
  await expect(page.getByRole("status").filter({ hasText: "PDFを解析しています" })).toBeVisible();
  const draft = await (await created).json();
  await expect(page).toHaveURL(/model-answer-import-reviews/);
  await expect(page.locator(".sidebar")).toHaveClass(/sidebar-collapsed/);
  await expect(page.getByRole("heading", { name: "編集中の下書き", exact: true })).toBeVisible();
  await expect(page.getByRole("group", { name: "登録済み模範解答" })).toContainText("未登録");
  await expect(page.locator(".model-answer-review-toolbar").getByRole("button", { name: "下書き保存" })).toBeVisible();
  const viewer = page.getByRole("region", { name: "模範解答PDF" });
  await expect(viewer.getByRole("button", { name: "拡大" })).toBeEnabled();
  await viewer.getByRole("button", { name: "拡大" }).click();
  await expect(viewer.getByLabel(/表示倍率/)).not.toHaveText("100%");
  await viewer.getByRole("button", { name: "ページに合わせる" }).click();
  await viewer.getByRole("button", { name: "幅に合わせる" }).click();
  await viewer.getByRole("button", { name: "倍率をリセット" }).click();
  await expect(viewer.getByLabel("表示倍率 100%")).toBeVisible();
  for (let i = 0; i < 5; i++) await viewer.getByRole("button", { name: "拡大" }).click();
  const viewport = viewer.locator(".pdf-pane-viewport");
  await expect.poll(() => viewport.evaluate((element) => element.scrollWidth > element.clientWidth && element.scrollHeight > element.clientHeight)).toBe(true);
  await viewport.evaluate((element) => { element.scrollLeft = 120; element.scrollTop = 120; });
  const beforePan = await viewport.evaluate((element) => ({ left: element.scrollLeft, top: element.scrollTop }));
  await viewport.scrollIntoViewIfNeeded();
  const viewportBox = await viewport.boundingBox();
  expect(viewportBox).not.toBeNull();
  const panX = viewportBox!.x + viewportBox!.width / 2;
  const panY = viewportBox!.y + Math.min(120, viewportBox!.height / 2);
  await page.mouse.move(panX, panY);
  await page.mouse.down();
  await page.mouse.move(panX - 40, panY - 40, { steps: 5 });
  await page.mouse.up();
  const afterPan = await viewport.evaluate((element) => ({ left: element.scrollLeft, top: element.scrollTop }));
  expect(afterPan.left).toBeGreaterThan(beforePan.left);
  expect(afterPan.top).toBeGreaterThan(beforePan.top);
  await viewer.getByRole("button", { name: "次のページ" }).click();
  await expect(viewer.getByText("2 / 2")).toBeVisible();
  await viewer.getByRole("button", { name: "前のページ" }).click();
  await expect(viewer.getByText("1 / 2")).toBeVisible();
  await page.getByLabel("模範解答 1 の対応先").selectOption("__excluded__");
  await expect(page.getByText("取り込み対象外として除外されています。")).toBeVisible();
  await expect(page.getByLabel("模範解答本文 1")).toHaveCount(0);
  await page.getByRole("button", { name: "取り込み対象に戻す" }).click();
  await expect(page.getByLabel("模範解答本文 1")).toBeVisible();
  await page.getByLabel("模範解答 1 の対応先").selectOption("__excluded__");
  await page.getByLabel("編集対象").selectOption(`question:${questionIds[1]}`);
  await page.getByLabel("模範解答 2 の対応先").selectOption("__unassigned__");
  await expect(page.getByLabel("編集対象")).toHaveValue(`unassigned:${draft.entries[1].id}`);
  await page.getByLabel("編集対象").selectOption(`question:${questionIds[0]}`);
  await page.getByRole("button", { name: /問題1 に模範解答を追加/ }).click();
  await expect(page.getByRole("button", { name: "模範解答として登録" })).toBeDisabled();
  const validation = page.getByRole("status", { name: "登録できない理由" });
  await expect(validation).toContainText("問題1");
  await expect(validation).toContainText("模範解答本文が空");
  await validation.getByRole("button", { name: /模範解答本文が空.*該当候補を表示/ }).click();
  await expect(page.locator(".model-answer-candidate-validation")).toContainText("模範解答本文が空");
  await expect(page.locator(".model-answer-import-entry textarea:focus")).toHaveCount(1);
  await page.getByLabel("模範解答本文 4").fill("Teacher-authored answer.");
  await expect(validation).toHaveCount(0);
  await page.getByRole("button", { name: "下書き保存" }).click();
  await expect(page.getByText("下書きを保存しました。")).toBeVisible();
  await page.reload();
  await page.getByLabel("編集対象").selectOption(`excluded:${draft.entries[0].id}`);
  await expect(page.getByText("取り込み対象外として除外されています。")).toBeVisible();
  await page.getByLabel("編集対象").selectOption(`unassigned:${draft.entries[1].id}`);
  await expect(page.getByLabel("模範解答 2 の対応先")).toHaveValue("__unassigned__");
  await page.getByLabel("編集対象").selectOption(`question:${questionIds[0]}`);
  await expect(page.getByLabel("模範解答本文 4")).toHaveValue("Teacher-authored answer.");
  const confirmed = page.waitForResponse((response) => response.url().endsWith("/confirm"));
  await page.getByRole("button", { name: "模範解答として登録" }).click();
  expect((await confirmed).status()).toBe(200);
  const answers = await (await page.request.get(`/api/v1/tests/${testId}/model-answers`)).json();
  expect(answers).toHaveLength(2);
  expect(answers.find((answer: { question_id: string }) => answer.question_id === questionIds[0]).answer_text).toBe("Teacher-authored answer.");
  const persisted = await (await page.request.get(`/api/v1/model-answer-import-drafts/${draft.id}`)).json();
  expect(persisted.entries[0].disposition).toBe("excluded");
  expect(persisted.entries[0].source.segments.length).toBeGreaterThan(0);
  expect(persisted.entries[1].disposition).toBe("unassigned");
  expect(persisted.entries[3].source.kind).toBe("teacher_manual");
  await page.getByRole("button", { name: "ナビゲーションを展開" }).click();
  await expect(page.locator(".sidebar")).not.toHaveClass(/sidebar-collapsed/);
  await page.goto(`/tests/${testId}?section=answers`);
  await expect(page.getByRole("button", { name: "前回の解析結果を編集" })).toBeVisible();
  const createCountBeforeResume = createRequests.length;
  const classifyCountBeforeResume = classifyRequests.length;
  await page.getByRole("button", { name: "前回の解析結果を編集" }).click();
  await expect(page).toHaveURL(new RegExp(`/model-answer-import-reviews/${draft.id}$`));
  await expect(page.getByLabel("模範解答本文 4")).toHaveValue("Teacher-authored answer.");
  expect(createRequests).toHaveLength(createCountBeforeResume);
  expect(classifyRequests).toHaveLength(classifyCountBeforeResume);
  await page.getByRole("link", { name: "戻る" }).click();
  const secondCreated = page.waitForResponse((response) => response.url().endsWith("/model-answer-imports") && response.request().method() === "POST");
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("button", { name: "再解析する" }).click();
  const secondDraft = await (await secondCreated).json();
  await expect(page.getByRole("heading", { name: "編集中の下書き" })).toBeVisible();
  await expect(page.getByRole("group", { name: "登録済み模範解答" })).toBeVisible();
  await expect(page.getByRole("group", {name: "登録済み模範解答"})).toContainText("Teacher-authored answer.");
  page.once("dialog", (dialog) => dialog.accept());
  await page.getByRole("group", {name: "登録済み模範解答"}).locator("summary").click();
  await page.getByRole("button", { name: "登録済み模範解答を読み込む" }).click();
  await expect(page.getByLabel("模範解答本文 1")).toHaveValue("Teacher-authored answer.");
  await page.getByRole("button", { name: "下書き保存" }).click();
  await page.reload();
  await expect(page.getByLabel("模範解答本文 1")).toHaveValue("Teacher-authored answer.");
  const loadedDraft = await (await page.request.get(`/api/v1/model-answer-import-drafts/${secondDraft.id}`)).json();
  expect(loadedDraft.entries[0].loaded_model_answer.id).toBe(answers.find((answer: { question_id: string }) => answer.question_id === questionIds[0]).id);
  expect(loadedDraft.entries[0].source).toEqual(secondDraft.entries[0].source);
  expect(pageErrors).toEqual([]);
});
