import { test, expect } from "@playwright/test";

const testId = process.env.REVIEW_UX_TEST_ID;
const questionIds: string[] = JSON.parse(process.env.REVIEW_UX_QUESTION_IDS || "[]");
test.skip(!testId, "requires isolated real API, production frontend and managed classifier stub");

test("review disposition, manual answer, navigation and in-pane PDF zoom persist", async ({ page }) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", { name: "ログイン" }).click();
  await expect(page).not.toHaveURL(/\/login/);
  await page.goto(`/tests/${testId}?section=answers`);
  await page.getByRole("button", { name: "ナビゲーションを折りたたむ" }).click();
  await expect(page.locator(".sidebar")).toHaveClass(/sidebar-collapsed/);
  const created = page.waitForResponse((response) => response.url().endsWith("/model-answer-imports") && response.request().method() === "POST");
  await page.getByRole("button", { name: "review-ux-model-answer.pdfを解析して模範解答を確認" }).click();
  await expect(page.getByRole("status").filter({ hasText: "PDFを解析しています" })).toBeVisible();
  const draft = await (await created).json();
  await expect(page).toHaveURL(/model-answer-import-reviews/);
  await expect(page.locator(".sidebar")).toHaveClass(/sidebar-collapsed/);
  await expect(page.getByRole("heading", { name: "LLM取り込み結果", exact: true })).toBeVisible();
  await expect(page.getByText("保存済み模範解答（")).toHaveCount(0);
  await expect(page.locator(".model-answer-review-toolbar").getByRole("button", { name: "変更を保存" })).toBeVisible();
  const viewer = page.getByRole("region", { name: "模範解答PDF" });
  await expect(viewer.getByRole("button", { name: "拡大" })).toBeEnabled();
  await viewer.getByRole("button", { name: "拡大" }).click();
  await expect(viewer.getByLabel(/表示倍率/)).not.toHaveText("100%");
  await viewer.getByRole("button", { name: "ページに合わせる" }).click();
  await viewer.getByRole("button", { name: "幅に合わせる" }).click();
  await viewer.getByRole("button", { name: "倍率をリセット" }).click();
  await expect(viewer.getByLabel("表示倍率 100%")).toBeVisible();
  await page.getByLabel("模範解答 1 の対応先").selectOption("__excluded__");
  await page.getByLabel("模範解答 2 の対応先").selectOption("__unassigned__");
  await page.getByRole("button", { name: /問題1 に模範解答を追加/ }).click();
  await page.getByLabel("模範解答本文 4").fill("Teacher-authored answer.");
  await page.getByRole("button", { name: "変更を保存" }).click();
  await expect(page.getByText("変更を保存しました。")).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("模範解答 1 の対応先")).toHaveValue("__excluded__");
  await expect(page.getByLabel("模範解答 2 の対応先")).toHaveValue("__unassigned__");
  await expect(page.getByLabel("模範解答本文 4")).toHaveValue("Teacher-authored answer.");
  const confirmed = page.waitForResponse((response) => response.url().endsWith("/confirm"));
  await page.getByRole("button", { name: "確認した模範解答を登録" }).click();
  expect((await confirmed).status()).toBe(200);
  const answers = await (await page.request.get(`/api/v1/tests/${testId}/model-answers`)).json();
  expect(answers).toHaveLength(2);
  expect(answers.find((answer: { question_id: string }) => answer.question_id === questionIds[0]).answer_text).toBe("Teacher-authored answer.");
  const persisted = await (await page.request.get(`/api/v1/model-answer-import-drafts/${draft.id}`)).json();
  expect(persisted.entries[0].disposition).toBe("excluded");
  expect(persisted.entries[0].source.segments.length).toBeGreaterThan(0);
  expect(persisted.entries[1].disposition).toBe("unassigned");
  expect(persisted.entries[3].source.kind).toBe("teacher_manual");
  await page.getByRole("button", { name: "ナビゲーションを展開" }).click();
  await expect(page.locator(".sidebar")).not.toHaveClass(/sidebar-collapsed/);
  await page.goto(`/tests/${testId}?section=answers`);
  await page.getByRole("button", { name: "review-ux-model-answer.pdfを解析して模範解答を確認" }).click();
  await expect(page.getByRole("heading", { name: "今回のLLM取り込み結果" })).toBeVisible();
  await page.getByText(/保存済み模範解答（2件）/).click();
  await expect(page.getByText("Teacher-authored answer.")).toBeVisible();
});
