import {test, expect} from "@playwright/test";
import {readFile} from "node:fs/promises";
test.skip(!process.env.QUESTION_MATH_TEST_ID, "isolated Question source fixture required");

test("Question source OCR reuses crop/proposal UI and isolates local, saved and formal content", async ({page}) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", {name:"ログイン"}).click();
  await expect(page).not.toHaveURL(/login/);
  const errors: string[] = [];
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", m => {if (m.type() === "error") errors.push(m.text());});
  const testId = process.env.QUESTION_MATH_TEST_ID!;
  const manager = process.env.LLM_GRADER_RUNTIME_MANAGER_URL!;
  await page.request.post(`${manager}/runtimes/math_ocr/stop`);
  const uploaded = await page.request.post(`/api/v1/tests/${testId}/question-materials`, {
    headers: {"content-type":"application/pdf", "x-filename":"question-math.pdf"},
    data: await readFile(process.env.QUESTION_MATH_PDF_PATH!)});
  expect(uploaded.status()).toBe(201);
  const extraction = await uploaded.json();
  const draftResponse = await page.request.post(`/api/v1/question-imports/${extraction.id}/draft`);
  expect(draftResponse.status()).toBe(201);
  const draft = await draftResponse.json();
  const reviewResponse = await page.request.post(`/api/v1/question-import-drafts/${draft.id}/reviews`);
  expect(reviewResponse.status()).toBe(201);
  const initial = await reviewResponse.json();
  const reviewId = initial.id;
  const path = `/api/v1/question-import-reviews/${reviewId}`;
  const read = async () => (await page.request.get(path)).json();
  const questions = async () => (await page.request.get(`/api/v1/tests/${testId}/questions`)).json();
  const answersBefore = await (await page.request.get(`/api/v1/tests/${testId}/model-answers`)).json();
  const rubricsBefore = await (await page.request.get(`/api/v1/tests/${testId}/rubrics`)).json();
  await page.goto(`/question-import-reviews/${reviewId}`);
  const formula = page.locator('[data-content-type="formula"]').first();
  const editor = formula.getByLabel("数式 1のLaTeX", {exact:true});
  const control = formula.getByRole("region", {name:"LaTeX変換", exact:true});
  const original = await editor.inputValue();
  expect(original).toContain("Precision=");
  await expect(page.locator(".review-tree")).toContainText("問題2");
  let calls = 0;
  page.on("request", r => {if(r.url().endsWith("/math-ocr")) calls++;});
  const getProposal = async () => {
    const received = page.waitForResponse(r => r.url().endsWith("/math-ocr"));
    await control.getByRole("button", {name:"数式をLaTeX化"}).click();
    await expect(control.locator(".processing-spinner")).toBeVisible();
    await expect(control).toHaveAttribute("aria-busy", "true");
    await expect(control.getByRole("button", {name:"数式をLaTeX化"})).toBeDisabled();
    const response = await received;
    expect(response.status()).toBe(200);
    const proposal = await response.json();
    expect(proposal.source.kind).toBe("question_review");
    expect(proposal.source.review_id).toBe(reviewId);
    expect(proposal.source.node_key).toBe(initial.snapshot.nodes[0].stable_key);
    expect(proposal.source.source_sha256).toBe(initial.source_pdf_sha256);
    expect(proposal.math_regions).toHaveLength(1);
    expect(proposal.math_regions[0].validation).toBe("accepted");
    expect(proposal.math_regions[0].grouping_method).toBe("geometry");
    expect(proposal.math_regions[0].ornith_used).toBe(false);
    expect(proposal.math_regions[0].source_field).toBe("choices[0].message.reasoning_content");
    return proposal;
  };
  const proposed = await getProposal();
  await expect(control.locator(".katex").first()).toBeVisible();
  await control.getByText("数式の原文: ページ 1", {exact:true}).click();
  await expect(control.getByAltText("数式OCR対象 1")).toBeVisible();
  await expect(control.getByRole("checkbox")).toHaveCount(0);
  await expect(control.getByText("適用後も数式は編集できます。", {exact:true})).toBeVisible();
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeEnabled();
  await expect(editor).toHaveValue(original);
  expect(await read()).toEqual(initial);
  expect(await questions()).toEqual([]);
  await control.getByRole("button", {name:"キャンセル"}).click();
  await expect(editor).toHaveValue(original);
  const cold = await (await page.request.get(`${manager}/runtimes/math_ocr/status`)).json();
  await getProposal();
  await editor.fill(original+" teacher changed");
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeDisabled();
  await expect(control).toContainText("本文が変更されています");
  await control.getByRole("button", {name:"キャンセル"}).click();
  await editor.fill(original);
  // Exercise rejected and invalid display proposals without another model call.
  await page.route("**/math-ocr", r => r.fulfill({json: {...proposed, status:"rejected", reason_code:"math_identifier_invalid"}}));
  await control.getByRole("button", {name:"数式をLaTeX化"}).click();
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeDisabled();
  await control.getByRole("button", {name:"キャンセル"}).click();
  await page.unroute("**/math-ocr");
  await page.route("**/math-ocr", r => r.fulfill({json: {...proposed, normalized_text:"$\\frac{TP}{$"}}));
  await control.getByRole("button", {name:"数式をLaTeX化"}).click();
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeDisabled();
  await expect(control).toContainText("構文を確認してください");
  await control.getByRole("button", {name:"キャンセル"}).click();
  await page.unroute("**/math-ocr");
  // A raw-LaTeX formula field preserves multiple independent proposals using
  // a presentation-only environment, rather than leaving nested $$ wrappers.
  const candidate = proposed.math_regions[0].final_candidate;
  await page.route("**/math-ocr", r => r.fulfill({json: {...proposed,
    normalized_text:`$$${candidate}$$\n\n$$${candidate}$$`}}));
  await control.getByRole("button", {name:"数式をLaTeX化"}).click();
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeEnabled();
  await control.getByRole("button", {name:"この変換を適用"}).click();
  await expect(editor).toHaveValue(`\\begin{gathered}${candidate}\\\\${candidate}\\end{gathered}`);
  expect(await read()).toEqual(initial);
  await editor.fill(original);
  await page.unroute("**/math-ocr");
  await getProposal();
  await control.getByRole("button", {name:"この変換を適用"}).press("Enter");
  await expect(editor).toHaveValue(/\\frac\{TP\}\{TP\+FP\}/);
  const edited = (await editor.inputValue()).replace("Precision=", "\\mathrm{Precision}=");
  await editor.fill(edited);
  await expect(editor).toHaveValue(edited);
  expect(await read()).toEqual(initial);
  expect(await questions()).toEqual([]);
  page.on("dialog", dialog => dialog.accept());
  await page.reload();
  await expect(editor).toHaveValue(original); // No implicit persistence.
  await getProposal();
  await control.getByRole("button", {name:"この変換を適用"}).click();
  await editor.fill(edited);
  const saved = page.waitForResponse(r => r.url().endsWith(`${reviewId}/revisions`) && r.request().method() === "POST");
  await page.getByRole("button", {name:"変更を保存", exact:true}).click();
  expect((await saved).status()).toBe(200);
  const server = await read();
  expect(server.current_revision).toBe(initial.current_revision+1);
  expect(server.snapshot.nodes[0].math_ocr_edits[0].source_sha256).toBe(initial.source_pdf_sha256);
  expect(JSON.stringify(server.snapshot.nodes[0].math_ocr_edits)).not.toContain("crop_image");
  expect(server.snapshot.nodes[1]).toEqual(initial.snapshot.nodes[1]);
  expect(await questions()).toEqual([]);
  await page.reload();
  await expect(editor).toHaveValue(edited);
  const warm = await (await page.request.get(`${manager}/runtimes/math_ocr/status`)).json();
  expect(warm.pid).toBe(cold.pid); expect(warm.started_at).toBe(cold.started_at);
  await page.getByLabel("数式 1の確認", {exact:true}).selectOption("confirmed");
  // Preserve existing warning/confirmation workflow before the final import.
  const ack = page.getByRole("combobox", {name:/確認事項 .*の状態/});
  for(let i=0;i<await ack.count();i++) await ack.nth(i).selectOption("acknowledged");
  await page.getByRole("button", {name:"変更を保存", exact:true}).click();
  const marked = page.waitForResponse(r => r.url().endsWith("/mark-reviewed"));
  await page.getByRole("button", {name:"確認済みにする", exact:true}).click();
  expect((await marked).status()).toBe(200);
  await page.getByRole("button", {name:"問題登録前の最終確認へ", exact:true}).click();
  await expect(page.getByText("問題を登録できます。登録すると、この試験の問題として確定されます。")).toBeVisible();
  await page.getByRole("button", {name:"確認した問題を登録", exact:true}).click();
  await expect.poll(async () => (await questions()).length).toBe(2);
  const formal = await questions();
  expect(JSON.stringify(formal)).toContain("\\\\mathrm{Precision}");
  expect(formal[0].question_text).toContain("次の式の意味を説明せよ。");
  expect(formal[0].question_text).toContain("途中の数値を変更しないこと。");
  expect(formal[0].provenance.math_ocr_edits).toHaveLength(1);
  expect(await (await page.request.get(`/api/v1/tests/${testId}/model-answers`)).json()).toEqual(answersBefore);
  expect(await (await page.request.get(`/api/v1/tests/${testId}/rubrics`)).json()).toEqual(rubricsBefore);
  expect(calls).toBe(7);
  expect(errors).toEqual([]);
});
