import { test, expect } from "@playwright/test";

const reviewId = process.env.REVIEW_SPLIT_ID;
const email = process.env.REVIEW_VALIDATION_EMAIL;
const password = process.env.REVIEW_VALIDATION_PASSWORD;
test.skip(!reviewId || !email || !password, "isolated review API is not configured");

test("teacher confirms a three-part split and Markdown source survives a real API round trip", async ({ page, baseURL }) => {
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(email!);
  await page.getByLabel("パスワード").fill(password!);
  await page.getByRole("button", { name: "ログイン" }).click();
  await expect(page).not.toHaveURL(/\/login/);
  const path = `/api/v1/question-import-reviews/${reviewId}`;
  const read = async () => (await (await page.request.get(`${baseURL}${path}`)).json());
  const before = await read();
  if (!before.snapshot) throw new Error(`Review API did not return a snapshot: ${JSON.stringify(before)}`);
  await page.goto(`/question-import-reviews/${reviewId}`);
  await page.getByRole("button", { name: "小問に分割" }).click();
  const preview = page.getByRole("heading", { name: "小問への分割候補" });
  await expect(preview).toBeVisible();
  await expect(page.getByLabel("小問名")).toHaveCount(3);
  const splitButton = page.getByRole("button", { name: "この内容で分割" });
  await expect(splitButton).toBeEnabled();
  await page.getByLabel("図の所属").selectOption("2");
  await splitButton.click();
  await expect(page.getByRole("navigation", { name: "設問構成" }).getByRole("button")).toHaveCount(4);
  const savedResponse = page.waitForResponse(response => response.url().includes(`${path}/revisions`) && response.request().method() === "POST");
  await page.getByRole("button", { name: "変更を保存", exact: true }).click();
  const saveResponse = await savedResponse;
  expect(saveResponse.status(), await saveResponse.text()).toBe(200);
  await page.reload();
  await expect(page.getByRole("navigation", { name: "設問構成" }).getByRole("button")).toHaveCount(4);
  const saved = await read();
  expect(saved.current_revision).toBe(before.current_revision + 1);
  const nodes = saved.snapshot.nodes;
  expect(nodes.slice(1).map((node: { parent_key: string }) => node.parent_key)).toEqual([nodes[0].stable_key, nodes[0].stable_key, nodes[0].stable_key]);
  expect(nodes[0].ordered_content[0].text).toContain("導入文です。");
  expect(nodes[2].ordered_content.some((item: { type: string }) => item.type === "formula_region")).toBe(true);
  expect(nodes[0].score_semantics).toBe("sum_children");
  expect(nodes[0].score_points).toBeNull();
  expect(nodes.slice(1).every((node: { score_points: number | null }) => node.score_points === null)).toBe(true);
  expect(saved.source_pdf_sha256).toBe(before.source_pdf_sha256);
  expect(saved.regions).toEqual(before.regions);
  expect(nodes[1].ordered_content[0].source_element_ids).toEqual(before.snapshot.nodes[0].ordered_content[0].source_element_ids);
  expect(nodes[3].ordered_content.some((item: { type: string }) => item.type === "figure_region")).toBe(true);
  expect(nodes[1].ordered_content[0].source_slice).toHaveLength(3);
  await page.getByRole("navigation", { name: "設問構成" }).getByRole("button", { name: /\(2\)/ }).click();
  await expect(page.locator('[data-content-type="formula"]')).toHaveCount(1);

  await page.getByRole("navigation", { name: "設問構成" }).getByRole("button", { name: /\(1\)/ }).click();
  const markdown = "- クラス1: $x_1 \\ge 0$\n- クラス0: $x_1 < 0$\n\n1. 条件A\n2. 条件B\n\n**重要**";
  await page.getByLabel("問題文 1").fill(markdown);
  const content = page.locator('[data-content-type="text"]').first();
  await expect(content.locator("ul li")).toHaveCount(2);
  await expect(content.locator("ol li")).toHaveCount(2);
  await expect(content.locator(".katex")).toHaveCount(2);
  const markdownSave = page.waitForResponse(response => response.url().includes(`${path}/revisions`) && response.request().method() === "POST");
  await page.getByRole("button", { name: "変更を保存", exact: true }).click();
  expect((await markdownSave).status()).toBe(200);
  await page.reload();
  await page.getByRole("navigation", { name: "設問構成" }).getByRole("button", { name: /\(1\)/ }).click();
  await expect(page.getByLabel("問題文 1")).toHaveValue(markdown);
  expect((await read()).snapshot.nodes[1].ordered_content[0].text).toBe(markdown);
  await page.getByLabel("問題文 1").fill("<script>window.__reviewXss = true</script>\n\n[bad](javascript:alert(1))");
  await expect(content.locator("script")).toHaveCount(0);
  expect(await page.evaluate(() => (window as Window & { __reviewXss?: boolean }).__reviewXss)).toBeUndefined();
  await expect(content.locator('a[href^="javascript:"]')).toHaveCount(0);
});
