import {test, expect} from "@playwright/test";
test.skip(!process.env.SOURCE_MATH_DRAFT_ID || process.env.LLM_GRADER_STUB_MATH_RESPONSE_MODE !== "formatting_hard", "isolated managed formatting fixture required");

test("formatting-only fallback preserves structure, cold/warm PID and local/saved/formal isolation", async ({page}) => {
  const errors: string[] = [];
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.TEXT_TOOL_TEACHER_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button", {name:"ログイン"}).click();
  await expect(page).not.toHaveURL(/login/);
  page.on("pageerror", e => errors.push(e.message));
  page.on("console", m => {if (m.type() === "error") errors.push(m.text());});
  const id = process.env.SOURCE_MATH_DRAFT_ID!;
  const manager = process.env.LLM_GRADER_RUNTIME_MANAGER_URL!;
  for (const role of ["math_ocr", "ornith_rubric_draft"]) {
    await page.request.post(`${manager}/runtimes/${role}/stop`);
    expect((await (await page.request.get(`${manager}/runtimes/${role}/status`)).json()).state).toBe("stopped");
  }
  await page.goto(`/model-answer-import-reviews/${id}`);
  const editor = page.getByLabel(/^模範解答本文 /).first();
  const original = await editor.inputValue();
  const control = page.getByRole("region", {name:"LaTeX変換", exact:true}).first();
  let requests = 0;
  page.on("request", request => {if (request.url().endsWith("/math-ocr")) requests++;});
  const response = page.waitForResponse(r => r.url().endsWith("/math-ocr"));
  await control.getByRole("button", {name:"数式をLaTeX化"}).click();
  await expect(control.locator(".processing-spinner")).toBeVisible();
  await expect(control).toHaveAttribute("aria-busy", "true");
  await expect(control.getByRole("button", {name:"この変換を適用"})).toHaveCount(0);
  await expect(control.getByRole("button", {name:"数式をLaTeX化"})).toBeDisabled();
  const received = await response;
  expect(received.status()).toBe(200);
  const proposal = await received.json();
  const region = proposal.math_regions[0];
  expect(region.source_field).toBe("choices[0].message.reasoning_content");
  expect(region.deterministic_status).toBe("rejected");
  expect(region.ornith_used).toBe(true);
  expect(region.ornith_profile).toBe("ornith_rubric_draft");
  expect(region.normalization_method).toBe("deterministic_ornith_formatting");
  expect(region.formatting_validation.accepted).toBe(true);
  expect(region.formatting_validation.before.tokens).toEqual(region.formatting_validation.after.tokens);
  expect(region.final_validation.accepted).toBe(true);
  expect(region.final_candidate).toContain("\\frac{24}{30}=0.800");
  await expect(control).toContainText("数式整形: 決定論的 + Ornith書式補助");
  await control.getByText("数式の原文: ページ 1", {exact:true}).click();
  await expect(control.getByAltText("数式OCR対象 1")).toBeVisible();
  await control.getByText("OCR診断", {exact:true}).click();
  await control.getByText("最終検証と書式補助", {exact:true}).click();
  await expect(control).toContainText("Ornith書式補助: 実行");
  await expect(control.locator(".katex").first()).toBeVisible();
  await expect(editor).toHaveValue(original);
  await expect(control.getByRole("checkbox")).toHaveCount(0);
  await expect(control).not.toContainText("変換案を確認しました。");
  await expect(control.getByText("適用後も数式は編集できます。", {exact:true})).toBeVisible();
  await expect(control.getByRole("button", {name:"この変換を適用"})).toBeEnabled();
  await control.getByRole("button", {name:"キャンセル"}).click();
  await expect(editor).toHaveValue(original);
  const before = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(before.state).toBe("ready");
  await control.getByRole("button", {name:"数式をLaTeX化"}).click();
  await control.getByRole("button", {name:"この変換を適用"}).press("Enter");
  const applied = await editor.inputValue();
  const normalized = applied.replace("Precision=", "\\mathrm{Precision}=")+"\n教師の確認メモ";
  await editor.fill(normalized);
  await expect(editor).toHaveValue(normalized);
  expect(normalized).toContain("\\frac{24}{30}=0.800");
  const warm = await (await page.request.get(`${manager}/runtimes/ornith_rubric_draft/status`)).json();
  expect(warm.pid).toBe(before.pid);
  expect(warm.started_at).toBe(before.started_at);
  expect(warm.state).toBe("ready");
  let server = await (await page.request.get(`/api/v1/model-answer-import-drafts/${id}`)).json();
  expect(server.entries[0].answer_text).toBe(original);
  expect(server.saved_answers[0].answer_text).toBe("Formal answer A.");
  const saved = page.waitForResponse(r => r.url().endsWith(id) && r.request().method() === "PUT");
  await page.getByRole("button", {name:"下書き保存"}).click();
  expect((await saved).status()).toBe(200);
  await page.reload(); await expect(editor).toHaveValue(normalized);
  server = await (await page.request.get(`/api/v1/model-answer-import-drafts/${id}`)).json();
  expect(server.entries[0].answer_text).toBe(normalized);
  expect(server.saved_answers[0].answer_text).toBe("Formal answer A.");
  expect(requests).toBe(2);
  await page.getByRole("button", {name:"模範解答として登録", exact:true}).click();
  await expect(page).toHaveURL(/section=answers/);
  await expect(page.getByLabel("模範解答本文", {exact:true})).toHaveValue(normalized);
  await page.reload();
  await expect(page.getByLabel("模範解答本文", {exact:true})).toHaveValue(normalized);
  expect(errors).toEqual([]);
});
