import {test, expect} from "@playwright/test";
import path from "node:path";
import fs from "node:fs";
const enabled=process.env.JUI7_FRESH_SMOKE==="1";
test("fresh Teacher course and source registration without model execution",async({page})=>{
 test.skip(!enabled,"Requires isolated fresh API and demo fixtures (JUI7_FRESH_SMOKE=1)");
 test.setTimeout(150000);
 page.setDefaultTimeout(15000);
 const password="DemoSetup123!"; const teacherPassword="DemoTeacherChanged123!";
 const fixture=process.env.JUI7_FIXTURES||"/tmp/jui7/fixtures";
 await page.goto("/");
 await expect(page).toHaveURL(/\/setup$/);
 await page.getByRole("button",{name:"初期設定を開始"}).click();
 await page.getByLabel("氏名",{exact:true}).fill("Demo Admin");
 await page.getByLabel("メールアドレス").fill("admin-jui7@example.invalid");
 await page.getByLabel("パスワード",{exact:true}).fill(password);
 await page.getByLabel("パスワード（確認）").fill(password);
 await page.getByRole("button",{name:"管理者を作成"}).click();
 await expect(page.getByText("初期設定が完了しました。")).toBeVisible();
 await page.getByRole("button",{name:"ログインへ進む"}).click();
 async function login(email:string,pw:string){await page.getByLabel("メールアドレス").fill(email);await page.getByLabel("パスワード",{exact:true}).fill(pw);await page.getByRole("button",{name:"ログイン",exact:true}).click();}
 await login("admin-jui7@example.invalid",password);
 await page.getByRole("link",{name:"ユーザ管理",exact:true}).click();
 await page.getByRole("button",{name:"ユーザを追加",exact:true}).click();
 await page.getByLabel("氏名",{exact:true}).fill("Demo Teacher");
 await page.getByLabel("メールアドレス").fill("teacher-jui7@example.invalid");
 await page.getByLabel("初期パスワード（空欄なら自動生成）").fill(password);
 await page.getByRole("button",{name:"作成",exact:true}).click();
 await expect(page.getByRole("cell",{name:"Demo Teacher",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"ログアウト"}).click();
 await login("teacher-jui7@example.invalid",password);
 await expect(page).toHaveURL(/change-password/);
 await page.getByLabel("現在のパスワード").fill(password);
 await page.getByLabel("新しいパスワード",{exact:true}).fill(teacherPassword);
 await page.getByLabel("新しいパスワード（確認）").fill(teacherPassword);
 await page.getByRole("button",{name:"変更する"}).click();
 await expect(page).toHaveURL(/\/$/);
 await page.goto("/courses");
 await expect(page).toHaveURL(/\/courses$/);
 await page.getByRole("button",{name:"科目を作成",exact:true}).click();
 await page.getByLabel("科目名",{exact:true}).fill("人工知能");
 await page.getByLabel("年度",{exact:true}).fill("2026");
 await page.getByLabel("開講時期",{exact:true}).selectOption("second_semester");
 await page.getByRole("button",{name:"保存",exact:true}).click();
 await expect(page.getByRole("cell",{name:"後期",exact:true})).toBeVisible();
 await page.getByRole("link",{name:"人工知能",exact:true}).click();
 await page.getByRole("button",{name:"科目を編集",exact:true}).click();
 await page.getByLabel("科目名",{exact:true}).fill("人工知能・機械学習");
 await page.getByRole("button",{name:"保存",exact:true}).click();
 await expect(page.getByRole("heading",{level:1})).toContainText("人工知能・機械学習");
 await expect(page.locator("body")).not.toContainText("second_semester");
 await page.getByRole("button",{name:"テストを作成",exact:true}).first().click();
 await page.getByLabel("テスト名 *",{exact:true}).fill("デモ試験");
 await page.getByRole("button",{name:"保存",exact:true}).click();
 await page.getByRole("link",{name:"デモ試験",exact:true}).click();
 await expect(page).toHaveURL(/\/tests\//);
 const testUrl=page.url();
 const uploadResponses:{role:string;status:number}[]=[];
 const submissionResponses:number[]=[];
 const processingRequests:string[]=[];
 page.on("response",response=>{
   const request=response.request();
   if(request.method()!=="POST")return;
   if(response.url().includes("/materials/upload"))uploadResponses.push({role:request.headers()["x-source-role"],status:response.status()});
   if(/\/tests\/[^/]+\/submissions$/.test(new URL(response.url()).pathname))submissionResponses.push(response.status());
 });
 page.on("request",request=>{
   if(request.method()==="POST"&&/\/(question-materials|question-imports|extractions|grading-jobs)(\/|$)/.test(new URL(request.url()).pathname))processingRequests.push(request.url());
 });
 await page.getByRole("navigation",{name:"テスト準備",exact:true}).getByRole("button",{name:"問題",exact:true}).click();
 const questionRegister=page.getByRole("button",{name:"問題用紙を登録",exact:true});
 await expect(questionRegister).toBeVisible();await expect(questionRegister).toBeDisabled();
 await page.getByLabel("問題用紙ファイルを選択").setInputFiles([path.join(fixture,"question.pdf"),path.join(fixture,"question.png")]);
 await expect(questionRegister).toBeEnabled();expect(uploadResponses).toHaveLength(0);
 await page.route("**/materials/upload",async route=>{
   if(route.request().headers()["x-source-role"]==="question_sheet")await new Promise(resolve=>setTimeout(resolve,400));
   await route.continue();
 });
 await questionRegister.click();
 await expect(questionRegister).toBeDisabled();
 await expect(page.getByText("問題用紙: 2ファイル登録済み",{exact:true})).toBeVisible();
 await page.unroute("**/materials/upload");
 await expect(questionRegister).toBeDisabled();
 expect(uploadResponses.filter(item=>item.role==="question_sheet"&&item.status===201)).toHaveLength(2);
 await page.getByRole("button",{name:"1. question.pdfを確認",exact:true}).click();
 await expect(page.locator("iframe").first()).toBeVisible();
 expect(processingRequests).toHaveLength(0);
 await page.goto(testUrl+"?section=answers");
 const modelRegister=page.getByRole("button",{name:"模範解答を登録",exact:true});
 await expect(modelRegister).toBeVisible();await expect(modelRegister).toBeDisabled();
 await page.getByLabel("模範解答ファイルを選択").setInputFiles([path.join(fixture,"model-answer.pdf"),path.join(fixture,"model-answer.png")]);
 await expect(modelRegister).toBeEnabled();expect(uploadResponses.filter(item=>item.role==="model_answer_source")).toHaveLength(0);
 await modelRegister.click();
 await expect(page.getByText("模範解答: 2ファイル登録済み",{exact:true})).toBeVisible();
 await expect(modelRegister).toBeDisabled();
 expect(uploadResponses.filter(item=>item.role==="model_answer_source"&&item.status===201)).toHaveLength(2);
 await page.getByRole("button",{name:"1. model-answer.pdfを確認",exact:true}).click();
 await expect(page.locator("iframe").first()).toBeVisible();
 await page.getByRole("navigation",{name:"テスト準備",exact:true}).getByRole("button",{name:"学生答案",exact:true}).click();
 const studentRegister=page.getByRole("button",{name:"学生答案を登録",exact:true});
 await expect(studentRegister).toBeVisible();await expect(studentRegister).toBeDisabled();
 await page.getByLabel("学生答案を追加",{exact:true}).setInputFiles([path.join(fixture,"student-1.png"),path.join(fixture,"student-2.png"),path.join(fixture,"student-3.pdf")]);
 await expect(studentRegister).toBeDisabled();
 for(let i=1;i<=3;i++){await page.getByRole("textbox",{name:`学籍番号 ${i}`,exact:true}).fill(`S00${i}`);await page.getByRole("textbox",{name:`氏名 ${i}`,exact:true}).fill(`デモ学生${i}`);}
 await expect(studentRegister).toBeEnabled();expect(uploadResponses.filter(item=>item.role==="student_answer_source")).toHaveLength(0);
 await studentRegister.click();
 await expect(page.getByText("学生答案: 3ファイル登録済み / 学生答案 3件",{exact:true})).toBeVisible();
 await expect(studentRegister).toBeDisabled();
 expect(uploadResponses.filter(item=>item.role==="student_answer_source"&&item.status===201)).toHaveLength(3);
 expect(submissionResponses.filter(status=>status===201)).toHaveLength(3);
 await page.getByRole("button",{name:"1. student-1.pngを確認",exact:true}).click();
 await expect(page.getByRole("img",{name:"学生答案原資料"})).toBeVisible();
 await page.reload();
 await expect(page.getByText("学生答案: 3ファイル登録済み / 学生答案 3件",{exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"1. student-1.pngを確認",exact:true})).toBeVisible();
 await page.getByLabel("学生答案を追加",{exact:true}).setInputFiles([
   {name:"student-1.png",mimeType:"image/png",buffer:fs.readFileSync(path.join(fixture,"student-1.png"))},
   {name:"invalid.txt",mimeType:"text/plain",buffer:Buffer.from("invalid answer source")},
 ]);
 for(const [i,number] of [[1,"S004"],[2,"S005"]] as const){await page.getByRole("textbox",{name:`学籍番号 ${i}`,exact:true}).fill(number);await page.getByRole("textbox",{name:`氏名 ${i}`,exact:true}).fill(`デモ学生${number}`);}
 await studentRegister.click();
 await expect(page.getByText("学生答案: 3ファイル登録済み / 学生答案 4件",{exact:true})).toBeVisible();
 await expect(page.getByText("1件成功・1件失敗",{exact:false})).toBeVisible();
 await expect(page.getByRole("alert").filter({hasText:"PNG・JPEG・PDFを選択してください"})).toBeVisible();
 await expect(studentRegister).toBeEnabled();
 await page.getByRole("button",{name:"取り消し",exact:true}).click();
 await expect(studentRegister).toBeDisabled();
 await page.getByLabel("学生答案を追加",{exact:true}).setInputFiles(path.join(fixture,"student-2.png"));
 await page.getByRole("textbox",{name:"学籍番号 1",exact:true}).fill("S005");
 await page.getByRole("textbox",{name:"氏名 1",exact:true}).fill("デモ学生5");
 let failOnce=true;
 await page.route("**/materials/upload",async route=>{
   if(failOnce){failOnce=false;await route.abort("failed");return;}
   await route.continue();
 });
 await studentRegister.click();
 await expect(page.getByRole("alert").filter({hasText:"接続を確認して再試行してください"})).toBeVisible();
 await expect(studentRegister).toBeEnabled();
 await studentRegister.click();
 await expect(page.getByText("学生答案: 3ファイル登録済み / 学生答案 5件",{exact:true})).toBeVisible();
 await expect(studentRegister).toBeDisabled();
 await page.unroute("**/materials/upload");
 expect(processingRequests).toHaveLength(0);
 if(process.env.JUI7_SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.JUI7_SCREENSHOT_DIR,"teacher-source-upload.png")});
 const health=await page.request.get("/api/v1/health");expect((await health.json()).jobs.pending).toBe(0);
 await page.getByRole("navigation",{name:"テスト準備",exact:true}).getByRole("button",{name:"概要",exact:true}).click();
 await expect(page.getByRole("heading",{name:"入力資料の登録状況"})).toBeVisible();
 await expect(page.locator("body")).not.toContainText("second_semester");
 await page.goto("/courses");
 await expect(page.getByRole("link",{name:"人工知能・機械学習",exact:true})).toBeVisible();
 await page.getByRole("button",{name:"科目を作成",exact:true}).click();
 await page.getByLabel("科目名",{exact:true}).fill("アルゴリズム");
 await page.getByLabel("年度",{exact:true}).fill("2025");
 await page.getByRole("button",{name:"保存",exact:true}).click();
 for(const field of ["year","name","term","created","updated"]){for(const dir of ["asc","desc"]){await page.getByLabel("並べ替え",{exact:true}).selectOption(field+"-"+dir);await expect(page.locator("tbody tr")).toHaveCount(2);}}
 await page.getByLabel("並べ替え",{exact:true}).selectOption("year-asc");
 await expect(page.locator("tbody tr").first()).toContainText("2025");
 await page.getByLabel("並べ替え",{exact:true}).selectOption("year-desc");
 await expect(page.locator("tbody tr").first()).toContainText("2026");
 if(process.env.JUI7_SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.JUI7_SCREENSHOT_DIR,"teacher-courses.png")});
 await page.goto(testUrl);
 await expect(page.locator("body")).toContainText("人工知能・機械学習");
});
