import {openAuthoringEditors} from "./authoringEditMode";
import {test,expect} from "@playwright/test";

test.setTimeout(90000);
test.skip(!process.env.RUNTIME_MANAGER_E2E,"requires isolated FastAPI/production browser harness");
test("whole-test drafts preserve local caret, materials, section state and formal isolation",async({page})=>{
  await page.setViewportSize({width:1920,height:1080});
  await page.goto("/login");
  await page.getByLabel("メールアドレス").fill(process.env.MODEL_ANSWER_CLASSIFICATION_EMAIL!);
  await page.getByLabel("パスワード").fill(process.env.MODEL_ANSWER_CLASSIFICATION_PASSWORD!);
  await page.getByRole("button",{name:"ログイン"}).click();
  await expect(page).not.toHaveURL(/login/);
  const errors:string[]=[];
  page.on("pageerror",e=>errors.push(e.message));
  page.on("console",e=>{if(e.type()==="error")errors.push(e.text());});
  const runtimes=await (await page.request.get("/api/v1/system/runtimes")).json();
  const seed=await (await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}`)).json();
  const response=await page.request.post(`/api/v1/offerings/${seed.course_offering_id}/tests`,{data:{name:"Unified draft browser",total_points:10}});
  expect(response.status()).toBe(201);
  const exam=await response.json();
  const base=`/api/v1/tests/${exam.id}`;
  await page.goto(`/tests/${exam.id}/authoring`);
  await page.getByRole("button",{name:"設問を追加",exact:true}).waitFor();
  await page.getByRole("button",{name:"設問を追加",exact:true}).click();
  await page.getByLabel("問題文",{exact:true}).waitFor({state:"attached"});await openAuthoringEditors(page);const editor=page.getByLabel("問題文",{exact:true});
  const text="2変数 x1, x2 に対して、\nx1 + x2 - 3 の値が\n0以上ならクラス1";
  await editor.fill(text);
  const at=text.indexOf("\n");
  await editor.evaluate((el,at)=>{const area=el as HTMLTextAreaElement;(window as unknown as {authorEditor:HTMLTextAreaElement}).authorEditor=area;area.focus();area.setSelectionRange(at,at);},at);
  await page.keyboard.press("Delete");
  await expect(editor).toHaveValue(text.slice(0,at)+text.slice(at+1));
  expect(await editor.evaluate(el=>({caret:(el as HTMLTextAreaElement).selectionStart,same:el===(window as unknown as {authorEditor:HTMLTextAreaElement}).authorEditor}))).toEqual({caret:at,same:true});
  await page.getByRole("button",{name:"設問設定の変更",exact:true}).click();await page.getByRole("spinbutton",{name:/^配点/}).fill("10");await page.getByLabel("問題の表示切替",{exact:true}).getByRole("button",{name:"本文編集",exact:true}).click();
  await page.getByLabel("模範解答本文",{exact:true}).fill("Answer draft");
  await page.getByRole("button",{name:"基準を追加"}).click();
  await page.getByLabel(/^基準\d+の本文$/).fill("Correct result");
  await page.getByLabel(/^基準\d+の配点$/).fill("10");
  await page.getByRole("checkbox",{name:"問題",exact:true}).uncheck();
  await expect(editor).toHaveCount(0);
  await page.getByRole("checkbox",{name:"問題",exact:true}).check();
  await expect(editor).toHaveValue(text.slice(0,at)+text.slice(at+1));
  await expect(page.getByText("未保存の変更があります",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"保存",exact:true}).first().click();
  await expect(page.locator(".authoring-toast").filter({hasText:"保存しました"}).last()).toBeVisible();
  const saved=await (await page.request.get(base+"/authoring")).json();
  await page.reload();await openAuthoringEditors(page);
  await expect(editor).toHaveValue(saved.revision.snapshot.nodes[0].body_text);
  await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue("Answer draft");
  await expect(page.getByLabel(/^基準\d+の本文$/)).toHaveValue("Correct result");
  // Upload is explicit source registration, never extraction/classification.
  const source=await page.request.get(`/api/v1/tests/${process.env.MODEL_ANSWER_CLASSIFICATION_TEST_ID}/materials/${process.env.MODEL_ANSWER_CLASSIFICATION_MATERIAL_ID}/file`);
  expect(source.status()).toBe(200);
  const bytes=await source.body();
  await page.getByLabel("利用資料",{exact:true}).selectOption("action:add");
  await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:"question.pdf",mimeType:"application/pdf",buffer:bytes});
  await page.getByRole("button",{name:"いいえ",exact:true}).click();
  await expect(page.getByLabel("利用資料",{exact:true})).toContainText("問題用紙 — question.pdf");
  await page.getByLabel("利用資料",{exact:true}).selectOption("action:add");await page.getByLabel("資料の種類",{exact:true}).selectOption("model_answer_source");
  await page.getByLabel("資料を追加",{exact:true}).setInputFiles({name:"answer.pdf",mimeType:"application/pdf",buffer:bytes});
  await page.getByRole("button",{name:"いいえ",exact:true}).click();
  await expect(page.getByLabel("利用資料",{exact:true})).toContainText("模範解答 — answer.pdf");
  const files=await (await page.request.get(base+"/materials")).json();
  const selected=await page.getByLabel("対象設問",{exact:true}).inputValue();
  await page.getByLabel("利用資料",{exact:true}).selectOption(files[0].id);
  expect(await page.getByLabel("対象設問",{exact:true}).inputValue()).toBe(selected);
  await expect(page.getByLabel("模範解答本文",{exact:true})).toHaveValue("Answer draft");
  await page.getByRole("button",{name:"保存",exact:true}).first().click();
  await expect(page.getByText("未保存の変更があります",{exact:true})).not.toBeVisible();
  await page.getByRole("button",{name:"最終確認へ"}).click();
  await expect(page.getByRole("heading",{name:"テスト全体確認",exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"この内容でテストを確定",exact:true})).toBeEnabled();
  for(const domain of ["questions","model-answers","rubrics"]){expect(await (await page.request.get(base+`/${domain}`)).json()).toEqual([]);}
  expect(await (await page.request.get("/api/v1/system/runtimes")).json()).toEqual(runtimes);
  const offering=await (await page.request.get(`/api/v1/offerings/${seed.course_offering_id}`)).json();
  await page.goto("/");
  await expect(page.locator(`a[href='/tests/${exam.id}/authoring']`)).toHaveText("編集を続ける");
  await page.locator(`a[href='/tests/${exam.id}/authoring']`).click();
  await expect(page).toHaveURL(new RegExp(`/tests/${exam.id}/authoring$`));
  await page.goto(`/offerings/${seed.course_offering_id}`);
  const row=page.getByRole("row").filter({hasText:"Unified draft browser"});
  await row.getByRole("button",{name:"削除",exact:true}).click();
  const dialog=page.getByRole("dialog");
  await expect(dialog).toContainText("データは削除せずアーカイブします。");
  await dialog.getByRole("button",{name:"キャンセル",exact:true}).click();
  await expect(row).toBeVisible();
  await row.getByRole("button",{name:"削除",exact:true}).click();
  await dialog.getByLabel("確認用テスト名").fill("Unified draft browser");
  await dialog.getByRole("button",{name:"アーカイブする",exact:true}).click();
  await expect(row).toHaveCount(0);
  expect((await page.request.get(base)).status()).toBe(410);
  expect((await page.request.post(base+"/restore")).status()).toBe(200);
  expect((await page.request.get(`/api/v1/courses/${offering.course_id}/recent-tests`)).status()).toBe(200);
  expect(errors).toEqual([]);
});
